// JF Oficina v0.12.0 — estrutura administrativa, busca global e relatórios
(function(){
 const V='0.12.0';
 function ensureAdminData(){
   S.custom=S.custom||{};
   for(const k of ['funcionarios','fornecedores'])if(!Array.isArray(S.custom[k]))S.custom[k]=[];
 }
 function addShell(){
   if(document.getElementById('admin'))return;
   const nav=document.querySelector('nav'),main=document.querySelector('main'),head=document.querySelector('header');
   if(!nav||!main||!head)return;
   const cad=document.createElement('button');cad.dataset.view='admin';cad.textContent='Cadastros';
   const rep=document.createElement('button');rep.dataset.view='reports';rep.textContent='Relatórios';
   const settings=nav.querySelector('[data-view="settings"]');nav.insertBefore(cad,settings);nav.insertBefore(rep,settings);
   const search=document.createElement('div');search.className='globalSearch';search.innerHTML='<input id="globalSearch" placeholder="Buscar OS, cliente, equipamento, peça, serviço..." autocomplete="off"><div id="globalResults" class="globalResults hidden"></div>';
   head.insertBefore(search,head.lastElementChild);
   const admin=document.createElement('section');admin.id='admin';admin.className='view';admin.innerHTML=`
    <h2>Cadastros</h2><p class="muted">Acesso organizado aos cadastros. Nem tudo precisa ficar visível o tempo inteiro.</p>
    <div class="folderGrid">
      <button class="folder" data-admin="clientes"><b>Clientes</b><span>Cadastro, equipamentos e histórico</span></button>
      <button class="folder" data-admin="equipamentos"><b>Equipamentos</b><span>Máquinas vinculadas aos clientes</span></button>
      <button class="folder" data-admin="produtos"><b>Peças / Produtos</b><span>Códigos, estoque, fornecedor e aplicação</span></button>
      <button class="folder" data-admin="servicos"><b>Serviços</b><span>Catálogo de serviços e valores</span></button>
      <button class="folder" data-admin="funcionarios"><b>Funcionários / Técnicos</b><span>Equipe, função e situação</span></button>
      <button class="folder" data-admin="fornecedores"><b>Fornecedores</b><span>Contato e histórico de fornecimento</span></button>
    </div>
    <div id="adminPanel" class="section"><h3>Escolha uma pasta</h3><p class="muted">Use os atalhos acima para abrir o cadastro desejado.</p></div>`;
   const reports=document.createElement('section');reports.id='reports';reports.className='view';reports.innerHTML=`
    <h2>Central de Relatórios</h2><div class="section"><div class="grid4">
      <label>Área<select id="reportArea"><option value="os">Ordens de Serviço</option><option value="clientes">Clientes</option><option value="equipamentos">Equipamentos</option><option value="estoque">Estoque</option><option value="movimentos">Movimentações de estoque</option><option value="servicos">Serviços</option><option value="funcionarios">Funcionários / Técnicos</option><option value="fornecedores">Fornecedores</option></select></label>
      <label>Data inicial<input id="reportFrom" type="date"></label><label>Data final<input id="reportTo" type="date"></label><label>Busca livre<input id="reportQuery" placeholder="cliente, peça, técnico, defeito..."></label>
    </div><div class="toolbar"><button id="runReport" class="primary">Gerar relatório</button><button id="printReport">Imprimir</button><button id="exportReport">Exportar CSV</button></div></div>
    <div id="reportSummary" class="cards"></div><div id="reportResult" class="tablewrap"><table><tbody><tr><td class="muted">Escolha os filtros e clique em Gerar relatório.</td></tr></tbody></table></div>`;
   main.insertBefore(admin,document.getElementById('settings'));main.insertBefore(reports,document.getElementById('settings'));
   const dlg=document.createElement('dialog');dlg.id='simpleAdminDlg';dlg.className='modal';dlg.innerHTML='<form id="simpleAdminForm"><div class="dhead"><b id="simpleAdminTitle">Cadastro</b><button type="button" id="simpleAdminClose">✕</button></div><div class="dbody" id="simpleAdminBody"></div><div class="dfoot"><button type="button" id="simpleAdminCancel">Cancelar</button><button class="primary" type="submit">Salvar</button></div></form>';document.body.appendChild(dlg);
   const st=document.createElement('style');st.textContent=`
    .globalSearch{position:relative;flex:1;max-width:520px}.globalSearch input{margin:0;background:#fff}.globalResults{position:absolute;top:42px;left:0;right:0;max-height:60vh;overflow:auto;background:#fff;color:#17202a;border:1px solid #dce2e8;border-radius:10px;box-shadow:0 15px 40px #0003;z-index:100}.gitem{padding:9px 10px;border-bottom:1px solid #edf0f2;cursor:pointer}.gitem:hover{background:#f8fafb}.folderGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:12px 0}.folder{background:#fff;border:1px solid #dce2e8;padding:18px;text-align:left;white-space:normal}.folder b{display:block;font-size:16px;margin-bottom:4px}.folder span{font-size:12px;color:#65727f}.reportCards{grid-template-columns:repeat(4,1fr)}@media(max-width:800px){.folderGrid{grid-template-columns:1fr 1fr}.globalSearch{order:3;max-width:none;width:100%}header{flex-wrap:wrap}}`;
   document.head.appendChild(st);
 }
 addShell();
 let adminType='',editId='',lastReport={headers:[],rows:[]};
 function esc2(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function renderAdmin(type){ensureAdminData();adminType=type;const p=document.getElementById('adminPanel');
   if(type==='clientes'){p.innerHTML='<h3>Clientes</h3><div class="toolbar"><button class="primary" onclick="openClient(\'\')">+ Novo cliente</button><button onclick="showView(\'clients\')">Abrir lista completa</button></div><p class="muted">Clientes continuam com seus equipamentos e histórico de OS vinculados.</p>';return}
   if(type==='equipamentos'){p.innerHTML='<h3>Equipamentos</h3><div class="toolbar"><button class="primary" onclick="openEquip(\'\',\'\')">+ Novo equipamento</button><button onclick="showView(\'clients\')">Localizar por cliente</button></div><p class="muted">O equipamento é localizado por cliente, marca, modelo, série, patrimônio e observações através da Busca Global.</p>';return}
   if(type==='produtos'){p.innerHTML='<h3>Peças / Produtos</h3><div class="toolbar"><button class="primary" onclick="openProduct(\'\')">+ Novo produto</button><button onclick="showView(\'stock\')">Abrir estoque</button></div><p class="muted">Código JF, fabricante, GTIN, descrição, categoria, localização e estoque ficam pesquisáveis.</p>';return}
   const isSrv=type==='servicos', arr=isSrv?(S.servicos_catalogo||[]):S.custom[type]||[];
   const label=isSrv?'Serviços':type==='funcionarios'?'Funcionários / Técnicos':'Fornecedores';
   p.innerHTML=`<div class="toolbar"><h3 style="margin:0">${label}</h3><button class="primary" id="adminNew">+ Novo</button></div><div class="tablewrap"><table><thead><tr>${isSrv?'<th>Serviço</th><th>Valor</th><th>Ativo</th>':type==='funcionarios'?'<th>Nome</th><th>Função</th><th>Telefone</th><th>Situação</th>':'<th>Fornecedor</th><th>Documento</th><th>Telefone</th><th>Cidade</th>'}<th></th></tr></thead><tbody>${arr.map(x=>isSrv?`<tr><td><b>${esc2(x.descricao)}</b></td><td>${money(x.valor)}</td><td>${x.ativo===false?'Inativo':'Ativo'}</td><td><button data-edit="${esc2(x.id)}">Editar</button></td></tr>`:type==='funcionarios'?`<tr><td><b>${esc2(x.nome)}</b></td><td>${esc2(x.funcao||'')}</td><td>${esc2(x.telefone||'')}</td><td>${x.ativo===false?'Inativo':'Ativo'}</td><td><button data-edit="${esc2(x.id)}">Editar</button></td></tr>`:`<tr><td><b>${esc2(x.nome)}</b></td><td>${esc2(x.documento||'')}</td><td>${esc2(x.telefone||'')}</td><td>${esc2(x.cidade||'')}</td><td><button data-edit="${esc2(x.id)}">Editar</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">Nenhum registro.</td></tr>'}</tbody></table></div>`;
   document.getElementById('adminNew').onclick=()=>openAdminEditor(type,'');p.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openAdminEditor(type,b.dataset.edit));
 }
 function openAdminEditor(type,id){ensureAdminData();adminType=type;editId=id;const isSrv=type==='servicos';const arr=isSrv?S.servicos_catalogo:S.custom[type];const x=id?arr.find(a=>String(a.id)===String(id)):null;simpleAdminTitle.textContent=(x?'Editar ':'Novo ')+(isSrv?'serviço':type==='funcionarios'?'funcionário/técnico':'fornecedor');
   simpleAdminBody.innerHTML=isSrv?`<label>Descrição<input id="aeName" value="${esc2(x?.descricao||'')}" required></label><div class="grid2"><label>Valor<input id="aeValue" type="number" step=".01" value="${num(x?.valor)}"></label><label>Situação<select id="aeActive"><option value="1" ${x?.ativo===false?'':'selected'}>Ativo</option><option value="0" ${x?.ativo===false?'selected':''}>Inativo</option></select></label></div><label>Categoria<input id="aeCategory" value="${esc2(x?.categoria||'')}"></label><label>Palavras-chave<input id="aeKeywords" value="${esc2(x?.palavras_chave||'')}"></label>`:type==='funcionarios'?`<label>Nome<input id="aeName" value="${esc2(x?.nome||'')}" required></label><div class="grid2"><label>Função<input id="aeRole" value="${esc2(x?.funcao||'')}"></label><label>Telefone<input id="aePhone" value="${esc2(x?.telefone||'')}"></label><label>E-mail<input id="aeEmail" value="${esc2(x?.email||'')}"></label><label>Situação<select id="aeActive"><option value="1" ${x?.ativo===false?'':'selected'}>Ativo</option><option value="0" ${x?.ativo===false?'selected':''}>Inativo</option></select></label></div><label>Observações<textarea id="aeObs">${esc2(x?.observacoes||'')}</textarea></label>`:`<label>Nome / Razão social<input id="aeName" value="${esc2(x?.nome||'')}" required></label><div class="grid2"><label>CNPJ / CPF<input id="aeDoc" value="${esc2(x?.documento||'')}"></label><label>Telefone<input id="aePhone" value="${esc2(x?.telefone||'')}"></label><label>E-mail<input id="aeEmail" value="${esc2(x?.email||'')}"></label><label>Cidade<input id="aeCity" value="${esc2(x?.cidade||'')}"></label><label>Contato<input id="aeContact" value="${esc2(x?.contato||'')}"></label><label>Ativo<select id="aeActive"><option value="1" ${x?.ativo===false?'':'selected'}>Sim</option><option value="0" ${x?.ativo===false?'selected':''}>Não</option></select></label></div><label>Observações<textarea id="aeObs">${esc2(x?.observacoes||'')}</textarea></label>`;simpleAdminDlg.showModal();
 }
 function searchGlobal(q){q=q.trim().toLowerCase();const box=document.getElementById('globalResults');if(q.length<2){box.classList.add('hidden');return}const r=[];const add=(type,title,sub,go)=>r.push({type,title,sub,go});
   for(const o of orders())if([o.numero_os,clientName(o.cliente_id),o.defeito_reclamado,o.defeito_constatado,o.descricao_servico,o.laudo].join(' ').toLowerCase().includes(q))add('OS','OS '+(o.numero_os||o.id),clientName(o.cliente_id)+' · '+(o.defeito_reclamado||''),()=>openOS(o.id));
   for(const c of clients())if([c.nome,c.documento,c.cpf_cnpj,c.cidade,c.fazenda,c.telefone].join(' ').toLowerCase().includes(q))add('Cliente',c.nome,c.cidade||'',()=>openClient(c.id));
   for(const e of equips())if([equipName(e.id),e.marca,e.modelo,e.numero_serie,e.serie,e.patrimonio,clientName(equipClient(e))].join(' ').toLowerCase().includes(q))add('Equipamento',equipName(e.id),clientName(equipClient(e))+' · '+(e.numero_serie||''),()=>openEquip(e.id));
   for(const p of activeProducts())if([productCode(p),productMakerCode(p),p.codigo_barras,p.descricao,p.categoria,p.localizacao,p.fornecedor].join(' ').toLowerCase().includes(q))add('Produto',productCode(p)+' · '+p.descricao,'Saldo '+num(p.estoque_atual)+' · '+(p.localizacao||''),()=>openProduct(p.id));
   for(const s of S.servicos_catalogo||[])if([s.descricao,s.categoria,s.palavras_chave].join(' ').toLowerCase().includes(q))add('Serviço',s.descricao,money(s.valor),()=>{showView('admin');renderAdmin('servicos')});
   ensureAdminData();for(const f of S.custom.funcionarios)if([f.nome,f.funcao,f.telefone].join(' ').toLowerCase().includes(q))add('Funcionário',f.nome,f.funcao||'',()=>{showView('admin');renderAdmin('funcionarios')});for(const f of S.custom.fornecedores)if([f.nome,f.documento,f.telefone,f.cidade].join(' ').toLowerCase().includes(q))add('Fornecedor',f.nome,f.cidade||'',()=>{showView('admin');renderAdmin('fornecedores')});
   box.innerHTML=r.slice(0,30).map((x,i)=>`<div class="gitem" data-i="${i}"><b>${esc2(x.type)} · ${esc2(x.title)}</b><div class="small muted">${esc2(x.sub)}</div></div>`).join('')||'<div class="gitem muted">Nenhum resultado.</div>';box.classList.remove('hidden');box.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>{box.classList.add('hidden');document.getElementById('globalSearch').value='';r[Number(el.dataset.i)].go()});
 }
 function buildReport(){ensureAdminData();const area=reportArea.value,q=reportQuery.value.trim().toLowerCase(),from=reportFrom.value,to=reportTo.value;let h=[],rows=[];const inDate=d=>(!from||String(d||'').slice(0,10)>=from)&&(!to||String(d||'').slice(0,10)<=to);const match=a=>!q||a.join(' ').toLowerCase().includes(q);
   if(area==='os'){h=['OS','Entrada','Cliente','Situação','Técnico','Defeito','Total'];for(const o of orders())if(inDate(o.entrada||o.data_entrada)&&match([o.numero_os,clientName(o.cliente_id),situation(o),o.tecnico,o.defeito_reclamado,o.defeito_constatado]))rows.push([o.numero_os||o.id,(o.entrada||o.data_entrada||'').slice(0,10),clientName(o.cliente_id),situation(o),o.tecnico||'',o.defeito_reclamado||'',num(o.total)]);}
   if(area==='clientes'){h=['Código','Cliente','Documento','Cidade','Telefone','OS'];for(const c of clients())if(match([c.matricula,c.nome,c.documento,c.cpf_cnpj,c.cidade,c.telefone]))rows.push([c.matricula||c.codigo_cti||c.id,c.nome,c.documento||c.cpf_cnpj||'',c.cidade||'',c.telefone||'',orders().filter(o=>String(o.cliente_id)===String(c.id)).length]);}
   if(area==='equipamentos'){h=['Cliente','Equipamento','Marca','Série','Ano','Horímetro'];for(const e of equips())if(match([clientName(equipClient(e)),equipName(e.id),e.marca,e.numero_serie,e.ano,e.horimetro]))rows.push([clientName(equipClient(e)),equipName(e.id),e.marca||'',e.numero_serie||'',e.ano||'',e.horimetro||'']);}
   if(area==='estoque'){h=['Código','Produto','Saldo','Mínimo','Custo','Venda','Categoria','Local'];for(const p of activeProducts())if(match([productCode(p),p.descricao,p.categoria,p.localizacao,p.fornecedor]))rows.push([productCode(p),p.descricao,num(p.estoque_atual),num(p.estoque_minimo),num(p.valor_custo),num(p.valor_venda),p.categoria||'',p.localizacao||'']);}
   if(area==='movimentos'){h=['Data','Produto','OS','Origem','Quantidade'];for(const m of S.custom.stockMoves||[])if(inDate(m.at)&&match([prodBy(m.produto_id)?.descricao,m.os_id,m.origem]))rows.push([(m.at||'').slice(0,10),prodBy(m.produto_id)?.descricao||m.produto_id,m.os_id||'',m.origem||'',num(m.delta)]);}
   if(area==='servicos'){h=['Serviço','Categoria','Valor','Ativo'];for(const s of S.servicos_catalogo||[])if(match([s.descricao,s.categoria,s.palavras_chave]))rows.push([s.descricao,s.categoria||'',num(s.valor),s.ativo===false?'Não':'Sim']);}
   if(area==='funcionarios'){h=['Nome','Função','Telefone','E-mail','Ativo'];for(const f of S.custom.funcionarios)if(match([f.nome,f.funcao,f.telefone,f.email]))rows.push([f.nome,f.funcao||'',f.telefone||'',f.email||'',f.ativo===false?'Não':'Sim']);}
   if(area==='fornecedores'){h=['Fornecedor','Documento','Telefone','E-mail','Cidade','Contato'];for(const f of S.custom.fornecedores)if(match([f.nome,f.documento,f.telefone,f.email,f.cidade,f.contato]))rows.push([f.nome,f.documento||'',f.telefone||'',f.email||'',f.cidade||'',f.contato||'']);}
   lastReport={headers:h,rows};const total=area==='os'?rows.reduce((a,r)=>a+num(r[6]),0):0;reportSummary.className='cards reportCards';reportSummary.innerHTML=`<div class="card">Registros<b>${rows.length}</b></div>${area==='os'?`<div class="card">Valor total<b style="font-size:18px">${money(total)}</b></div>`:''}${area==='estoque'?`<div class="card">Itens abaixo mínimo<b>${rows.filter(r=>num(r[2])<num(r[3])).length}</b></div>`:''}`;reportResult.innerHTML=`<table><thead><tr>${h.map(x=>'<th>'+esc2(x)+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map((v,i)=>'<td>'+esc2((area==='os'&&i===6)||(area==='estoque'&&(i===4||i===5))?money(v):v)+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="'+h.length+'" class="muted">Nenhum registro encontrado.</td></tr>'}</tbody></table>`;
 }
 function exportCSV(){if(!lastReport.headers.length)buildReport();const all=[lastReport.headers,...lastReport.rows];const csv=all.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='JF-Oficina-relatorio-'+dateOnly()+'.csv';a.click()}
 function printCurrentReport(){if(!lastReport.headers.length)buildReport();const w=open('','_blank');w.document.write('<html><head><title>Relatório JF Oficina</title><style>body{font:12px Arial;margin:25px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:5px;text-align:left}h1{font-size:18px}</style></head><body><h1>JF Oficina — Relatório</h1>'+reportResult.innerHTML+'<script>print()<\/script></body></html>');w.document.close()}
 addEventListener('DOMContentLoaded',()=>{ensureAdminData();document.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>renderAdmin(b.dataset.admin));const gs=document.getElementById('globalSearch');gs.oninput=()=>searchGlobal(gs.value);gs.onkeydown=e=>{if(e.key==='Escape')globalResults.classList.add('hidden')};document.addEventListener('click',e=>{if(!e.target.closest('.globalSearch'))globalResults.classList.add('hidden')});simpleAdminClose.onclick=simpleAdminCancel.onclick=()=>simpleAdminDlg.close();simpleAdminForm.onsubmit=async e=>{e.preventDefault();ensureAdminData();const isSrv=adminType==='servicos';const arr=isSrv?S.servicos_catalogo:S.custom[adminType];let x=editId?arr.find(a=>String(a.id)===String(editId)):null;if(!x){x={id:uid(isSrv?'SV':adminType==='funcionarios'?'FN':'FR')};arr.unshift(x)}if(isSrv)Object.assign(x,{descricao:aeName.value.trim(),valor:num(aeValue.value),ativo:aeActive.value==='1',categoria:aeCategory.value.trim(),palavras_chave:aeKeywords.value.trim()});else if(adminType==='funcionarios')Object.assign(x,{nome:aeName.value.trim(),funcao:aeRole.value.trim(),telefone:aePhone.value.trim(),email:aeEmail.value.trim(),ativo:aeActive.value==='1',observacoes:aeObs.value.trim()});else Object.assign(x,{nome:aeName.value.trim(),documento:aeDoc.value.trim(),telefone:aePhone.value.trim(),email:aeEmail.value.trim(),cidade:aeCity.value.trim(),contato:aeContact.value.trim(),ativo:aeActive.value==='1',observacoes:aeObs.value.trim()});await saveDB();simpleAdminDlg.close();renderAdmin(adminType);render()};runReport.onclick=buildReport;exportReport.onclick=exportCSV;printReport.onclick=printCurrentReport;});
})();
