// JF Oficina v0.15.10 — carregador modular síncrono
document.write([
  '<script src="core.js?v=0.15.10"><\/script>',
  '<script src="os.js?v=0.15.10"><\/script>',
  '<script src="clients.js?v=0.15.10"><\/script>',
  '<script src="products.js?v=0.15.10"><\/script>',
  '<script src="updater-tech.js?v=0.15.10"><\/script>',
  '<script src="library.js?v=0.15.10"><\/script>',
  '<script src="service-intelligence.js?v=0.15.10"><\/script>',
  '<script src="recovery.js?v=0.15.10"><\/script>',
  '<script src="sync.js?v=0.15.10"><\/script>',
  '<script src="sync-numbering.js?v=0.15.10"><\/script>',
  '<script src="sync-integrity.js?v=0.15.10"><\/script>',
  '<script src="admin.js?v=0.15.10"><\/script>',
  '<script src="management.js?v=0.15.10"><\/script>',
  '<script src="search-pro.js?v=0.15.10"><\/script>',
  '<script src="budgets.js?v=0.15.10"><\/script>',
  '<script src="shared-doc.js?v=0.15.10"><\/script>',
  '<script src="shared-doc-fix.js?v=0.15.10"><\/script>',
  '<script src="search-fields.js?v=0.15.10"><\/script>',
  '<script src="release.js?v=0.15.10"><\/script>',
  '<script src="init.js?v=0.15.10"><\/script>',
  '<script src="qr-materials.js?v=0.15.10"><\/script>',
  '<script src="materials-compact.js?v=0.15.10"><\/script>',
  '<script src="services-compact.js?v=0.15.10"><\/script>',
  '<script src="ui-cleanup.js?v=0.15.10"><\/script>',
  '<script src="labels.js?v=0.15.10"><\/script>'
].join(''));
