// JF Oficina v0.14.0 — Orçamentos independentes da OS, sem movimentação de estoque ou financeira
(function(){
 const V='0.14.0';
 function ensure(){S.custom=S.custom||{};if(!Array.isArray(S.custom.orcamentos))S.custom.orcamentos=[];}
 function arr(){ensure();return S.custom.orcamentos}
 function nextNo(){const a=arr().map(x=>Number(x.numero_orcamento)).filter(Number.isFinite);return String((a.length?Math.max(...a):0)+1)}
 function byId(id){return arr().find(x=>String(x.id)===String(id))}
 function blank(){return {id:'',numero_orcamento:'',cliente_id:'',situacao:'Em elaboração',solicitante:'',entrada:nowLocal(),validade:15,local:'',tecnico:'JEFERSON',horimetro:'',controle:'',defeito_reclamado:'',defeito_constatado:'',descricao_servico:'',laudo:'',recomendacao:'',observacoes_internas:'',servicos:[],outros:[],materiais:[],equipamentos:[],desconto:0,acrescimo:0,frete:0,total:0,criado_em:new Date().toISOString(),atualizado_em:new Date().toISOString()}}
 let w=null;
 function addShell(){
   if(document.getElementById('budgets'))return;
   const nav=document.querySelector('nav'),main=document.querySelector('main');if(!nav||!main)return;
   const b=document.createElement('button');b.dataset.view='budgets';b.textContent='Orçamentos';const osb=nav.querySelector('[data-view="os"]');nav.insertBefore(b,osb?.nextSibling||null);
   const sec=document.createElement('section');sec.id='budgets';sec.className='view';sec.innerHTML=`<h2>Orçamentos</h2><div class="toolbar"><button class="primary" id="newBudget">+ Novo orçamento</button><input id="budgetSearch" placeholder="Buscar número, cliente, equipamento, defeito, peça, serviço..."><select id="budgetStatus"><option value="">Todas as situações</option><option>Em elaboração</option><option>Enviado</option><option>Aprovado</option><option>Recusado</option><option>Expirado</option><option>Cancelado</option></select></div><p class="small muted">Orçamento é apenas proposta comercial/técnica. Não movimenta estoque, não gera contas e não altera financeiro.</p><div class="tablewrap"><table><thead><tr><th>Orçamento</th><th>Data</th><th>Cliente / equipamento</th><th>Situação</th><th>Validade</th><th>Total</th></tr></thead><tbody id="budgetTable"></tbody></table></div>`;
   main.insertBefore(sec,document.getElementById('settings'));
   const d=document.createElement('dialog');d.id='budgetDlg';d.className='osmodal';d.innerHTML=`<form id="budgetForm"><div class="dhead"><div><b id="budgetTitle">Novo orçamento</b><div id="budgetSub" class="small"></div></div><button type="button" id="closeBudget">✕</button></div><div class="tabs budgetTabs"><button type="button" class="tab active" data-btab="general">Geral</button><button type="button" class="tab" data-btab="services">Serviços</button><button type="button" class="tab" data-btab="others">Desloc./Outros</button><button type="button" class="tab" data-btab="materials">Materiais</button><button type="button" class="tab" data-btab="equipments">Equipamentos</button><button type="button" class="tab" data-btab="values">Valores</button></div><div class="dbody">
   <div class="btab on" id="btab-general"><div class="section"><h3>Atendimento</h3><div class="grid3"><label>Cliente<select id="bClient" required></select></label><label>Situação<select id="bSituation"><option>Em elaboração</option><option>Enviado</option><option>Aprovado</option><option>Recusado</option><option>Expirado</option><option>Cancelado</option></select></label><label>Solicitante<input id="bRequester"></label><label>Data<input id="bEntry" type="datetime-local"></label><label>Validade (dias)<input id="bValidity" type="number" min="1" value="15"></label><label>Local / Fazenda<input id="bLocation"></label><label>Técnico<input id="bTechnician"></label><label>Horímetro<input id="bHourmeter"></label><label>Nº controle<input id="bControl"></label></div></div><div class="section"><h3>Diagnóstico / escopo</h3><label>Defeito reclamado<textarea id="bComplaint" rows="3"></textarea></label><label>Defeito constatado<textarea id="bFinding" rows="4"></textarea></label><label>Descrição do serviço proposto<textarea id="bServiceDesc" rows="5"></textarea></label><label>Laudo / justificativa técnica<textarea id="bReport" rows="6"></textarea></label><label>Recomendação<textarea id="bRecommendation" rows="3"></textarea></label><label>Observações internas <span class="small muted">(não sai no orçamento do cliente)</span><textarea id="bInternal" rows="3"></textarea></label></div></div>
   <div class="btab" id="btab-services"><div class="section"><h3>Serviços propostos</h3><div id="bServices"></div><button type="button" id="bAddService">+ Adicionar serviço</button></div></div>
   <div class="btab" id="btab-others"><div class="section"><h3>Deslocamentos e outros</h3><div id="bOthers"></div><button type="button" id="bAddOther">+ Adicionar deslocamento/outro</button></div></div>
   <div class="btab" id="btab-materials"><div class="section"><h3>Materiais previstos</h3><p class="small muted">Itens aqui não reservam nem dão baixa no estoque.</p><div id="bMaterials"></div><button type="button" id="bAddMaterial">+ Adicionar material</button></div></div>
   <div class="btab" id="btab-equipments"><div class="section"><h3>Equipamentos</h3><div id="bEquipments"></div><button type="button" id="bAddEquipment">+ Vincular equipamento</button></div></div>
   <div class="btab" id="btab-values"><div class="grid2"><div class="section"><h3>Totais do orçamento</h3><div id="bTotals"></div></div><div class="section"><h3>Ajustes comerciais</h3><div class="grid2"><label>Desconto geral<input id="bDiscount" type="number" step=".01" value="0"></label><label>Acréscimo geral<input id="bAdd" type="number" step=".01" value="0"></label><label>Frete<input id="bFreight" type="number" step=".01" value="0"></label></div><p class="small muted">Estes valores pertencem somente ao orçamento. Não geram lançamento financeiro.</p></div></div></div>
   </div><div class="dfoot"><div class="stickybar"><button type="button" id="printBudget">Imprimir / PDF</button><span class="statusnote">Sem movimentação de estoque/financeiro</span></div><div class="right"></div><button type="button" id="cancelBudget">Fechar</button><button type="button" id="convertBudget">Converter em OS</button><button type="submit" class="primary">Salvar orçamento</button></div></form>`;document.body.appendChild(d);
   const st=document.createElement('style');st.textContent='.btab{display:none}.btab.on{display:block}.budgetWarn{background:#fff4d8;padding:8px 10px;border-radius:9px}.budgetRows .itemrow{margin-bottom:4px}';document.head.appendChild(st);
 }
 function optsClients(sel=''){return '<option value="">Selecione...</option>'+clients().map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(sel)?'selected':''}>${esc(c.nome)}</option>`).join('')}
 function optsSrv(sel=''){return '<option value="">Selecione...</option>'+(S.servicos_catalogo||[]).filter(x=>x.ativo!==false).map(s=>`<option value="${esc(s.id)}" ${String(s.id)===String(sel)?'selected':''}>${esc(s.descricao)}</option>`).join('')}
 function optsProd(sel=''){return '<option value="">Selecione...</option>'+activeProducts().map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(sel)?'selected':''}>[${esc(productCode(p))}] ${esc(p.descricao||'')}</option>`).join('')}
 function optsEq(client,sel=''){return '<option value="">Selecione...</option>'+equips().filter(e=>String(equipClient(e))===String(client)).map(e=>`<option value="${esc(e.id)}" ${String(e.id)===String(sel)?'selected':''}>${esc(equipName(e.id))} ${esc(e.numero_serie||e.serie||'')}</option>`).join('')}
 function line(r){return Math.max(0,num(r.quantidade||1)*num(r.valor)-num(r.desconto)+num(r.acrescimo))}
 function totals(){const s=w.servicos.reduce((a,x)=>a+line(x),0),o=w.outros.reduce((a,x)=>a+line(x),0),m=w.materiais.reduce((a,x)=>a+line(x),0),total=Math.max(0,s+o+m+num(bFreight.value)+num(bAdd.value)-num(bDiscount.value));return {s,o,m,total}}
 function renderRows(){
   bServices.innerHTML=w.servicos.map((r,i)=>`<div class="itemrow" data-i="${i}"><label>Serviço<select class="bsSel">${optsSrv(r.servico_id)}</select></label><label>Qtd/Horas<input class="bsQty" type="number" step=".25" value="${num(r.quantidade)||1}"></label><label>Valor<input class="bsVal" type="number" step=".01" value="${num(r.valor)}"></label><label>Desconto<input class="bsDisc" type="number" step=".01" value="${num(r.desconto)}"></label><label>Acréscimo<input class="bsAcc" type="number" step=".01" value="${num(r.acrescimo)}"></label><label>Técnico<input class="bsTech" value="${esc(r.tecnico||w.tecnico)}"></label><button type="button" class="danger bsDel">✕</button></div>`).join('');
   bOthers.innerHTML=w.outros.map((r,i)=>`<div class="itemrow other"><label>Descrição<input class="boName" value="${esc(r.nome||'')}"></label><label>Qtd/Km<input class="boQty" type="number" step=".01" value="${num(r.quantidade)||1}"></label><label>Valor un.<input class="boVal" type="number" step=".01" value="${num(r.valor)}"></label><label>Origem<input class="boFrom" value="${esc(r.origem||'')}"></label><label>Destino<input class="boTo" value="${esc(r.destino||'')}"></label><button type="button" class="danger boDel">✕</button></div>`).join('');
   bMaterials.innerHTML=w.materiais.map((r,i)=>`<div class="itemrow"><label>Produto / Código<select class="bmSel">${optsProd(r.produto_id)}</select></label><label>Qtd<input class="bmQty" type="number" step=".01" value="${num(r.quantidade)||1}"></label><label>Valor<input class="bmVal" type="number" step=".01" value="${num(r.valor)}"></label><label>Desconto<input class="bmDisc" type="number" step=".01" value="${num(r.desconto)}"></label><label>Acréscimo<input class="bmAcc" type="number" step=".01" value="${num(r.acrescimo)}"></label><label><span class="small muted">Sem baixa</span></label><button type="button" class="danger bmDel">✕</button></div>`).join('');
   bEquipments.innerHTML=w.equipamentos.map((r,i)=>`<div class="itemrow eq"><label>Equipamento<select class="beSel">${optsEq(w.cliente_id,r.equipamento_id)}</select></label><label>Horímetro<input class="beHour" value="${esc(r.horimetro||'')}"></label><label><input class="beMain" type="radio" name="bMain" ${r.principal?'checked':''}> Principal</label><button type="button" class="danger beDel">✕</button></div>`).join('');
   bind('.bsQty','quantidade',w.servicos,true);bind('.bsVal','valor',w.servicos,true);bind('.bsDisc','desconto',w.servicos,true);bind('.bsAcc','acrescimo',w.servicos,true);bind('.bsTech','tecnico',w.servicos,false);bind('.boName','nome',w.outros,false);bind('.boQty','quantidade',w.outros,true);bind('.boVal','valor',w.outros,true);bind('.boFrom','origem',w.outros,false);bind('.boTo','destino',w.outros,false);bind('.bmQty','quantidade',w.materiais,true);bind('.bmVal','valor',w.materiais,true);bind('.bmDisc','desconto',w.materiais,true);bind('.bmAcc','acrescimo',w.materiais,true);bind('.beHour','horimetro',w.equipamentos,false);
   $$('.bsSel').forEach((e,i)=>e.onchange=()=>{let s=serviceBy(e.value);w.servicos[i].servico_id=e.value;w.servicos[i].descricao=s?.descricao||'';if(!w.servicos[i].valor)w.servicos[i].valor=num(s?.valor);renderRows()});
   $$('.bmSel').forEach((e,i)=>e.onchange=()=>{let p=prodBy(e.value);w.materiais[i].produto_id=e.value;if(!w.materiais[i].valor)w.materiais[i].valor=num(p?.valor_venda);renderRows()});
   $$('.beSel').forEach((e,i)=>e.onchange=()=>{w.equipamentos[i].equipamento_id=e.value});$$('.beMain').forEach((e,i)=>e.onchange=()=>{w.equipamentos.forEach((x,j)=>x.principal=j===i);renderRows()});
   $$('.bsDel').forEach((e,i)=>e.onclick=()=>{w.servicos.splice(i,1);renderRows()});$$('.boDel').forEach((e,i)=>e.onclick=()=>{w.outros.splice(i,1);renderRows()});$$('.bmDel').forEach((e,i)=>e.onclick=()=>{w.materiais.splice(i,1);renderRows()});$$('.beDel').forEach((e,i)=>e.onclick=()=>{w.equipamentos.splice(i,1);renderRows()});renderTotals();
 }
 function bind(sel,key,a,numeric){$$(sel).forEach((e,i)=>e.oninput=()=>{a[i][key]=numeric?num(e.value):e.value;renderTotals()})}
 function renderTotals(){const t=totals();bTotals.innerHTML=`<div class="sumline"><span>Serviços</span><b>${money(t.s)}</b></div><div class="sumline"><span>Desloc./Outros</span><b>${money(t.o)}</b></div><div class="sumline"><span>Materiais</span><b>${money(t.m)}</b></div><div class="sumline"><span>Frete</span><b>${money(bFreight.value)}</b></div><div class="sumline"><span>Acréscimos</span><b>${money(bAdd.value)}</b></div><div class="sumline"><span>Descontos</span><b>-${money(bDiscount.value)}</b></div><div class="sumline total"><span>TOTAL DO ORÇAMENTO</span><b>${money(t.total)}</b></div><p class="small muted">Valor informativo. Não é lançamento financeiro.</p>`}
 function read(){w.cliente_id=bClient.value;w.situacao=bSituation.value;w.solicitante=bRequester.value;w.entrada=bEntry.value;w.validade=num(bValidity.value)||15;w.local=bLocation.value;w.tecnico=bTechnician.value;w.horimetro=bHourmeter.value;w.controle=bControl.value;w.defeito_reclamado=bComplaint.value;w.defeito_constatado=bFinding.value;w.descricao_servico=bServiceDesc.value;w.laudo=bReport.value;w.recomendacao=bRecommendation.value;w.observacoes_internas=bInternal.value;w.desconto=num(bDiscount.value);w.acrescimo=num(bAdd.value);w.frete=num(bFreight.value);w.total=totals().total;w.atualizado_em=new Date().toISOString()}
 function open(id=''){ensure();w=id?deep(byId(id)):blank();bClient.innerHTML=optsClients(w.cliente_id);bClient.value=w.cliente_id;bSituation.value=w.situacao;bRequester.value=w.solicitante;bEntry.value=w.entrada||nowLocal();bValidity.value=w.validade||15;bLocation.value=w.local;bTechnician.value=w.tecnico||'JEFERSON';bHourmeter.value=w.horimetro;bControl.value=w.controle;bComplaint.value=w.defeito_reclamado;bFinding.value=w.defeito_constatado;bServiceDesc.value=w.descricao_servico;bReport.value=w.laudo;bRecommendation.value=w.recomendacao;bInternal.value=w.observacoes_internas;bDiscount.value=w.desconto||0;bAdd.value=w.acrescimo||0;bFreight.value=w.frete||0;budgetTitle.textContent=id?`Orçamento ${w.numero_orcamento}`:'Novo orçamento';budgetSub.textContent=id?`${clientName(w.cliente_id)} · ${w.situacao}`:'Proposta sem movimentação de estoque/financeiro';setTab('general');renderRows();budgetDlg.showModal()}
 function setTab(n){$$('[data-btab]').forEach(x=>x.classList.toggle('active',x.dataset.btab===n));$$('.btab').forEach(x=>x.classList.toggle('on',x.id==='btab-'+n))}
 function searchable(o){const eq=(o.equipamentos||[]).map(x=>equipName(x.equipamento_id));const mats=(o.materiais||[]).map(x=>{const p=prodBy(x.produto_id);return [productCode(p),p?.descricao,p?.codigo_fabricante].join(' ')});const srv=(o.servicos||[]).map(x=>x.descricao||serviceBy(x.servico_id)?.descricao||'');return [o.numero_orcamento,clientName(o.cliente_id),o.situacao,o.tecnico,o.defeito_reclamado,o.defeito_constatado,o.descricao_servico,o.laudo,...eq,...mats,...srv].join(' ').toLowerCase()}
 function renderList(){if(!document.getElementById('budgetTable'))return;ensure();let q=(budgetSearch.value||'').toLowerCase(),st=budgetStatus.value;budgetTable.innerHTML=arr().filter(o=>(!st||o.situacao===st)&&searchable(o).includes(q)).sort((a,b)=>num(b.numero_orcamento)-num(a.numero_orcamento)).map(o=>{const eq=(o.equipamentos||[]).map(x=>equipName(x.equipamento_id)).filter(Boolean).join(', ');let exp='';if(o.entrada&&o.validade){const d=new Date(o.entrada);d.setDate(d.getDate()+num(o.validade));exp=d.toLocaleDateString('pt-BR')}return `<tr class="click" data-bid="${esc(o.id)}"><td><b>${esc(o.numero_orcamento)}</b></td><td>${esc(String(o.entrada||'').slice(0,10))}</td><td><b>${esc(clientName(o.cliente_id))}</b><br><span class="muted">${esc(eq)}</span></td><td><span class="badge">${esc(o.situacao)}</span></td><td>${esc(exp)}</td><td>${money(o.total)}</td></tr>`}).join('')||'<tr><td colspan="6" class="muted">Nenhum orçamento.</td></tr>';budgetTable.querySelectorAll('[data-bid]').forEach(tr=>tr.onclick=()=>open(tr.dataset.bid))}
 async function save(){read();if(!w.cliente_id){alert('Selecione o cliente.');return false}ensure();if(!w.id){w.id=uid('ORC');w.numero_orcamento=nextNo();w.criado_em=new Date().toISOString();arr().push(deep(w))}else{const i=arr().findIndex(x=>String(x.id)===String(w.id));if(i>=0)arr()[i]=deep(w);else arr().push(deep(w))}await saveDB();renderList();if(typeof render==='function')render();return true}
 function printOne(){read();const c=clientBy(w.cliente_id),eq=(w.equipamentos||[]).map(x=>equipName(x.equipamento_id)).filter(Boolean).join(', '),t=totals();const mat=w.materiais.map(x=>{let p=prodBy(x.produto_id);return `<tr><td>${esc(productCode(p))}</td><td>${esc(p?.descricao||'')}</td><td>${num(x.quantidade)}</td><td>${money(x.valor)}</td><td>${money(line(x))}</td></tr>`}).join(''),srv=w.servicos.map(x=>`<tr><td colspan="2">${esc(x.descricao||serviceBy(x.servico_id)?.descricao||'')}</td><td>${num(x.quantidade)}</td><td>${money(x.valor)}</td><td>${money(line(x))}</td></tr>`).join('');let html=`<h1>JF Manutenções Agrícolas</h1><h2>Orçamento ${esc(w.numero_orcamento||'(novo)')}</h2><p><b>Cliente:</b> ${esc(c?.nome||'')}<br><b>Equipamento:</b> ${esc(eq)}<br><b>Data:</b> ${esc(String(w.entrada||'').slice(0,10))} · <b>Validade:</b> ${num(w.validade)} dias</p><h3>Escopo técnico</h3><p><b>Defeito reclamado:</b> ${esc(w.defeito_reclamado)}</p><p><b>Defeito constatado:</b> ${esc(w.defeito_constatado)}</p><p>${esc(w.descricao_servico||w.laudo||'')}</p><table border="1" cellspacing="0" cellpadding="6" width="100%"><tr><th>Código</th><th>Descrição</th><th>Qtd.</th><th>Valor</th><th>Total</th></tr>${srv}${mat}</table><h2>Total: ${money(t.total)}</h2><p><small>Este documento é um orçamento. Não representa baixa de estoque, faturamento ou recebimento.</small></p>`;const win=open('','_blank');win.document.write(`<html><head><title>Orçamento ${esc(w.numero_orcamento||'')}</title></head><body style="font-family:Arial;padding:24px">${html}</body></html>`);win.document.close();win.print()}
 async function convert(){read();if(!confirm('Criar uma nova OS com os dados deste orçamento? O orçamento será preservado e a OS terá numeração própria.'))return;await save();const o=blankOS();o.cliente_id=w.cliente_id;o.solicitante=w.solicitante;o.local=w.local;o.tecnico=w.tecnico;o.horimetro=w.horimetro;o.controle='ORÇ '+w.numero_orcamento+(w.controle?' · '+w.controle:'');o.defeito_reclamado=w.defeito_reclamado;o.defeito_constatado=w.defeito_constatado;o.descricao_servico=w.descricao_servico;o.laudo=w.laudo;o.recomendacao=w.recomendacao;o.observacoes_internas='Origem: Orçamento '+w.numero_orcamento+(w.observacoes_internas?'\n'+w.observacoes_internas:'');o.servicos=deep(w.servicos);o.outros=deep(w.outros);o.materiais=deep(w.materiais);o.equipamentos=deep(w.equipamentos);work=o;budgetDlg.close();openOS('');Object.assign(work,o);renderWork();dirty()}
 addShell();ensure();
 document.querySelectorAll('nav [data-view]').forEach(b=>{if(b.dataset.view==='budgets')b.onclick=()=>{showView('budgets');renderList()}});
 document.querySelectorAll('[data-btab]').forEach(b=>b.onclick=()=>setTab(b.dataset.btab));
 newBudget.onclick=()=>open();budgetSearch.oninput=renderList;budgetStatus.onchange=renderList;closeBudget.onclick=cancelBudget.onclick=()=>budgetDlg.close();bAddService.onclick=()=>{w.servicos.push({id:uid('BOS'),servico_id:'',descricao:'',quantidade:1,valor:0,desconto:0,acrescimo:0,tecnico:w.tecnico});renderRows()};bAddOther.onclick=()=>{w.outros.push({id:uid('BO'),nome:'',quantidade:1,valor:0,origem:'',destino:'',desconto:0,acrescimo:0});renderRows()};bAddMaterial.onclick=()=>{w.materiais.push({id:uid('BM'),produto_id:'',quantidade:1,valor:0,desconto:0,acrescimo:0});renderRows()};bAddEquipment.onclick=()=>{if(!bClient.value){alert('Selecione o cliente primeiro.');return}w.cliente_id=bClient.value;w.equipamentos.push({equipamento_id:'',horimetro:'',principal:w.equipamentos.length===0});renderRows()};bClient.onchange=()=>{w.cliente_id=bClient.value;renderRows()};[bDiscount,bAdd,bFreight].forEach(x=>x.oninput=renderTotals);budgetForm.onsubmit=async e=>{e.preventDefault();if(await save()){budgetDlg.close();renderList()}};printBudget.onclick=printOne;convertBudget.onclick=convert;
 window.openBudget=open;window.renderBudgets=renderList;
})();