function openClient(id=''){let c=id?clientBy(id):null;fillClientSelects();clientId.value=c?.id||'';clientTitle.textContent=c?`Cliente — ${c.nome}`:'Novo cliente';clientCode.value=c?(c.matricula||c.codigo_cti||c.id):nextClientCode();clientName.value=c?.nome||'';clientDoc.value=c?.documento||c?.cpf_cnpj||'';clientIE.value=c?.ie||c?.inscricao_estadual||'';clientPhone.value=c?.telefone||c?.fone||'';clientEmail.value=c?.email||'';clientCity.value=c?.cidade||'';clientFarm.value=c?.fazenda||'';clientAddress.value=c?.endereco||c?.logradouro||'';clientBirth.value=c?.data_nascimento||c?.data_abertura||'';clientObs.value=c?.observacoes||'';clientRelations.classList.toggle('hidden',!c);if(c)renderClientRelations(c.id);clientDlg.showModal()}
window.openClient=openClient;
function renderClientRelations(id){let es=equips().filter(e=>String(equipClient(e))===String(id)),os=orders().filter(o=>String(o.cliente_id)===String(id)).sort((a,b)=>num(b.numero_os)-num(a.numero_os));clientEquipTable.innerHTML=es.length?es.map(e=>`<tr class="click" onclick="openEquip('${esc(e.id)}')"><td><b>${esc(equipName(e.id))}</b></td><td>${esc(e.numero_serie||'')}</td></tr>`).join(''):'<tr><td class="muted">Nenhum equipamento.</td></tr>';clientOsTable.innerHTML=os.length?os.slice(0,120).map(o=>`<tr class="click" onclick="clientDlg.close();openOS('${esc(o.id)}')"><td><b>OS ${esc(o.numero_os||o.id)}</b></td><td>${esc(o.data_entrada||'')}</td><td>${badge(situation(o))}</td><td>${esc((o.defeito_reclamado||'').slice(0,80))}</td></tr>`).join(''):'<tr><td class="muted">Nenhuma OS.</td></tr>'}
clientForm.onsubmit=async e=>{e.preventDefault();let c=clientId.value?clientBy(clientId.value):null,created=!c;let fields={matricula:clientCode.value,codigo_cti:clientCode.value,nome:clientName.value,documento:clientDoc.value,cpf_cnpj:clientDoc.value,ie:clientIE.value,inscricao_estadual:clientIE.value,telefone:clientPhone.value,email:clientEmail.value,cidade:clientCity.value,fazenda:clientFarm.value,endereco:clientAddress.value,logradouro:clientAddress.value,data_nascimento:clientBirth.value,observacoes:clientObs.value};if(c)Object.assign(c,fields);else{c={id:uid('C'),...fields};S.custom.clientes.unshift(c)}log('cliente',c.id,created?'Cliente criado':'Cliente alterado');await saveDB();render();clientDlg.close();if(osDlg.open){fillClientSelects();osClient.value=c.id;work.cliente_id=c.id;renderEquipments()}}
closeClient.onclick=clientCancel.onclick=()=>clientDlg.close();clientNewEquip.onclick=()=>openEquip('',clientId.value);quickClient.onclick=()=>openClient('');

function openEquip(id='',client=''){let e=id?equipBy(id):null;fillClientSelects();equipId.value=e?.id||'';equipTitle.textContent=e?`Equipamento — ${equipName(e.id)}`:'Novo equipamento';equipClient.value=e?equipClient(e):client;equipType.value=e?.tipo||'';equipBrand.value=e?.marca||'';equipModel.value=e?.equipamento||e?.modelo||e?.descricao||'';equipSerial.value=e?.numero_serie||e?.serie||'';equipAsset.value=e?.patrimonio||'';equipYear.value=e?.ano||'';equipHour.value=e?.horimetro||'';equipLocation.value=e?.local||'';equipObs.value=e?.observacoes||'';equipDlg.showModal()}
window.openEquip=openEquip;
equipForm.onsubmit=async e=>{e.preventDefault();let x=equipId.value?equipBy(equipId.value):null,was=!!x;if(x)Object.assign(x,{cliente_id:equipClient.value,tipo:equipType.value,marca:equipBrand.value,equipamento:equipModel.value,modelo:equipModel.value,numero_serie:equipSerial.value,patrimonio:equipAsset.value,ano:equipYear.value,horimetro:equipHour.value,local:equipLocation.value,observacoes:equipObs.value});else{x={id:uid('E'),cliente_id:equipClient.value,tipo:equipType.value,marca:equipBrand.value,equipamento:equipModel.value,modelo:equipModel.value,numero_serie:equipSerial.value,patrimonio:equipAsset.value,ano:equipYear.value,horimetro:equipHour.value,local:equipLocation.value,observacoes:equipObs.value};S.custom.equipamentos.unshift(x)}log('equipamento',x.id,was?'Equipamento alterado':'Equipamento criado');await saveDB();render();equipDlg.close();if(clientDlg.open)renderClientRelations(equipClient.value);if(osDlg.open){work.cliente_id=equipClient.value;osClient.value=equipClient.value;work.equipamentos.push({equipamento_id:x.id,principal:work.equipamentos.length===0});renderEquipments();dirty()}}
closeEquip.onclick=equipCancel.onclick=()=>equipDlg.close();

function nextProductCode(){normalize();S.custom.productSeq=Math.max(num(S.custom.productSeq),1746,...S.produtos.map(p=>num(productCode(p))))+1;return String(S.custom.productSeq)}
function renderProductQR(code){
 productQR.innerHTML='';productQRText.textContent='JF-PRODUTO-'+code;
 if(window.QRCode){new QRCode(productQR,{text:'JF-PRODUTO-'+code,width:150,height:150,correctLevel:QRCode.CorrectLevel.M})}
 else productQR.innerHTML='<div class="muted">QR disponível quando a biblioteca carregar.</div>'
}
async function handleProductImage(file){
 if(!file)return;let data=await compressProductImage(file);productImagePreview.src=data;productImagePreview.dataset.value=data;productImagePreview.style.display='block'
}
function compressProductImage(file){return new Promise(ok=>{let im=new Image(),r=new FileReader();r.onload=()=>im.src=r.result;im.onload=()=>{let max=900,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.62))};r.readAsDataURL(file)})}
