// JF Oficina v0.15.3 — seleção de produtos e projetos de impressão de etiquetas
(function(){
 const STORE='jf-label-projects-v1';
 const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 const escx=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const preset={id:'pimaco-6181-carta-20',name:'Pimaco Carta 20 — 6181 / SL61081',pageW:215.9,pageH:279.4,cols:2,rows:10,labelW:101.6,labelH:25.4,marginX:6.35,marginY:12.7,gapX:0,gapY:0};
 let selected=[];
 function loadProjects(){try{const x=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(x)&&x.length?x:[preset]}catch(e){return [preset]}}
 function saveProjects(a){localStorage.setItem(STORE,JSON.stringify(a))}
 function projects(){let a=loadProjects();if(!a.some(x=>x.id===preset.id)){a.unshift(preset);saveProjects(a)}return a}
 function productSearch(code,desc,extra){const a=norm(code),b=norm(desc),c=norm(extra);return activeProducts().filter(p=>{
   const ca=norm([productCode(p),productMakerCode(p),p.codigo_barras,p.codigos_equivalentes].join(' '));
   const cb=norm(p.descricao);const cc=norm([p.marca,p.aplicacao,p.categoria,p.localizacao].join(' '));
   return (!a||ca.includes(a))&&(!b||cb.includes(b))&&(!c||cc.includes(c));
 }).slice(0,80)}
 function ensureDialog(){if(document.getElementById('labelDlg'))return;
   const d=document.createElement('dialog');d.id='labelDlg';d.className='osmodal labelModal';d.innerHTML=`<form method="dialog"><div class="dhead"><div><b>Gerar etiquetas</b><div class="small">Selecione somente os produtos que deseja imprimir.</div></div><button type="button" id="closeLabelDlg">✕</button></div><div class="dbody">
   <div class="section"><h3>1. Localizar produtos</h3><div class="labelSearchGrid"><label>Código<input id="labelFindCode" type="search" placeholder="JF, fabricante ou GTIN"></label><label>Descrição<input id="labelFindDesc" type="search" placeholder="Nome ou descrição"></label><label>Aplicação / marca<input id="labelFindExtra" type="search" placeholder="Marca, aplicação ou categoria"></label></div><div id="labelSearchResults" class="labelResults"></div></div>
   <div class="section"><div class="toolbar"><h3 style="margin:0">2. Etiquetas selecionadas</h3><button type="button" id="clearLabelSelection">Limpar seleção</button></div><div id="labelSelection"></div></div>
   <div class="section"><h3>3. Projeto de impressão</h3><div class="grid3"><label>Projeto<select id="labelProject"></select></label><label>Iniciar na etiqueta nº<input id="labelStart" type="number" min="1" value="1"></label><label>&nbsp;<button type="button" id="saveLabelProject">Salvar projeto / ajustes</button></label></div><p class="small muted">Use “Iniciar na etiqueta nº” para reaproveitar uma folha parcialmente usada.</p><div id="labelProjectFields" class="labelProjectGrid"></div></div>
   </div><div class="dfoot"><button type="button" id="cancelLabelDlg">Fechar</button><button type="button" id="printSelectedLabels" class="primary">Gerar / Imprimir etiquetas</button></div></form>`;document.body.appendChild(d);
   const st=document.createElement('style');st.textContent=`.labelModal{width:min(1120px,96vw)}.labelSearchGrid,.labelProjectGrid{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:9px}.labelResults{margin-top:10px;border:1px solid #dfe5ea;border-radius:9px;max-height:260px;overflow:auto}.labelResult{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:9px 10px;border-bottom:1px solid #edf0f2}.labelResult:last-child{border-bottom:0}.labelChosen{display:grid;grid-template-columns:minmax(260px,1fr) 120px auto;gap:10px;align-items:end;padding:9px 0;border-bottom:1px solid #edf0f2}.labelChosen .qty input{width:100%}.labelProjectGrid{margin-top:10px}.labelProjectGrid label span{display:block;font-size:11px;color:#5f6973;margin-bottom:3px}@media(max-width:800px){.labelSearchGrid,.labelProjectGrid{grid-template-columns:1fr}.labelChosen{grid-template-columns:1fr 100px auto}}`;document.head.appendChild(st);
   bindUI();
 }
 function projectOptions(){const sel=document.getElementById('labelProject');if(!sel)return;const cur=sel.value;sel.innerHTML=projects().map(p=>`<option value="${escx(p.id)}">${escx(p.name)}</option>`).join('')+'<option value="__new">+ Novo projeto personalizado</option>';sel.value=cur&&[...sel.options].some(o=>o.value===cur)?cur:preset.id;renderProjectFields()}
 function currentProject(){const id=document.getElementById('labelProject')?.value;return projects().find(x=>x.id===id)||preset}
 function renderProjectFields(){const box=document.getElementById('labelProjectFields');if(!box)return;let p=currentProject();if(document.getElementById('labelProject')?.value==='__new')p={id:'custom-'+Date.now(),name:'Novo projeto',pageW:215.9,pageH:279.4,cols:2,rows:10,labelW:101.6,labelH:25.4,marginX:6.35,marginY:12.7,gapX:0,gapY:0};box.dataset.pid=p.id;box.innerHTML=`<label><span>Nome do projeto</span><input data-pf="name" value="${escx(p.name)}"></label><label><span>Largura da folha (mm)</span><input data-pf="pageW" type="number" step="0.01" value="${p.pageW}"></label><label><span>Altura da folha (mm)</span><input data-pf="pageH" type="number" step="0.01" value="${p.pageH}"></label><label><span>Colunas</span><input data-pf="cols" type="number" min="1" value="${p.cols}"></label><label><span>Linhas</span><input data-pf="rows" type="number" min="1" value="${p.rows}"></label><label><span>Largura etiqueta (mm)</span><input data-pf="labelW" type="number" step="0.01" value="${p.labelW}"></label><label><span>Altura etiqueta (mm)</span><input data-pf="labelH" type="number" step="0.01" value="${p.labelH}"></label><label><span>Margem lateral (mm)</span><input data-pf="marginX" type="number" step="0.01" value="${p.marginX}"></label><label><span>Margem superior (mm)</span><input data-pf="marginY" type="number" step="0.01" value="${p.marginY}"></label><label><span>Espaço horizontal (mm)</span><input data-pf="gapX" type="number" step="0.01" value="${p.gapX}"></label><label><span>Espaço vertical (mm)</span><input data-pf="gapY" type="number" step="0.01" value="${p.gapY}"></label>`;const cap=Math.max(1,Number(p.cols)*Number(p.rows));const start=document.getElementById('labelStart');start.max=cap;if(Number(start.value)>cap)start.value=1}
 function readProjectFields(){const box=document.getElementById('labelProjectFields'),o={id:box.dataset.pid};box.querySelectorAll('[data-pf]').forEach(i=>{const k=i.dataset.pf;o[k]=k==='name'?i.value.trim():Number(i.value||0)});o.cols=Math.max(1,Math.round(o.cols));o.rows=Math.max(1,Math.round(o.rows));return o}
 function renderSearch(){const box=document.getElementById('labelSearchResults');const code=labelFindCode.value,desc=labelFindDesc.value,extra=labelFindExtra.value;if(![code,desc,extra].some(x=>x.trim())){box.innerHTML='<div class="labelResult muted">Digite em um ou mais campos para localizar produtos.</div>';return}const rows=productSearch(code,desc,extra);box.innerHTML=rows.map(p=>`<div class="labelResult"><div><b>${escx(productCode(p))} · ${escx(p.descricao||'')}</b><div class="small muted">${escx([productMakerCode(p),p.marca,p.aplicacao,p.localizacao,`Saldo ${num(p.estoque_atual)}`].filter(Boolean).join(' · '))}</div></div><button type="button" data-add-label="${escx(p.id)}">Adicionar</button></div>`).join('')||'<div class="labelResult muted">Nenhum produto encontrado.</div>';box.querySelectorAll('[data-add-label]').forEach(b=>b.onclick=()=>{addSelected(b.dataset.addLabel);[labelFindCode,labelFindDesc,labelFindExtra].forEach(x=>x.value='');renderSearch()})}
 function addSelected(id){const p=prodBy(id);if(!p)return;const old=selected.find(x=>String(x.id)===String(id));if(old)old.qty+=1;else selected.push({id:p.id,qty:1});renderSelected()}
 function renderSelected(){const box=document.getElementById('labelSelection');if(!selected.length){box.innerHTML='<p class="muted">Nenhum produto adicionado.</p>';return}box.innerHTML=selected.map((x,i)=>{const p=prodBy(x.id);return `<div class="labelChosen"><div><b>${escx(productCode(p))} · ${escx(p?.descricao||'')}</b><div class="small muted">${escx([productMakerCode(p),p?.marca,p?.localizacao].filter(Boolean).join(' · '))}</div></div><label class="qty">Qtd. etiquetas<input type="number" min="1" max="999" value="${x.qty}" data-label-qty="${i}"></label><button type="button" class="danger" data-label-del="${i}">Remover</button></div>`}).join('');box.querySelectorAll('[data-label-qty]').forEach(i=>i.oninput=()=>selected[Number(i.dataset.labelQty)].qty=Math.max(1,Math.round(Number(i.value)||1)));box.querySelectorAll('[data-label-del]').forEach(b=>b.onclick=()=>{selected.splice(Number(b.dataset.labelDel),1);renderSelected()})}
 function expandedLabels(){const out=[];for(const x of selected){const p=prodBy(x.id);if(!p)continue;for(let i=0;i<Math.max(1,Math.round(x.qty));i++)out.push(p)}return out}
 function printNow(){const p=readProjectFields(),labels=expandedLabels();if(!labels.length){alert('Adicione ao menos um produto para gerar etiquetas.');return}const capacity=p.cols*p.rows,start=Math.min(capacity,Math.max(1,Math.round(Number(labelStart.value)||1)));const slots=[];for(let i=1;i<start;i++)slots.push(null);slots.push(...labels);const pages=[];for(let i=0;i<slots.length;i+=capacity)pages.push(slots.slice(i,i+capacity));const w=open('','_blank');if(!w){alert('O navegador bloqueou a janela de impressão. Permita pop-ups para o JF Oficina.');return}const pageHtml=pages.map((page,pi)=>`<section class="sheet ${pi<pages.length-1?'break':''}">${Array.from({length:capacity},(_,i)=>{const z=page[i];return `<div class="lab">${z?`<div class="qr" id="q-${pi}-${i}"></div><div class="txt"><div class="code">${escx(productCode(z))}</div><div class="desc">${escx((z.descricao||'').slice(0,75))}</div><div class="meta">${escx([productMakerCode(z),z.localizacao].filter(Boolean).join(' · '))}</div></div>`:''}</div>`}).join('')}</section>`).join('');const qrJs=[];pages.forEach((page,pi)=>page.forEach((z,i)=>{if(z)qrJs.push(`new QRCode(document.getElementById('q-${pi}-${i}'),{text:${JSON.stringify('JF-PRODUTO-'+productCode(z))},width:56,height:56,correctLevel:QRCode.CorrectLevel.M});`)}));w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Etiquetas JF — ${escx(p.name)}</title><script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"><\/script><style>@page{size:${p.pageW}mm ${p.pageH}mm;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0}.sheet{position:relative;width:${p.pageW}mm;height:${p.pageH}mm;display:grid;grid-template-columns:repeat(${p.cols},${p.labelW}mm);grid-template-rows:repeat(${p.rows},${p.labelH}mm);column-gap:${p.gapX}mm;row-gap:${p.gapY}mm;padding:${p.marginY}mm ${p.marginX}mm}.break{page-break-after:always}.lab{width:${p.labelW}mm;height:${p.labelH}mm;overflow:hidden;display:grid;grid-template-columns:18mm 1fr;gap:2mm;align-items:center;padding:2mm;font-family:Arial,sans-serif}.qr{width:15mm;height:15mm}.qr img,.qr canvas{width:15mm!important;height:15mm!important}.code{font-size:12pt;font-weight:700;line-height:1.05}.desc{font-size:8.5pt;font-weight:700;line-height:1.05;margin-top:1mm;max-height:9mm;overflow:hidden}.meta{font-size:6.5pt;line-height:1.05;margin-top:.7mm;color:#333}.controls{position:fixed;right:10px;top:10px;z-index:9}@media print{.controls{display:none}}</style></head><body><div class="controls"><button onclick="print()">Imprimir</button></div>${pageHtml}<script>${qrJs.join('')}<\/script></body></html>`);w.document.close();setTimeout(()=>w.focus(),300)}
 function bindUI(){closeLabelDlg.onclick=cancelLabelDlg.onclick=()=>labelDlg.close();[labelFindCode,labelFindDesc,labelFindExtra].forEach(i=>i.oninput=renderSearch);clearLabelSelection.onclick=()=>{selected=[];renderSelected()};labelProject.onchange=renderProjectFields;saveLabelProject.onclick=()=>{const p=readProjectFields();let a=projects(),i=a.findIndex(x=>x.id===p.id);if(i>=0)a[i]=p;else a.push(p);saveProjects(a);projectOptions();labelProject.value=p.id;renderProjectFields();alert('Projeto de etiqueta salvo neste aparelho.');};printSelectedLabels.onclick=printNow;}
 function openLabelManager(){ensureDialog();selected=[];projectOptions();renderSelected();renderSearch();labelStart.value=1;labelDlg.showModal()}
 window.openLabelManager=openLabelManager;
 function install(){ensureDialog();const btn=document.getElementById('printLabels');if(btn)btn.onclick=openLabelManager;}
 if(document.readyState==='loading')addEventListener('DOMContentLoaded',()=>setTimeout(install,0));else setTimeout(install,0);
})();
