const DEFAULT_TECH_LIBRARY=[
 {id:'ac_pressostato',category:'Ar-condicionado',name:'Pressostato aberto / danificado',keywords:['pressostato','pressostato aberto','pressostato danificado','circuito aberto pressostato'],specificity:100,steps:['Analisadas as pressões do sistema','Analisado o circuito elétrico de acionamento do compressor','Verificada a alimentação do pressostato','Verificado o sinal de saída do pressostato','Confirmada falha do pressostato','Substituído o pressostato','Testado o acionamento do compressor após o reparo','Verificadas as pressões de trabalho após o reparo','Realizado teste final de eficiência do sistema']},
 {id:'ac_baixa_carga',category:'Ar-condicionado',name:'Baixa carga de fluido refrigerante',keywords:['baixa carga','falta de fluido','pouco fluido','sem fluido','baixa pressão','vazamento'],steps:['Analisadas as pressões de alta e baixa do sistema','Realizada inspeção para localização de vazamento','Identificado o ponto de fuga do fluido refrigerante','Reparado ou substituído o componente responsável pelo vazamento','Realizado teste de estanqueidade com nitrogênio','Confirmada estanqueidade do sistema após o reparo','Realizado vácuo no sistema','Verificada a necessidade de complemento ou substituição do óleo lubrificante','Realizada carga de fluido refrigerante conforme especificação do equipamento','Verificadas as pressões de trabalho após a carga','Verificada a temperatura de insuflamento','Realizado teste final de eficiência do sistema']},
 {id:'ac_ventilacao',category:'Ar-condicionado',name:'Falha de ventilação / baixo fluxo de ar',keywords:['ventilação','ventilador','baixo fluxo','sem ventilação','evaporador obstruído','filtro obstruído'],steps:['Verificado o fluxo de ar na cabine','Inspecionados os filtros de ar interno e externo','Inspecionada a caixa evaporadora','Verificados os drenos da caixa evaporadora','Verificada a alimentação elétrica dos ventiladores','Verificado o comando de velocidade dos ventiladores','Verificado o estado dos motores dos ventiladores','Realizada limpeza do evaporador, filtros e drenos quando necessário','Reparado o circuito elétrico de ventilação quando necessário','Realizado teste final de ventilação e eficiência']},
 {id:'eletrica_partida',category:'Elétrica',name:'Falha no sistema de partida',keywords:['não pega','nao pega','não dá partida','nao da partida','partida','motor de partida','arranque'],steps:['Verificada a tensão da bateria em repouso','Verificada a tensão da bateria durante a partida','Verificada a alimentação positiva do circuito de partida','Verificado o aterramento do motor e da cabine','Verificado o comando de partida','Verificado o relé de partida','Verificada a alimentação do solenoide do motor de partida','Realizado teste de queda de tensão no circuito positivo','Realizado teste de queda de tensão no circuito negativo','Verificados os intertravamentos de segurança do sistema','Reparado o circuito ou componente identificado','Realizado teste final do sistema de partida']},
 {id:'eletrica_carga',category:'Elétrica',name:'Falha no sistema de carga',keywords:['alternador','não carrega','nao carrega','baixa carga bateria','queda de tensão carga','sistema de carga'],steps:['Verificada a tensão da bateria com o equipamento desligado','Verificada a tensão de carga do alternador','Verificada a queda de tensão entre alternador e bateria','Inspecionados os cabos positivos e aterramentos','Inspecionados fusíveis e porta-fusíveis do circuito de carga','Verificado o sinal de excitação do alternador','Verificado o regulador de tensão quando aplicável','Reparadas conexões ou cabos com perda de alimentação','Realizado teste do sistema após o reparo']},
 {id:'eletrica_iluminacao',category:'Elétrica',name:'Falha de iluminação / sinalização',keywords:['iluminação','farol','luz','lanterna','sinalização','lampada','lâmpada'],steps:['Verificada a alimentação do circuito de iluminação','Verificado o comando/interruptor do circuito','Verificado o relé de iluminação quando aplicável','Verificados fusíveis e porta-fusíveis','Verificada a continuidade dos condutores','Verificados os aterramentos dos pontos de iluminação','Verificada a carga instalada e condição das lâmpadas/faróis','Reparado o circuito ou substituído o componente danificado','Realizado teste final de iluminação e sinalização']},
 {id:'eletronica_can',category:'Eletrônica',name:'Falha de comunicação / Rede CAN',keywords:['can','rede can','sem comunicação','sem comunicacao','falha de comunicação','falha comunicacao','módulo offline','modulo offline'],steps:['Realizada leitura dos códigos de falha dos módulos','Verificadas as alimentações positivas dos módulos envolvidos','Verificados os aterramentos dos módulos envolvidos','Medida a resistência da rede CAN com o sistema desenergizado','Verificadas as tensões CAN High e CAN Low','Inspecionados conectores e derivações da rede','Realizado isolamento dos ramos da rede para localização da falha','Reparado o chicote, conector ou terminação identificada','Apagados os códigos de falha quando aplicável','Realizado teste final de comunicação entre os módulos']},
 {id:'eletronica_sensor',category:'Eletrônica',name:'Falha de sensor / atuador',keywords:['sensor','atuador','sinal do sensor','circuito sensor','circuito atuador'],steps:['Realizada leitura dos códigos de falha','Verificada a alimentação de referência do sensor','Verificado o aterramento do sensor/atuador','Verificado o sinal do componente','Testada a continuidade do chicote até o módulo','Verificada a presença de curto para positivo ou aterramento','Comparado o sinal com o valor esperado quando disponível','Realizado comando do atuador por ferramenta de diagnóstico quando disponível','Reparado o circuito ou substituído o componente identificado','Realizado teste final do sistema']}
];

function normalizeTextTech(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function techLibrary(){normalize();let custom=(S.custom.techLibrary||[]).filter(x=>!x.deleted);return [...DEFAULT_TECH_LIBRARY,...custom];}
function scoreRule(rule,found,complaint){let f=normalizeTextTech(found),c=normalizeTextTech(complaint),score=0,hits=[],foundHits=0,complaintHits=0;for(const kw of rule.keywords||[]){let k=normalizeTextTech(kw);if(!k)continue;if(f.includes(k)){foundHits++;score+=100;hits.push(kw)}else if(c.includes(k)){complaintHits++;score+=5;hits.push(kw)}}score+=(rule.specificity||0);return {score,hits,foundHits,complaintHits}}
function identifyBestRule(){let found=document.getElementById('osFinding')?.value||'',complaint=document.getElementById('osComplaint')?.value||'',category=document.getElementById('checkCategory')?.value||'',candidates=techLibrary().filter(r=>!category||r.category===category);let scored=candidates.map(r=>({rule:r,...scoreRule(r,found,complaint)})).sort((a,b)=>b.score-a.score);let exact=scored.filter(x=>x.foundHits>0).sort((a,b)=>{if(b.foundHits!==a.foundHits)return b.foundHits-a.foundHits;return (b.rule.specificity||0)-(a.rule.specificity||0)});if(exact.length)return exact[0];let fallback=scored.filter(x=>x.complaintHits>0);return fallback.length?fallback[0]:null;}
function fillRuleSelect(selected=''){let cat=document.getElementById('checkCategory')?.value||'',list=techLibrary().filter(r=>!cat||r.category===cat),sel=document.getElementById('checkRule');if(!sel)return;sel.innerHTML='<option value="">Selecione...</option>'+list.map(r=>`<option value="${esc(r.id)}" ${String(r.id)===String(selected)?'selected':''}>${esc(r.category)} — ${esc(r.name)}</option>`).join('');}
function renderChecklist(){if(!work.checklist)work.checklist={rule_id:'',category:'',items:[]};let box=document.getElementById('checkItems');if(!box)return;box.innerHTML=(work.checklist.items||[]).length?work.checklist.items.map((x,i)=>`<div class="section" style="padding:8px;margin-bottom:6px"><label style="display:flex;gap:8px;align-items:flex-start"><input type="checkbox" class="checkDone" data-i="${i}" ${x.done?'checked':''} style="width:auto;margin-top:4px"><span style="flex:1">${esc(x.text)}</span></label><input class="checkNote" data-i="${i}" value="${esc(x.note||'')}" placeholder="Observação / medição opcional"></div>`).join(''):'<p class="muted">Nenhum procedimento sugerido ainda.</p>';document.querySelectorAll('.checkDone').forEach(e=>e.onchange=()=>{let i=+e.dataset.i;work.checklist.items[i].done=e.checked;dirty()});document.querySelectorAll('.checkNote').forEach(e=>e.oninput=()=>{let i=+e.dataset.i;work.checklist.items[i].note=e.value;dirty()});}
function loadChecklistRule(rule,reason=''){if(!rule)return;work.checklist={rule_id:rule.id,category:rule.category,items:(rule.steps||[]).map(t=>({text:t,done:false,note:''}))};document.getElementById('checkCategory').value=rule.category;fillRuleSelect(rule.id);document.getElementById('checkRule').value=rule.id;document.getElementById('checkReason').innerHTML=`<b>${esc(rule.category)} — ${esc(rule.name)}</b>${reason?'<br><span class="small">'+esc(reason)+'</span>':''}`;renderChecklist();dirty()}
function checklistDescription(){let done=(work.checklist?.items||[]).filter(x=>x.done);if(!done.length)return '';let parts=done.map(x=>x.note?`${x.text} (${x.note})`:x.text);return technicalLocalReview(parts.join('. ')+'.');}
function applyChecklistDescription(){let text=checklistDescription();if(!text){alert('Marque os procedimentos que realmente foram executados.');return}let target=document.getElementById('osServiceDesc');if(!target)return;previewGenerated(target,text,'Prévia da Descrição do Serviço');}
function renderLibraryList(){let box=document.getElementById('libraryList');if(!box)return;let custom=(S.custom.techLibrary||[]).filter(x=>!x.deleted);box.innerHTML=custom.length?custom.map(r=>`<div class="section"><b>${esc(r.category)} — ${esc(r.name)}</b><br><span class="small muted">${esc((r.keywords||[]).join(', '))}</span><div class="toolbar"><button type="button" onclick="deleteLibraryRule('${esc(r.id)}')">Excluir regra personalizada</button></div></div>`).join(''):'<p class="muted">Nenhuma regra personalizada. As regras padrão continuam disponíveis.</p>';}
window.deleteLibraryRule=async id=>{let r=(S.custom.techLibrary||[]).find(x=>x.id===id);if(r)r.deleted=true;await saveDB();fillRuleSelect();renderLibraryList()}
