// JF Oficina v0.20.17 — cadastro mestre de locações do estoque
(function(){
 const $=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 function ensureStore(){if(typeof S==='undefined')return[];S.custom=S.custom||{};S.custom.locationCatalog=S.custom.locationCatalog||[];return S.custom.locationCatalog}
 function list(){return ensureStore()}
 function nextCode(){let max=0;list().forEach(x=>{const m=String(x.code||'').match(/(\d+)$/);if(m)max=Math.max(max,Number(m[1])||0)});return 'LOC'+String(max+1).padStart(3,'0')}
 function active(){return list().filter(x=>x.active!==false).sort((a,b)=>String(a.code||'').localeCompare(String(b.code||''),'pt-BR',{numeric:true}))}
 function currentProductLocations(){if(typeof activeProducts!=='function')return[];return [...new Set(activeProducts().map(p=>String(p.localizacao||'').trim()).filter(Boolean))]}
 async function persist(){if(typeof saveDB==='function')await saveDB();if(typeof render==='function')render();refreshDatalist();renderRows();if(typeof window.pushCentralSync==='function')window.pushCentralSync().catch(()=>{})}
 function refreshDatalist(){let dl=$('jfLocationList');if(!dl){dl=document.createElement('datalist');dl.id='jfLocationList';document.body.appendChild(dl)}
   const catalog=active();const known=new Set(catalog.map(x=>norm(x.address)));let html=catalog.map(x=>`<option value="${esc(x.address)}" label="${esc(x.code)} — ${esc(x.address)}"></option>`).join('');
   currentProductLocations().filter(x=>!known.has(norm(x))).forEach(x=>html+=`<option value="${esc(x)}" label="Locação existente"></option>`);dl.innerHTML=html;
   const input=$('productLoc');if(input){input.setAttribute('list','jfLocationList');input.setAttribute('autocomplete','off')}
 }
 function ensureProductButton(){const input=$('productLoc');if(!input||$('manageLocationsFromProduct'))return;const label=input.closest('label');if(!label)return;const b=document.createElement('button');b.type='button';b.id='manageLocationsFromProduct';b.textContent='Gerenciar locações';b.style.marginTop='4px';b.onclick=open;label.appendChild(b);refreshDatalist()}
 function ensureStockButton(){const stock=$('stock');if(!stock||$('manageStockLocations'))return;const bar=stock.querySelector('.toolbar');if(!bar)return;const b=document.createElement('button');b.type='button';b.id='manageStockLocations';b.textContent='Locações';b.onclick=open;bar.appendChild(b)}
 function ensureDialog(){if($('locationCatalogDlg'))return;const d=document.createElement('dialog');d.id='locationCatalogDlg';d.className='modal';d.innerHTML=`<div class="dhead"><div><b>Locações do estoque</b><div class="small">Cadastro mestre de endereços e códigos internos</div></div><button type="button" id="locClose">✕</button></div><div class="dbody"><div class="section"><h3 id="locFormTitle">Nova locação</h3><input type="hidden" id="locId"><div class="grid2"><label>Código interno<input id="locCode" placeholder="Ex.: LOC001"></label><label>Endereço / locação<input id="locAddress" placeholder="Ex.: Corredor A · Estante 02 · Prateleira 03"></label></div><label>Observação<input id="locNote" placeholder="Opcional"></label><label><input id="locActive" type="checkbox" checked style="width:auto"> Ativa</label><div class="toolbar"><button type="button" class="primary" id="locSave">Salvar locação</button><button type="button" id="locCancelEdit">Limpar</button><button type="button" id="locImport">Importar locações existentes dos produtos</button></div></div><div class="section"><div class="toolbar"><h3 style="margin:0">Locações cadastradas</h3><input id="locSearch" placeholder="Buscar código ou endereço"></div><div id="locRows"></div></div></div>`;document.body.appendChild(d);
   const st=document.createElement('style');st.textContent=`#locationCatalogDlg{width:min(850px,96vw);max-height:90vh}.locRow{display:grid;grid-template-columns:120px minmax(240px,1fr) 90px auto;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #edf0f2}.locRow .muted{font-size:11px}.locStatus{font-weight:800;font-size:12px}@media(max-width:700px){.locRow{grid-template-columns:90px 1fr auto}.locRow .locStatus{grid-column:2}.locRow .locActions{grid-column:3;grid-row:1/3}}`;document.head.appendChild(st);
   $('locClose').onclick=()=>d.close();$('locCancelEdit').onclick=clearForm;$('locSave').onclick=saveForm;$('locImport').onclick=importExisting;$('locSearch').oninput=renderRows;
 }
 function clearForm(){if(!$('locId'))return;$('locId').value='';$('locFormTitle').textContent='Nova locação';$('locCode').value=nextCode();$('locAddress').value='';$('locNote').value='';$('locActive').checked=true;$('locAddress').focus()}
 function open(){ensureDialog();clearForm();renderRows();$('locationCatalogDlg').showModal()}
 function edit(id){const x=list().find(v=>String(v.id)===String(id));if(!x)return;ensureDialog();$('locId').value=x.id;$('locFormTitle').textContent='Editar locação';$('locCode').value=x.code||'';$('locAddress').value=x.address||'';$('locNote').value=x.note||'';$('locActive').checked=x.active!==false;$('locationCatalogDlg').showModal();$('locAddress').focus()}
 async function saveForm(){const id=$('locId').value.trim(),code=$('locCode').value.trim().toUpperCase(),address=$('locAddress').value.trim(),note=$('locNote').value.trim(),isActive=$('locActive').checked;if(!code||!address){alert('Informe o código interno e o endereço da locação.');return}const dupCode=list().find(x=>norm(x.code)===norm(code)&&String(x.id)!==String(id));if(dupCode){alert('Este código interno já está cadastrado.');return}const dupAddr=list().find(x=>norm(x.address)===norm(address)&&String(x.id)!==String(id));if(dupAddr){alert('Este endereço de locação já está cadastrado.');return}let x=id?list().find(v=>String(v.id)===String(id)):null;if(!x){x={id:'LOC-'+Date.now()};list().push(x)}Object.assign(x,{code,address,note,active:isActive,updated_at:new Date().toISOString()});if(!x.created_at)x.created_at=x.updated_at;await persist();clearForm()}
 async function importExisting(){const existing=currentProductLocations();const known=new Set(list().map(x=>norm(x.address)));const add=existing.filter(x=>!known.has(norm(x)));if(!add.length){alert('Todas as locações existentes já estão cadastradas.');return}add.forEach(addr=>list().push({id:'LOC-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),code:nextCode(),address:addr,note:'Importada do cadastro de produtos',active:true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}));await persist();alert(add.length+' locação(ões) importada(s).')}
 function renderRows(){const box=$('locRows');if(!box)return;const q=norm($('locSearch')?.value);const rows=list().slice().sort((a,b)=>String(a.code||'').localeCompare(String(b.code||''),'pt-BR',{numeric:true})).filter(x=>!q||norm([x.code,x.address,x.note].join(' ')).includes(q));box.innerHTML=rows.length?rows.map(x=>`<div class="locRow"><div><b>${esc(x.code||'')}</b></div><div><b>${esc(x.address||'')}</b>${x.note?`<div class="muted">${esc(x.note)}</div>`:''}</div><div class="locStatus">${x.active===false?'Inativa':'Ativa'}</div><div class="locActions"><button type="button" data-edit-loc="${esc(x.id)}">Editar</button></div></div>`).join(''):'<p class="muted">Nenhuma locação cadastrada.</p>';box.querySelectorAll('[data-edit-loc]').forEach(b=>b.onclick=()=>edit(b.dataset.editLoc))}
 function heal(){try{ensureStockButton();ensureProductButton();refreshDatalist()}catch(e){}}
 addEventListener('DOMContentLoaded',()=>{setTimeout(heal,800);setTimeout(heal,1800)});new MutationObserver(()=>setTimeout(heal,0)).observe(document.documentElement,{childList:true,subtree:true});
 window.JFLocationCatalog={open,edit,refresh:refreshDatalist,list};
})();