// JF Oficina v0.20.19 — cadastro mestre de locações com reconciliação
(function(){
 const $=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 function ensureStore(){if(typeof S==='undefined')return[];S.custom=S.custom||{};S.custom.locationCatalog=S.custom.locationCatalog||[];return S.custom.locationCatalog}
 function list(){return ensureStore()}
 function allProducts(){if(typeof S!=='undefined'&&Array.isArray(S.products))return S.products;if(typeof activeProducts==='function')return activeProducts();return[]}
 function nextCode(){let max=0;list().forEach(x=>{const m=String(x.code||'').match(/(\d+)$/);if(m)max=Math.max(max,Number(m[1])||0)});return 'LOC'+String(max+1).padStart(3,'0')}
 function active(){return list().filter(x=>x.active!==false).sort((a,b)=>String(a.code||'').localeCompare(String(b.code||''),'pt-BR',{numeric:true}))}
 function isPseudoLocation(v){return ['compra direta','direct purchase'].includes(norm(v))}
 function aliasesOf(x){return Array.isArray(x?.aliases)?x.aliases.filter(Boolean):[]}
 function namesOf(x){return [x?.address,...aliasesOf(x)].filter(Boolean)}
 function currentProductLocations(){return [...new Set(allProducts().map(p=>String(p.localizacao||'').trim()).filter(Boolean))]}
 function catalogMatch(addr,excludeId=''){const n=norm(addr);return list().find(x=>String(x.id)!==String(excludeId)&&namesOf(x).some(v=>norm(v)===n))||null}
 function moveProducts(fromNames,toAddress){const src=new Set((Array.isArray(fromNames)?fromNames:[fromNames]).map(norm).filter(Boolean));let moved=0;allProducts().forEach(p=>{if(src.has(norm(p.localizacao))){p.localizacao=toAddress;moved++}});return moved}
 function productCount(x){const names=new Set(namesOf(x).map(norm));let n=0;allProducts().forEach(p=>{if(names.has(norm(p.localizacao)))n++});return n}
 async function persist(){if(typeof saveDB==='function')await saveDB();if(typeof render==='function')render();refreshDatalist();renderRows();if(typeof window.pushCentralSync==='function')window.pushCentralSync().catch(()=>{})}
 function refreshDatalist(){let dl=$('jfLocationList');if(!dl){dl=document.createElement('datalist');dl.id='jfLocationList';document.body.appendChild(dl)}
   const catalog=active();const known=new Set();catalog.forEach(x=>namesOf(x).forEach(v=>known.add(norm(v))));let html=catalog.map(x=>`<option value="${esc(x.address)}" label="${esc(x.code)} — ${esc(x.address)}"></option>`).join('');
   currentProductLocations().filter(x=>!known.has(norm(x))&&!isPseudoLocation(x)).forEach(x=>html+=`<option value="${esc(x)}" label="Locação existente"></option>`);dl.innerHTML=html;
   const input=$('productLoc');if(input){input.setAttribute('list','jfLocationList');input.setAttribute('autocomplete','off')}
 }
 function ensureProductButton(){const input=$('productLoc');if(!input||$('manageLocationsFromProduct'))return;const label=input.closest('label');if(!label)return;const b=document.createElement('button');b.type='button';b.id='manageLocationsFromProduct';b.textContent='Gerenciar locações';b.style.marginTop='4px';b.onclick=open;label.appendChild(b);refreshDatalist()}
 function ensureStockButton(){const stock=$('stock');if(!stock||$('manageStockLocations'))return;const bar=stock.querySelector('.toolbar');if(!bar)return;const b=document.createElement('button');b.type='button';b.id='manageStockLocations';b.textContent='Locações';b.onclick=open;bar.appendChild(b)}
 function ensureDialog(){if($('locationCatalogDlg'))return;const d=document.createElement('dialog');d.id='locationCatalogDlg';d.className='modal';d.innerHTML=`<div class="dhead"><div><b>Locações do estoque</b><div class="small">Cadastro mestre de endereços e códigos internos</div></div><button type="button" id="locClose">✕</button></div><div class="dbody"><div class="section"><h3 id="locFormTitle">Nova locação</h3><input type="hidden" id="locId"><div class="grid2"><label>Código interno<input id="locCode" placeholder="Ex.: LOC001"></label><label>Endereço / locação<input id="locAddress" placeholder="Ex.: Corredor A · Estante 02 · Prateleira 03"></label></div><label>Observação<input id="locNote" placeholder="Opcional"></label><label><input id="locActive" type="checkbox" checked style="width:auto"> Ativa</label><div class="toolbar"><button type="button" class="primary" id="locSave">Salvar locação</button><button type="button" id="locCancelEdit">Limpar</button><button type="button" id="locImport">Importar / reconciliar existentes</button></div></div><div class="section"><div class="toolbar"><h3 style="margin:0">Locações cadastradas</h3><input id="locSearch" placeholder="Buscar código ou endereço"></div><div id="locRows"></div></div></div>`;document.body.appendChild(d);
   const st=document.createElement('style');st.textContent=`#locationCatalogDlg{width:min(900px,96vw);max-height:90vh}.locRow{display:grid;grid-template-columns:110px minmax(240px,1fr) 95px 90px auto;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #edf0f2}.locRow .muted{font-size:11px}.locStatus{font-weight:800;font-size:12px}.locCount{font-size:12px;font-weight:700;color:#425466}.locActions{display:flex;gap:6px;flex-wrap:wrap}@media(max-width:700px){.locRow{grid-template-columns:90px 1fr auto}.locRow .locStatus,.locRow .locCount{grid-column:2}.locRow .locActions{grid-column:3;grid-row:1/4}}`;document.head.appendChild(st);
   $('locClose').onclick=()=>d.close();$('locCancelEdit').onclick=clearForm;$('locSave').onclick=saveForm;$('locImport').onclick=importExisting;$('locSearch').oninput=renderRows;
 }
 function clearForm(){if(!$('locId'))return;$('locId').value='';$('locFormTitle').textContent='Nova locação';$('locCode').value=nextCode();$('locAddress').value='';$('locNote').value='';$('locActive').checked=true;$('locAddress').focus()}
 function open(){ensureDialog();clearForm();renderRows();$('locationCatalogDlg').showModal()}
 function edit(id){const x=list().find(v=>String(v.id)===String(id));if(!x)return;ensureDialog();$('locId').value=x.id;$('locFormTitle').textContent='Editar locação';$('locCode').value=x.code||'';$('locAddress').value=x.address||'';$('locNote').value=x.note||'';$('locActive').checked=x.active!==false;$('locationCatalogDlg').showModal();$('locAddress').focus()}
 async function saveForm(){const id=$('locId').value.trim(),code=$('locCode').value.trim().toUpperCase(),address=$('locAddress').value.trim(),note=$('locNote').value.trim(),isActive=$('locActive').checked;if(!code||!address){alert('Informe o código interno e o endereço da locação.');return}if(isPseudoLocation(address)){alert('COMPRA DIRETA não é uma locação física e não pode ser cadastrada como endereço de estoque.');return}const dupCode=list().find(x=>norm(x.code)===norm(code)&&String(x.id)!==String(id));if(dupCode){alert('Este código interno já está cadastrado.');return}const dupAddr=catalogMatch(address,id);if(dupAddr){alert('Este endereço já pertence a '+dupAddr.code+'. Use Mesclar se os dois códigos representam o mesmo local.');return}let x=id?list().find(v=>String(v.id)===String(id)):null;const oldNames=x?namesOf(x):[];const oldAddress=x?.address||'';if(!x){x={id:'LOC-'+Date.now(),aliases:[]};list().push(x)}if(oldAddress&&norm(oldAddress)!==norm(address)){x.aliases=[...new Set([...aliasesOf(x),oldAddress].filter(v=>norm(v)!==norm(address)))];moveProducts(oldNames,address)}Object.assign(x,{code,address,note,active:isActive,updated_at:new Date().toISOString()});if(!x.created_at)x.created_at=x.updated_at;await persist();clearForm()}
 async function mergeInto(sourceId){const src=list().find(x=>String(x.id)===String(sourceId));if(!src)return;const targetCode=prompt('Mesclar '+src.code+' ('+src.address+') em qual código?\nEx.: LOC004');if(!targetCode)return;const dst=list().find(x=>norm(x.code)===norm(targetCode));if(!dst){alert('Código de destino não encontrado.');return}if(dst.id===src.id){alert('Escolha outro código.');return}const moved=productCount(src);if(!confirm('Mesclar '+src.code+' em '+dst.code+'?\n'+moved+' produto(s) serão movidos para "'+dst.address+'".\nO código '+src.code+' será removido do catálogo.'))return;moveProducts(namesOf(src),dst.address);dst.aliases=[...new Set([...aliasesOf(dst),...namesOf(src)].filter(v=>norm(v)!==norm(dst.address)))];dst.updated_at=new Date().toISOString();const i=list().findIndex(x=>x.id===src.id);if(i>=0)list().splice(i,1);await persist();alert(moved+' produto(s) reconciliados em '+dst.code+'.')}
 async function importExisting(){let changed=false,moved=0,added=0,ignored=0,removed=0;for(let i=list().length-1;i>=0;i--){const x=list()[i];if(isPseudoLocation(x.address)){list().splice(i,1);removed++;changed=true}}
   for(const addr of currentProductLocations()){if(isPseudoLocation(addr)){ignored++;continue}const match=catalogMatch(addr);if(match){if(norm(addr)!==norm(match.address)){moved+=moveProducts([addr],match.address);match.aliases=[...new Set([...aliasesOf(match),addr])];changed=true}continue}list().push({id:'LOC-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),code:nextCode(),address:addr,note:'Importada do cadastro de produtos',aliases:[],active:true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});added++;changed=true}
   if(changed)await persist();alert('Reconciliação concluída.\nNovas locações: '+added+'\nProdutos realocados por alias: '+moved+'\nEntradas não físicas ignoradas: '+ignored+'\nCadastros não físicos removidos: '+removed)}
 function renderRows(){const box=$('locRows');if(!box)return;const q=norm($('locSearch')?.value);const rows=list().slice().sort((a,b)=>String(a.code||'').localeCompare(String(b.code||''),'pt-BR',{numeric:true})).filter(x=>!q||norm([x.code,x.address,x.note,...aliasesOf(x)].join(' ')).includes(q));box.innerHTML=rows.length?rows.map(x=>`<div class="locRow"><div><b>${esc(x.code||'')}</b></div><div><b>${esc(x.address||'')}</b>${x.note?`<div class="muted">${esc(x.note)}</div>`:''}${aliasesOf(x).length?`<div class="muted">Anterior: ${esc(aliasesOf(x).join(' · '))}</div>`:''}</div><div class="locStatus">${x.active===false?'Inativa':'Ativa'}</div><div class="locCount">${productCount(x)} item(ns)</div><div class="locActions"><button type="button" data-edit-loc="${esc(x.id)}">Editar</button><button type="button" data-merge-loc="${esc(x.id)}">Mesclar</button></div></div>`).join(''):'<p class="muted">Nenhuma locação cadastrada.</p>';box.querySelectorAll('[data-edit-loc]').forEach(b=>b.onclick=()=>edit(b.dataset.editLoc));box.querySelectorAll('[data-merge-loc]').forEach(b=>b.onclick=()=>mergeInto(b.dataset.mergeLoc))}
 function heal(){try{ensureStockButton();ensureProductButton();refreshDatalist()}catch(e){}}
 addEventListener('DOMContentLoaded',()=>{setTimeout(heal,800);setTimeout(heal,1800)});new MutationObserver(()=>setTimeout(heal,0)).observe(document.documentElement,{childList:true,subtree:true});
 window.JFLocationCatalog={open,edit,merge:mergeInto,refresh:refreshDatalist,list};
})();