// JF Oficina v0.13.0 — gestão avançada, buscas rápidas e relatórios completos
(function(){
 const V='0.13.0';
 const e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function ensure(){
   S.custom=S.custom||{};
   for(const k of ['funcionarios','fornecedores','categorias','marcas','locaisEstoque'])if(!Array.isArray(S.custom[k]))S.custom[k]=[];
 }
 function lower(v){return String(v??'').toLocaleLowerCase('pt-BR')}
 function tokens(q){return lower(q).trim().split(/\s+/).filter(Boolean)}
 function matches(text,q){const t=lower(text);return tokens(q).every(x=>t.includes(x))}
 function addStyle(){if(document.getElementById('jfMgmtStyle'))return;const s=document.createElement('style');s.id='jfMgmtStyle';s.textContent=`
 .jfQuick{border:1px solid var(--line);border-radius:10px;background:#f8fafb;padding:9px;margin:8px 0}.jfQuick input{margin:0}.jfQuickResults{max-height:230px;overflow:auto;background:#fff;border:1px solid var(--line);border-radius:8px;margin-top:6px}.jfQuickItem{padding:8px 10px;border-bottom:1px solid #edf0f2;cursor:pointer}.jfQuickItem:hover{background:#fff4d8}.jfQuickItem:last-child{border-bottom:0}.jfPath{font-size:11px;color:var(--muted);margin-bottom:8px}.jfFolderSub{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.jfFolderSub button{text-align:left;white-space:normal;min-height:72px;background:#fff;border:1px solid var(--line)}.jfFolderSub b{display:block}.jfFolderSub span{display:block;font-size:11px;color:var(--muted);margin-top:3px}.jfReportGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:9px;margin:10px 0}.jfReportCard{background:#fff;border:1px solid var(--line);border-radius:11px;padding:12px;cursor:pointer}.jfReportCard:hover{border-color:#f2a51a}.jfReportCard b{display:block}.jfReportCard span{font-size:11px;color:var(--muted)}.jfKpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px;margin:8px 0}.jfKpi{background:#fff;border:1px solid var(--line);border-radius:9px;padding:10px}.jfKpi b{display:block;font-size:20px}.jfStickySearch{position:sticky;top:0;background:#fff;z-index:2;padding-bottom:6px}.jfBadge{font-size:10px;padding:2px 6px;border-radius:999px;background:#eef2f5}.jfMasterTable td{vertical-align:middle}
 @media(max-width:800px){.jfFolderSub{grid-template-columns:1fr 1fr}.jfReportGrid{grid-template-columns:1fr}.jfQuickResults{max-height:180px}}
 `;document.head.appendChild(s)}
 function masterId(prefix){return uid(prefix)}
 function masterList(kind){ensure();return S.custom[kind]||[]}
 function saveMaster(kind,record){ensure();const a=masterList(kind),i=a.findIndex(x=>String(x.id)===String(record.id));if(i>=0)a[i]=record;else a.unshift(record);return saveDB()}

 function enhanceAdmin(){
   const panel=document.getElementById('adminPanel');if(!panel||document.getElementById('jfMasterFolders'))return;
   const host=document.createElement('div');host.id='jfMasterFolders';host.innerHTML=`<div class="jfPath">Cadastros › Organização</div><div class="jfFolderSub">
    <button data-master="categorias"><b>Categorias</b><span>Peças e serviços</span></button>
    <button data-master="marcas"><b>Marcas / Fabricantes</b><span>Equipamentos e peças</span></button>
    <button data-master="locaisEstoque"><b>Locais de estoque</b><span>Oficina, Hilux, prateleiras e caixas</span></button>
    <button data-master="funcionarios"><b>Equipe técnica</b><span>Função, custo, competências e contato</span></button>
    <button data-master="fornecedores"><b>Fornecedores</b><span>Dados comerciais, marcas e condições</span></button>
   </div>`;panel.parentNode.insertBefore(host,panel);
   host.querySelectorAll('[data-master]').forEach(b=>b.onclick=()=>renderMaster(b.dataset.master));
 }
 function masterLabel(k){return {categorias:'Categorias',marcas:'Marcas / Fabricantes',locaisEstoque:'Locais de estoque',funcionarios:'Funcionários / Técnicos',fornecedores:'Fornecedores'}[k]||k}
 function renderMaster(kind){ensure();const p=document.getElementById('adminPanel');if(!p)return;const a=masterList(kind);p.innerHTML=`<div class="jfPath">Cadastros › ${e(masterLabel(kind))}</div><div class="toolbar"><h3 style="margin:0">${e(masterLabel(kind))}</h3><button class="primary" id="jfMasterNew">+ Novo</button><input id="jfMasterSearch" placeholder="Buscar neste cadastro"></div><div class="tablewrap"><table class="jfMasterTable"><thead><tr><th>Nome</th><th>Detalhes</th><th>Situação</th><th></th></tr></thead><tbody id="jfMasterRows"></tbody></table></div>`;
   const draw=()=>{let q=document.getElementById('jfMasterSearch').value;document.getElementById('jfMasterRows').innerHTML=a.filter(x=>matches(JSON.stringify(x),q)).map(x=>`<tr><td><b>${e(x.nome||x.descricao||'')}</b><br><span class="muted">${e(x.codigo||'')}</span></td><td>${e(kind==='funcionarios'?[x.funcao,x.telefone,x.competencias].filter(Boolean).join(' · '):kind==='fornecedores'?[x.contato,x.telefone,x.cidade,x.marcas].filter(Boolean).join(' · '):x.observacoes||x.descricao||'')}</td><td>${x.ativo===false?'Inativo':'Ativo'}</td><td><button data-id="${e(x.id)}">Editar</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">Nenhum registro.</td></tr>';document.querySelectorAll('#jfMasterRows [data-id]').forEach(b=>b.onclick=()=>openMasterEditor(kind,b.dataset.id))};
   document.getElementById('jfMasterSearch').oninput=draw;document.getElementById('jfMasterNew').onclick=()=>openMasterEditor(kind,'');draw();
 }
 function ensureMasterDialog(){if(document.getElementById('jfMasterDlg'))return;const d=document.createElement('dialog');d.id='jfMasterDlg';d.className='modal';d.innerHTML='<form id="jfMasterForm"><div class="dhead"><b id="jfMasterTitle">Cadastro</b><button type="button" id="jfMasterClose">✕</button></div><div class="dbody" id="jfMasterBody"></div><div class="dfoot"><button type="button" id="jfMasterCancel">Cancelar</button><button class="primary">Salvar</button></div></form>';document.body.appendChild(d);jfMasterClose.onclick=jfMasterCancel.onclick=()=>jfMasterDlg.close()}
 let editMaster={kind:'',id:''};
 function openMasterEditor(kind,id){ensureMasterDialog();editMaster={kind,id};const x=id?masterList(kind).find(y=>String(y.id)===String(id)):null;jfMasterTitle.textContent=(x?'Editar ':'Novo ')+masterLabel(kind);let body='';
   if(kind==='funcionarios')body=`<div class="grid2"><label>Código<input id="jmCode" value="${e(x?.codigo||'')}"></label><label>Nome<input id="jmName" required value="${e(x?.nome||'')}"></label><label>Função<input id="jmRole" value="${e(x?.funcao||'')}"></label><label>Telefone<input id="jmPhone" value="${e(x?.telefone||'')}"></label><label>E-mail<input id="jmEmail" value="${e(x?.email||'')}"></label><label>Custo/hora<input id="jmCost" type="number" step=".01" value="${num(x?.custo_hora)}"></label><label>Valor/hora<input id="jmSale" type="number" step=".01" value="${num(x?.valor_hora)}"></label><label>Situação<select id="jmActive"><option value="1" ${x?.ativo===false?'':'selected'}>Ativo</option><option value="0" ${x?.ativo===false?'selected':''}>Inativo</option></select></label></div><label>Competências / especialidades<input id="jmSkills" value="${e(x?.competencias||'')}"></label><label>Observações<textarea id="jmObs">${e(x?.observacoes||'')}</textarea></label>`;
   else if(kind==='fornecedores')body=`<div class="grid2"><label>Código<input id="jmCode" value="${e(x?.codigo||'')}"></label><label>Nome / Razão social<input id="jmName" required value="${e(x?.nome||'')}"></label><label>CPF/CNPJ<input id="jmDoc" value="${e(x?.documento||'')}"></label><label>Inscrição estadual<input id="jmIE" value="${e(x?.ie||'')}"></label><label>Contato<input id="jmContact" value="${e(x?.contato||'')}"></label><label>Telefone<input id="jmPhone" value="${e(x?.telefone||'')}"></label><label>E-mail<input id="jmEmail" value="${e(x?.email||'')}"></label><label>Cidade<input id="jmCity" value="${e(x?.cidade||'')}"></label><label>Endereço<input id="jmAddress" value="${e(x?.endereco||'')}"></label><label>Condição de pagamento<input id="jmPayment" value="${e(x?.pagamento||'')}"></label><label>Situação<select id="jmActive"><option value="1" ${x?.ativo===false?'':'selected'}>Ativo</option><option value="0" ${x?.ativo===false?'selected':''}>Inativo</option></select></label></div><label>Marcas / linhas fornecidas<input id="jmBrands" value="${e(x?.marcas||'')}"></label><label>Observações<textarea id="jmObs">${e(x?.observacoes||'')}</textarea></label>`;
   else body=`<div class="grid2"><label>Nome<input id="jmName" required value="${e(x?.nome||'')}"></label><label>Código / sigla<input id="jmCode" value="${e(x?.codigo||'')}"></label><label>Situação<select id="jmActive"><option value="1" ${x?.ativo===false?'':'selected'}>Ativo</option><option value="0" ${x?.ativo===false?'selected':''}>Inativo</option></select></label></div><label>Descrição / observações<textarea id="jmObs">${e(x?.observacoes||'')}</textarea></label>`;
   jfMasterBody.innerHTML=body;jfMasterDlg.showModal();
 }
 function installMasterSubmit(){ensureMasterDialog();jfMasterForm.onsubmit=async ev=>{ev.preventDefault();const k=editMaster.kind,id=editMaster.id||masterId(k==='funcionarios'?'F':k==='fornecedores'?'FR':'M');const old=masterList(k).find(x=>String(x.id)===String(id))||{};const get=id=>document.getElementById(id)?.value||'';let r={...old,id,nome:get('jmName').trim(),codigo:get('jmCode').trim(),ativo:get('jmActive')!=='0',observacoes:get('jmObs').trim(),updated_at:new Date().toISOString()};if(!old.created_at)r.created_at=r.updated_at;
   if(k==='funcionarios')Object.assign(r,{funcao:get('jmRole').trim(),telefone:get('jmPhone').trim(),email:get('jmEmail').trim(),custo_hora:num(get('jmCost')),valor_hora:num(get('jmSale')),competencias:get('jmSkills').trim()});
   if(k==='fornecedores')Object.assign(r,{documento:get('jmDoc').trim(),ie:get('jmIE').trim(),contato:get('jmContact').trim(),telefone:get('jmPhone').trim(),email:get('jmEmail').trim(),cidade:get('jmCity').trim(),endereco:get('jmAddress').trim(),pagamento:get('jmPayment').trim(),marcas:get('jmBrands').trim()});
   await saveMaster(k,r);jfMasterDlg.close();renderMaster(k);render();};}

 function enhanceProduct(){const form=document.getElementById('productForm');if(!form||form.dataset.jfPro==='1')return;form.dataset.jfPro='1';const loc=document.getElementById('productLoc');if(loc&&!document.getElementById('productBrand')){const grid=loc.closest('.grid2');const supplier=document.getElementById('productSupplier');const extras=document.createElement('div');extras.id='jfProductExtras';extras.style.display='contents';extras.innerHTML='<label>Marca / Fabricante<input id="productBrand"></label><label>Unidade<select id="productUnit"><option>UN</option><option>PC</option><option>JG</option><option>MT</option><option>LT</option><option>KG</option><option>CX</option></select></label><label>Aplicação / equipamentos<input id="productApplication" placeholder="Ex.: BH200, CR5.85, Gladiador"></label><label>Códigos equivalentes<input id="productEquivalent" placeholder="OEM / alternativos"></label>';grid.insertBefore(extras,supplier?.parentElement||null)}
   const origOpen=window.openProduct;window.openProduct=function(id=''){origOpen(id);const p=id?prodBy(id):null;setTimeout(()=>{if(document.getElementById('productBrand'))productBrand.value=p?.marca||'';if(document.getElementById('productUnit'))productUnit.value=p?.unidade||'UN';if(document.getElementById('productApplication'))productApplication.value=p?.aplicacao||'';if(document.getElementById('productEquivalent'))productEquivalent.value=p?.codigos_equivalentes||''},0)};
   const original=form.onsubmit;form.onsubmit=async function(ev){const id=productId.value;const r=await original.call(this,ev);let p=id?prodBy(id):null;if(!p){const code=productCode.value.trim();p=S.produtos.find(x=>productCode(x)===code)}if(p){p.marca=document.getElementById('productBrand')?.value.trim()||'';p.unidade=document.getElementById('productUnit')?.value||'UN';p.aplicacao=document.getElementById('productApplication')?.value.trim()||'';p.codigos_equivalentes=document.getElementById('productEquivalent')?.value.trim()||'';await saveDB()}return r};
 }
 function quickBox(tabId,type){const tab=document.getElementById(tabId);if(!tab||tab.querySelector('[data-jfquick="'+type+'"]'))return;const section=tab.querySelector('.section');if(!section)return;const box=document.createElement('div');box.className='jfQuick';box.dataset.jfquick=type;const ph=type==='product'?'Digite código, fabricante, descrição, marca ou aplicação...':type==='service'?'Digite serviço, categoria ou palavra-chave...':'Digite marca, modelo, série, patrimônio ou cliente...';box.innerHTML=`<b>Busca rápida</b><div class="small muted">Encontre e adicione sem percorrer listas longas.</div><input placeholder="${ph}"><div class="jfQuickResults hidden"></div>`;section.insertBefore(box,section.children[1]||null);const input=box.querySelector('input'),res=box.querySelector('.jfQuickResults');input.oninput=()=>{const q=input.value;if(q.trim().length<2){res.classList.add('hidden');return}let rows=[];
   if(type==='product')rows=activeProducts().filter(p=>matches([productCode(p),productMakerCode(p),p.descricao,p.marca,p.aplicacao,p.codigos_equivalentes,p.codigo_barras,p.categoria].join(' '),q)).slice(0,25).map(p=>({id:p.id,title:`${productCode(p)} · ${p.descricao}`,sub:`Saldo ${num(p.estoque_atual)} ${p.unidade||''} · ${p.marca||''} ${p.localizacao?'· '+p.localizacao:''}`}));
   if(type==='service')rows=(S.servicos_catalogo||[]).filter(s=>s.ativo!==false&&matches([s.descricao,s.categoria,s.palavras_chave,s.codigo].join(' '),q)).slice(0,25).map(s=>({id:s.id,title:s.descricao,sub:`${money(s.valor)} ${s.categoria?'· '+s.categoria:''}`}));
   if(type==='equipment')rows=equips().filter(x=>!work?.cliente_id||String(equipClient(x))===String(work.cliente_id)).filter(x=>matches([equipName(x.id),x.marca,x.modelo,x.numero_serie,x.serie,x.patrimonio,x.tipo,clientName(equipClient(x))].join(' '),q)).slice(0,25).map(x=>({id:x.id,title:equipName(x.id),sub:`${clientName(equipClient(x))} · ${x.numero_serie||x.serie||''}`}));
   res.innerHTML=rows.map((r,i)=>`<div class="jfQuickItem" data-i="${i}"><b>${e(r.title)}</b><div class="small muted">${e(r.sub)}</div></div>`).join('')||'<div class="jfQuickItem muted">Nenhum resultado.</div>';res.classList.remove('hidden');res.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>{const r=rows[+el.dataset.i];if(type==='product'){const p=prodBy(r.id);work.materiais.push({id:uid('P'),produto_id:p.id,quantidade:1,valor:num(p.valor_venda),desconto:0,acrescimo:0,origem:'Oficina'});renderMaterials();renderFinance();dirty()}if(type==='service'){const s=serviceBy(r.id);work.servicos.push({id:uid('S'),servico_id:s.id,descricao:s.descricao,quantidade:1,valor:num(s.valor),desconto:0,acrescimo:0,tecnico:work.tecnico});renderServices();renderFinance();dirty()}if(type==='equipment'){work.equipamentos.push({equipamento_id:r.id,principal:work.equipamentos.length===0,horimetro:''});renderEquipments();dirty()}input.value='';res.classList.add('hidden')})};
 }
 function enhanceOSSearch(){quickBox('tab-materials','product');quickBox('tab-services','service');quickBox('tab-equipments','equipment');const os=document.getElementById('osSearch');if(os)os.placeholder='Buscar OS, cliente, equipamento, série, técnico, defeito, peça ou serviço...'}

 function buildReportCenter(){const reports=document.getElementById('reports');if(!reports||document.getElementById('jfReportsPro'))return;const box=document.createElement('div');box.id='jfReportsPro';box.innerHTML=`<div class="section"><div class="jfPath">Relatórios › Biblioteca</div><h3>Relatórios prontos</h3><p class="muted">Os dados permanecem no sistema; você só abre o relatório quando precisar.</p><div class="jfReportGrid">
   ${[
    ['os-detalhado','OS detalhadas','Atendimentos, defeitos, técnico e valores'],['cliente-historico','Histórico por cliente','OS, equipamentos e faturamento'],['equipamento-historico','Histórico por equipamento','Manutenções e falhas recorrentes'],['produto-consumo','Consumo de peças','Quantidade e OS que consumiram cada item'],['estoque-inventario','Inventário financeiro','Saldo, custo e valor imobilizado'],['estoque-baixo','Estoque baixo','Itens abaixo do mínimo'],['movimentos','Movimentações','Entradas, saídas e ajustes'],['tecnico','Produção por técnico','OS, serviços e valores'],['servicos','Serviços executados','Frequência e faturamento'],['fornecedores','Fornecedores','Cadastro e linhas fornecidas'],['falhas','Falhas recorrentes','Defeitos constatados e equipamentos'],['financeiro','Resumo financeiro','Faturamento por OS e período']
   ].map(x=>`<div class="jfReportCard" data-r="${x[0]}"><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}
   </div></div>`;reports.insertBefore(box,reports.firstChild);box.querySelectorAll('[data-r]').forEach(c=>c.onclick=()=>openReport(c.dataset.r));
 }
 function ensureReportDialog(){if(document.getElementById('jfReportDlg'))return;const d=document.createElement('dialog');d.id='jfReportDlg';d.className='osmodal';d.innerHTML=`<div class="dhead"><div><b id="jrTitle">Relatório</b><div class="small">JF Oficina · relatório gerencial</div></div><button id="jrClose">✕</button></div><div class="dbody"><div class="section jfStickySearch"><div class="grid4"><label>Data inicial<input id="jrFrom" type="date"></label><label>Data final<input id="jrTo" type="date"></label><label>Filtro livre<input id="jrQuery" placeholder="Cliente, técnico, produto, máquina..."></label><label>&nbsp;<button class="primary" id="jrRun">Atualizar relatório</button></label></div><div class="toolbar"><button id="jrPrint">Imprimir / PDF</button><button id="jrCsv">Exportar CSV</button></div></div><div id="jrKpis" class="jfKpis"></div><div id="jrOut" class="tablewrap"></div></div>`;document.body.appendChild(d);jrClose.onclick=()=>jfReportDlg.close();jrRun.onclick=()=>runProReport();jrPrint.onclick=()=>printProReport();jrCsv.onclick=()=>csvProReport()}
 let currentReport='', currentData={title:'',headers:[],rows:[],kpis:[]};
 function openReport(type){ensureReportDialog();currentReport=type;jrQuery.value='';jrFrom.value='';jrTo.value='';runProReport();jfReportDlg.showModal()}
 function dateOk(v){const d=String(v||'').slice(0,10);return(!jrFrom.value||d>=jrFrom.value)&&(!jrTo.value||d<=jrTo.value)}
 function qOk(row){return !jrQuery.value.trim()||matches(row.join(' '),jrQuery.value)}
 function matFor(o){return o.materiais||legacyMaterials(o.id)} function srvFor(o){return o.servicos||legacyServices(o.id)} function eqFor(o){return o.equipamentos||legacyEquipLinks(o.id)}
 function runProReport(){ensure();let H=[],R=[],K=[],title='';const os=orders().filter(o=>dateOk(o.entrada||o.data_entrada));
   if(currentReport==='os-detalhado'||currentReport==='financeiro'){title=currentReport==='financeiro'?'Resumo financeiro':'OS detalhadas';H=['OS','Data','Cliente','Equipamento','Situação','Técnico','Defeito reclamado','Defeito constatado','Total'];R=os.map(o=>[o.numero_os||o.id,String(o.entrada||o.data_entrada||'').slice(0,10),clientName(o.cliente_id),eqFor(o).map(x=>equipName(x.equipamento_id)).join(', '),situation(o),o.tecnico||'',o.defeito_reclamado||'',o.defeito_constatado||'',num(o.total)]).filter(qOk);const total=R.reduce((a,r)=>a+num(r[8]),0);K=[['OS',R.length],['Total',money(total)],['Ticket médio',money(R.length?total/R.length:0)],['Em andamento',R.filter(r=>r[4]==='Em andamento').length]]}
   else if(currentReport==='cliente-historico'){title='Histórico por cliente';H=['Cliente','Cidade/Fazenda','Equipamentos','OS','Última OS','Total em OS'];R=clients().map(c=>{const co=os.filter(o=>String(o.cliente_id)===String(c.id));return[c.nome,[c.cidade,c.fazenda].filter(Boolean).join(' · '),equips().filter(x=>String(equipClient(x))===String(c.id)).length,co.length,co.sort((a,b)=>num(b.numero_os)-num(a.numero_os))[0]?.numero_os||'',co.reduce((a,o)=>a+num(o.total),0)]}).filter(qOk);K=[['Clientes',R.length],['OS relacionadas',R.reduce((a,r)=>a+num(r[3]),0)],['Faturamento',money(R.reduce((a,r)=>a+num(r[5]),0))]]}
   else if(currentReport==='equipamento-historico'){title='Histórico por equipamento';H=['Cliente','Equipamento','Série/Chassi','Patrimônio','OS','Último defeito'];R=equips().map(x=>{const eo=os.filter(o=>eqFor(o).some(l=>String(l.equipamento_id)===String(x.id))).sort((a,b)=>num(b.numero_os)-num(a.numero_os));return[clientName(equipClient(x)),equipName(x.id),x.numero_serie||x.serie||'',x.patrimonio||'',eo.length,eo[0]?.defeito_constatado||eo[0]?.defeito_reclamado||'']}).filter(qOk);K=[['Equipamentos',R.length],['Com histórico',R.filter(r=>num(r[4])>0).length]]}
   else if(currentReport==='produto-consumo'){title='Consumo de peças';H=['Código','Produto','Marca','Aplicação','Qtd consumida','OS relacionadas','Saldo atual'];R=activeProducts().map(p=>{let qty=0,nos=new Set();for(const o of os)for(const m of matFor(o))if(String(m.produto_id)===String(p.id)){qty+=num(m.quantidade);nos.add(String(o.numero_os||o.id))}return[productCode(p),p.descricao||'',p.marca||'',p.aplicacao||'',qty,nos.size,num(p.estoque_atual)]}).filter(r=>num(r[4])>0).filter(qOk).sort((a,b)=>num(b[4])-num(a[4]));K=[['Produtos usados',R.length],['Unidades consumidas',R.reduce((a,r)=>a+num(r[4]),0)]]}
   else if(currentReport==='estoque-inventario'||currentReport==='estoque-baixo'){title=currentReport==='estoque-baixo'?'Estoque baixo':'Inventário financeiro';H=['Código','Produto','Marca','Local','Saldo','Mínimo','Custo','Venda','Custo total'];R=activeProducts().filter(p=>currentReport!=='estoque-baixo'||(num(p.estoque_minimo)>0&&num(p.estoque_atual)<num(p.estoque_minimo))).map(p=>[productCode(p),p.descricao||'',p.marca||'',p.localizacao||'',num(p.estoque_atual),num(p.estoque_minimo),num(p.valor_custo),num(p.valor_venda),num(p.estoque_atual)*num(p.valor_custo)]).filter(qOk);K=[['Itens',R.length],['Unidades',R.reduce((a,r)=>a+num(r[4]),0)],['Custo imobilizado',money(R.reduce((a,r)=>a+num(r[8]),0))]]}
   else if(currentReport==='movimentos'){title='Movimentações de estoque';H=['Data','Produto','Código','Movimento','Origem','OS'];R=(S.custom.stockMoves||[]).filter(m=>dateOk(m.at)).map(m=>{const p=prodBy(m.produto_id);return[String(m.at||'').slice(0,10),p?.descricao||'',p?productCode(p):m.produto_id,num(m.delta),m.origem||'',m.os_id?String(osBy(m.os_id)?.numero_os||m.os_id):'']}).filter(qOk);K=[['Movimentos',R.length],['Saldo movimentado',R.reduce((a,r)=>a+num(r[3]),0)]]}
   else if(currentReport==='tecnico'){title='Produção por técnico';H=['Técnico','OS','Linhas de serviço','Valor de serviços','Valor total das OS'];const map=new Map();for(const o of os){const names=new Set([o.tecnico,...srvFor(o).map(s=>s.tecnico)].filter(Boolean));for(const n of names){let z=map.get(n)||{os:new Set(),lines:0,serv:0,total:0};z.os.add(o.id);for(const s of srvFor(o).filter(s=>!s.tecnico||s.tecnico===n)){z.lines++;z.serv+=num(s.quantidade)*num(s.valor)}z.total+=num(o.total);map.set(n,z)}}R=[...map].map(([n,z])=>[n,z.os.size,z.lines,z.serv,z.total]).filter(qOk);K=[['Técnicos',R.length],['OS',R.reduce((a,r)=>a+num(r[1]),0)],['Serviços',money(R.reduce((a,r)=>a+num(r[3]),0))]]}
   else if(currentReport==='servicos'){title='Serviços executados';H=['Serviço','Categoria','Qtd/Horas','Ocorrências','Valor'];const map=new Map();for(const o of os)for(const s of srvFor(o)){const name=serviceBy(s.servico_id)?.descricao||s.descricao||'Serviço';let z=map.get(name)||{cat:serviceBy(s.servico_id)?.categoria||'',qty:0,n:0,v:0};z.qty+=num(s.quantidade);z.n++;z.v+=num(s.quantidade)*num(s.valor);map.set(name,z)}R=[...map].map(([n,z])=>[n,z.cat,z.qty,z.n,z.v]).filter(qOk).sort((a,b)=>num(b[4])-num(a[4]));K=[['Serviços diferentes',R.length],['Ocorrências',R.reduce((a,r)=>a+num(r[3]),0)],['Valor',money(R.reduce((a,r)=>a+num(r[4]),0))]]}
   else if(currentReport==='fornecedores'){title='Fornecedores';H=['Fornecedor','Documento','Contato','Telefone','Cidade','Marcas / linhas','Condição'];R=masterList('fornecedores').map(f=>[f.nome||'',f.documento||'',f.contato||'',f.telefone||'',f.cidade||'',f.marcas||'',f.pagamento||'']).filter(qOk);K=[['Fornecedores',R.length],['Ativos',masterList('fornecedores').filter(f=>f.ativo!==false).length]]}
   else if(currentReport==='falhas'){title='Falhas recorrentes';H=['Defeito constatado','Ocorrências','Equipamentos / modelos','Clientes'];const map=new Map();for(const o of os){let d=(o.defeito_constatado||o.defeito_reclamado||'').trim();if(!d)continue;let key=d.toLocaleLowerCase('pt-BR').slice(0,180),z=map.get(key)||{d,n:0,eq:new Set(),cl:new Set()};z.n++;eqFor(o).forEach(x=>z.eq.add(equipName(x.equipamento_id)));z.cl.add(clientName(o.cliente_id));map.set(key,z)}R=[...map.values()].map(z=>[z.d,z.n,[...z.eq].filter(Boolean).join(', '),[...z.cl].filter(Boolean).join(', ')]).filter(qOk).sort((a,b)=>num(b[1])-num(a[1]));K=[['Falhas agrupadas',R.length],['Ocorrências',R.reduce((a,r)=>a+num(r[1]),0)]]}
   currentData={title,headers:H,rows:R,kpis:K};jrTitle.textContent=title;jrKpis.innerHTML=K.map(k=>`<div class="jfKpi"><span class="muted">${e(k[0])}</span><b>${e(k[1])}</b></div>`).join('');jrOut.innerHTML=`<table><thead><tr>${H.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${R.map(r=>`<tr>${r.map((v,i)=>`<td>${typeof v==='number'&&/valor|custo|total/i.test(H[i])?e(money(v)):e(v)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${H.length||1}" class="muted">Nenhum resultado.</td></tr>`}</tbody></table>`;
 }
 function printProReport(){if(!currentData.headers.length)return;const w=open('','_blank');w.document.write(`<html><head><title>${e(currentData.title)}</title><style>body{font:11px Arial;margin:24px}h1{font-size:18px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:5px;text-align:left}th{background:#eee}.k{display:inline-block;margin-right:20px;font-weight:bold}</style></head><body><h1>JF MANUTENÇÕES AGRÍCOLAS — ${e(currentData.title)}</h1><p>${currentData.kpis.map(k=>`<span class="k">${e(k[0])}: ${e(k[1])}</span>`).join('')}</p><table><thead><tr>${currentData.headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${currentData.rows.map(r=>`<tr>${r.map(v=>`<td>${e(v)}</td>`).join('')}</tr>`).join('')}</tbody></table><script>print()<\/script></body></html>`);w.document.close()}
 function csvProReport(){if(!currentData.headers.length)return;const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',csv=[currentData.headers,...currentData.rows].map(r=>r.map(q).join(';')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='JF-'+currentData.title.replace(/[^a-z0-9]+/gi,'-')+'-'+dateOnly()+'.csv';a.click()}

 function expandGlobalSearch(){const g=document.getElementById('globalSearch');if(!g)return;g.placeholder='Busca global: OS, série, peça, código, serviço, técnico, fornecedor...'}
 function boot(){ensure();addStyle();enhanceAdmin();installMasterSubmit();enhanceProduct();enhanceOSSearch();buildReportCenter();expandGlobalSearch()}
 addEventListener('DOMContentLoaded',()=>setTimeout(boot,80));
 const oldRender=window.render;window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{enhanceAdmin();enhanceOSSearch();buildReportCenter();enhanceProduct()},0);return r};
})();