// JF Oficina v0.15.8 — inclusão rápida e lista compacta de materiais
(function(){
 const $=id=>document.getElementById(id), esc2=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 function ensurePicker(){
  const pane=$('tab-materials'),rows=$('materialRows'); if(!pane||!rows||$('matQuickPicker'))return;
  const box=document.createElement('div');box.id='matQuickPicker';box.className='matQuickPicker';
  box.innerHTML='<div class="matQuickFields"><label>Código<input id="mqCode" placeholder="JF, fabricante ou GTIN" autocomplete="off"></label><label>Descrição<input id="mqDesc" placeholder="Nome ou descrição" autocomplete="off"></label><label>Aplicação / marca<input id="mqApp" placeholder="Marca, aplicação, categoria" autocomplete="off"></label></div><div id="mqResults" class="matQuickResults hidden"></div>';
  rows.parentNode.insertBefore(box,rows);
  const f=[$('mqCode'),$('mqDesc'),$('mqApp')]; f.forEach(x=>{x.oninput=draw;x.onfocus=draw;x.onkeydown=e=>{if(e.key==='Escape')$('mqResults').classList.add('hidden')}});
 }
 function matches(p){const a=norm($('mqCode')?.value),b=norm($('mqDesc')?.value),c=norm($('mqApp')?.value);if(!a&&!b&&!c)return false;return (!a||norm([productCode(p),productMakerCode(p),p.codigo_barras,p.codigos_equivalentes].join(' ')).includes(a))&&(!b||norm(p.descricao).includes(b))&&(!c||norm([p.marca,p.aplicacao,p.categoria,p.localizacao].join(' ')).includes(c))}
 function draw(){const out=$('mqResults');if(!out)return;const rows=activeProducts().filter(p=>p.ativo!==false&&matches(p)).slice(0,30);if(!rows.length){out.innerHTML='<div class="matQuickResult muted">Nenhum produto encontrado.</div>';out.classList.remove('hidden');return}out.innerHTML=rows.map((p,i)=>`<button type="button" class="matQuickResult" data-i="${i}"><b>${esc2(productCode(p))} · ${esc2(p.descricao||'')}</b><span>${esc2([productMakerCode(p),p.marca,p.aplicacao,'Saldo '+num(p.estoque_atual)].filter(Boolean).join(' · '))}</span></button>`).join('');out.classList.remove('hidden');out.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>add(rows[Number(el.dataset.i)]))}
 function add(p){if(typeof work==='undefined'||!work)return;work.materiais.unshift({id:uid('P'),produto_id:p.id,quantidade:1,valor:num(p.valor_venda),desconto:0,acrescimo:0,origem:'Oficina'});['mqCode','mqDesc','mqApp'].forEach(id=>{if($(id))$(id).value=''});$('mqResults')?.classList.add('hidden');renderMaterials();renderFinance();dirty();$('mqCode')?.focus()}
 function compact(){
  ensurePicker();const rows=$('materialRows');if(!rows||typeof work==='undefined'||!work)return;
  rows.innerHTML=work.materiais.map((r,i)=>{const p=prodBy(r.produto_id);return `<div class="matCompact" data-i="${i}"><div class="matIdentity"><b>${esc2(productCode(p))} · ${esc2(p?.descricao||'Produto')}</b><span>${esc2([productMakerCode(p),p?.marca,p?.aplicacao].filter(Boolean).join(' · '))}</span></div><label>Qtd<input class="matQty" type="number" step=".01" value="${num(r.quantidade)||1}"></label><label>Valor<input class="matVal" type="number" step=".01" value="${num(r.valor)}"></label><label>Desc.<input class="matDisc" type="number" step=".01" value="${num(r.desconto)}"></label><label>Acrésc.<input class="matAdd" type="number" step=".01" value="${num(r.acrescimo)}"></label><label>Origem<select class="matOrigin"><option ${r.origem==='Oficina'?'selected':''}>Oficina</option><option ${r.origem==='Hilux'?'selected':''}>Hilux</option></select></label><button type="button" class="danger delMat">✕</button></div>`}).join('');
  bindRows('.matQty','quantidade',work.materiais);bindRows('.matVal','valor',work.materiais);bindRows('.matDisc','desconto',work.materiais);bindRows('.matAdd','acrescimo',work.materiais);bindRows('.matOrigin','origem',work.materiais,false);document.querySelectorAll('#materialRows .delMat').forEach((e,i)=>e.onclick=()=>{work.materiais.splice(i,1);compact();renderFinance();dirty()});
 }
 function install(){if(typeof renderMaterials!=='function')return;ensurePicker();if(!window.__jfOldRenderMaterials)window.__jfOldRenderMaterials=renderMaterials;renderMaterials=compact;const addBtn=$('addMaterial');if(addBtn)addBtn.style.display='none';compact()}
 addEventListener('DOMContentLoaded',()=>setTimeout(install,100));new MutationObserver(()=>{if($('tab-materials')&&!$('matQuickPicker'))install()}).observe(document.documentElement,{childList:true,subtree:true});
 const style=document.createElement('style');style.textContent=`.matQuickPicker{margin:8px 0 10px}.matQuickFields{display:grid;grid-template-columns:1fr 1.4fr 1.2fr;gap:7px}.matQuickFields label{font-size:11px;color:#5f6c77}.matQuickFields input{margin:2px 0 0}.matQuickResults{border:1px solid #dce2e8;border-radius:9px;max-height:260px;overflow:auto;margin-top:5px}.matQuickResult{display:flex;width:100%;border-radius:0;background:#fff;border-bottom:1px solid #edf0f2;text-align:left;padding:8px 10px;flex-direction:column;gap:2px}.matQuickResult span,.matIdentity span{font-size:11px;color:#65727f}.matCompact{display:grid;grid-template-columns:minmax(260px,2.5fr) 72px 92px 82px 82px 105px 42px;gap:6px;align-items:end;padding:7px 0;border-bottom:1px dashed #dfe5ea}.matCompact label{font-size:11px}.matCompact input,.matCompact select{padding:7px;margin:2px 0 0}.matIdentity{align-self:center;min-width:0}.matIdentity b,.matIdentity span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:700px){.matQuickFields{grid-template-columns:1fr 1fr}.matQuickFields label:last-child{grid-column:1/-1}.matCompact{grid-template-columns:1.15fr 1fr 1fr 42px;padding:6px 0}.matIdentity{grid-column:1/-1}.matCompact label:nth-of-type(1){grid-column:1}.matCompact label:nth-of-type(2){grid-column:2}.matCompact label:nth-of-type(3){grid-column:3}.matCompact label:nth-of-type(4){grid-column:1}.matCompact label:nth-of-type(5){grid-column:2/4}.matCompact .delMat{grid-column:4;grid-row:3}.matIdentity b{font-size:13px}}`;document.head.appendChild(style);
})();