// JF Oficina v0.20.14 — inclusão rápida de materiais com quantidade e edição
(function(){
 const $=id=>document.getElementById(id), esc2=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 function askQty(p,current=1){const raw=prompt(`Quantidade para adicionar\n\n${productCode(p)} · ${p?.descricao||'Produto'}`,String(current));if(raw===null)return null;const q=num(String(raw).replace(',','.'));if(!(q>0)){alert('Informe uma quantidade maior que zero.');return null}return q}
 function ensurePicker(){
  const pane=$('tab-materials'),rows=$('materialRows'); if(!pane||!rows)return;
  if($('matQuickPicker'))return;
  const box=document.createElement('div');box.id='matQuickPicker';box.className='matQuickPicker';
  box.innerHTML='<div class="matQuickFields"><label>Código<input id="mqCode" placeholder="JF, fabricante ou GTIN" autocomplete="off"></label><label>Descrição<input id="mqDesc" placeholder="Nome ou descrição" autocomplete="off"></label><label>Aplicação / marca<input id="mqApp" placeholder="Marca, aplicação, categoria" autocomplete="off"></label></div><div id="mqResults" class="matQuickResults hidden"></div>';
  rows.parentNode.insertBefore(box,rows);
  const f=[$('mqCode'),$('mqDesc'),$('mqApp')]; f.forEach(x=>{x.oninput=draw;x.onfocus=draw;x.onkeydown=e=>{if(e.key==='Escape')$('mqResults')?.classList.add('hidden')}});
  ensureEditDialog();
 }
 function matches(p){const a=norm($('mqCode')?.value),b=norm($('mqDesc')?.value),c=norm($('mqApp')?.value);if(!a&&!b&&!c)return false;return (!a||norm([productCode(p),productMakerCode(p),p.codigo_barras,p.codigos_equivalentes].join(' ')).includes(a))&&(!b||norm(p.descricao).includes(b))&&(!c||norm([p.marca,p.aplicacao,p.categoria,p.localizacao].join(' ')).includes(c))}
 function qtyInDoc(id){return (work?.materiais||[]).filter(x=>String(x.produto_id)===String(id)).reduce((a,x)=>a+num(x.quantidade),0)}
 function draw(){const out=$('mqResults');if(!out)return;const rows=activeProducts().filter(p=>p.ativo!==false&&matches(p)).slice(0,30);if(!rows.length){out.innerHTML='<div class="matQuickResult muted">Nenhum produto encontrado.</div>';out.classList.remove('hidden');return}out.innerHTML=rows.map((p,i)=>{const inDoc=qtyInDoc(p.id);return `<div class="matQuickResult"><div class="matQuickResultInfo"><b>${esc2(productCode(p))} · ${esc2(p.descricao||'')}</b><span>${esc2([productMakerCode(p),p.marca,p.aplicacao,'Saldo '+num(p.estoque_atual),inDoc>0?'Neste documento '+inDoc:''].filter(Boolean).join(' · '))}</span></div><button type="button" class="matQuickAdd" data-i="${i}">Adicionar</button></div>`}).join('');out.classList.remove('hidden');out.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>add(rows[Number(el.dataset.i)]))}
 function add(p){if(typeof work==='undefined'||!work)return;const qty=askQty(p,1);if(qty===null)return;const existing=work.materiais.find(x=>String(x.produto_id)===String(p.id)&&String(x.origem||'Oficina')==='Oficina');if(existing)existing.quantidade=num(existing.quantidade)+qty;else work.materiais.unshift({id:uid('P'),produto_id:p.id,quantidade:qty,valor:num(p.valor_venda),desconto:0,acrescimo:0,origem:'Oficina'});compact();renderFinance();dirty();draw()}
 function ensureEditDialog(){if($('matItemEditDlg'))return;const d=document.createElement('dialog');d.id='matItemEditDlg';d.className='osmodal matItemEditDlg';d.innerHTML=`<form method="dialog"><div class="dhead"><div><b id="matEditTitle">Editar material</b><div id="matEditSub" class="small muted"></div></div><button type="button" id="matEditClose">✕</button></div><div class="dbody"><div class="grid2"><label>Quantidade<input id="matEditQty" type="number" step=".01" min=".01"></label><label>Valor unitário<input id="matEditVal" type="number" step=".01"></label><label>Desconto<input id="matEditDisc" type="number" step=".01"></label><label>Acréscimo<input id="matEditAdd" type="number" step=".01"></label><label>Origem<select id="matEditOrigin"><option>Oficina</option><option>Hilux</option></select></label></div></div><div class="dfoot"><button type="button" id="matEditCancel">Cancelar</button><button type="button" class="primary" id="matEditSave">Salvar alterações</button></div></form>`;document.body.appendChild(d);$('matEditClose').onclick=$('matEditCancel').onclick=()=>d.close();$('matEditSave').onclick=()=>{const i=Number(d.dataset.i),r=work?.materiais?.[i];if(!r)return d.close();const q=num($('matEditQty').value);if(!(q>0)){alert('A quantidade deve ser maior que zero.');return}r.quantidade=q;r.valor=num($('matEditVal').value);r.desconto=num($('matEditDisc').value);r.acrescimo=num($('matEditAdd').value);r.origem=$('matEditOrigin').value||'Oficina';d.close();compact();renderFinance();dirty();draw()}}
 function editMaterial(i){const r=work?.materiais?.[i];if(!r)return;const p=prodBy(r.produto_id);ensureEditDialog();const d=$('matItemEditDlg');d.dataset.i=String(i);$('matEditTitle').textContent=`Editar ${productCode(p)||'material'}`;$('matEditSub').textContent=p?.descricao||'';$('matEditQty').value=num(r.quantidade)||1;$('matEditVal').value=num(r.valor);$('matEditDisc').value=num(r.desconto);$('matEditAdd').value=num(r.acrescimo);$('matEditOrigin').value=r.origem||'Oficina';d.showModal();setTimeout(()=>$('matEditQty')?.select(),30)}
 function compact(){
  ensurePicker();const rows=$('materialRows');if(!rows||typeof work==='undefined'||!work)return;
  rows.innerHTML=work.materiais.map((r,i)=>{const p=prodBy(r.produto_id);return `<div class="matCompact" data-i="${i}"><button type="button" class="matIdentity" data-edit-mat="${i}" title="Clique para editar este item"><b>${esc2(productCode(p))} · ${esc2(p?.descricao||'Produto')}</b><span>${esc2([productMakerCode(p),p?.marca,p?.aplicacao].filter(Boolean).join(' · '))}</span></button><label>Qtd<input class="matQty" type="number" step=".01" value="${num(r.quantidade)||1}"></label><label>Valor<input class="matVal" type="number" step=".01" value="${num(r.valor)}"></label><label>Desc.<input class="matDisc" type="number" step=".01" value="${num(r.desconto)}"></label><label>Acrésc.<input class="matAdd" type="number" step=".01" value="${num(r.acrescimo)}"></label><label>Origem<select class="matOrigin"><option ${r.origem==='Oficina'?'selected':''}>Oficina</option><option ${r.origem==='Hilux'?'selected':''}>Hilux</option></select></label><button type="button" class="danger delMat">✕</button></div>`}).join('');
  bindRows('.matQty','quantidade',work.materiais);bindRows('.matVal','valor',work.materiais);bindRows('.matDisc','desconto',work.materiais);bindRows('.matAdd','acrescimo',work.materiais);bindRows('.matOrigin','origem',work.materiais,false);document.querySelectorAll('#materialRows [data-edit-mat]').forEach(e=>e.onclick=()=>editMaterial(Number(e.dataset.editMat)));document.querySelectorAll('#materialRows .delMat').forEach((e,i)=>e.onclick=()=>{work.materiais.splice(i,1);compact();renderFinance();dirty();draw()});
 }
 function install(){if(typeof renderMaterials!=='function')return;if(!window.__jfOldRenderMaterials)window.__jfOldRenderMaterials=renderMaterials;renderMaterials=compact;const addBtn=$('addMaterial');if(addBtn)addBtn.style.display='none';ensurePicker();compact()}
 function heal(){const pane=$('tab-materials');if(!pane)return;const addBtn=$('addMaterial');if(addBtn)addBtn.style.display='none';if(!$('matQuickPicker'))ensurePicker()}
 addEventListener('DOMContentLoaded',()=>setTimeout(install,100));
 new MutationObserver(()=>{if($('tab-materials'))setTimeout(heal,0)}).observe(document.documentElement,{childList:true,subtree:true});
 const style=document.createElement('style');style.textContent=`.matQuickPicker{margin:8px 0 10px}.matQuickFields{display:grid;grid-template-columns:1fr 1.4fr 1.2fr;gap:7px}.matQuickFields label{font-size:11px;color:#5f6c77}.matQuickFields input{margin:2px 0 0}.matQuickResults{border:1px solid #dce2e8;border-radius:9px;max-height:300px;overflow:auto;margin-top:5px}.matQuickResult{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;width:100%;background:#fff;border-bottom:1px solid #edf0f2;padding:8px 10px}.matQuickResultInfo{min-width:0}.matQuickResultInfo b,.matQuickResultInfo span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.matQuickResultInfo span,.matIdentity span{font-size:11px;color:#65727f}.matQuickAdd{white-space:nowrap}.matCompact{display:grid;grid-template-columns:minmax(260px,2.5fr) 72px 92px 82px 82px 105px 42px;gap:6px;align-items:end;padding:7px 0;border-bottom:1px dashed #dfe5ea}.matCompact label{font-size:11px}.matCompact input,.matCompact select{padding:7px;margin:2px 0 0}.matIdentity{align-self:center;min-width:0;background:transparent;border:0;text-align:left;padding:4px 2px;cursor:pointer;color:inherit}.matIdentity:hover{background:#f3f7f5;border-radius:7px}.matIdentity b,.matIdentity span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.matItemEditDlg{width:min(620px,94vw)}@media(max-width:700px){.matQuickFields{grid-template-columns:1fr 1fr}.matQuickFields label:last-child{grid-column:1/-1}.matCompact{grid-template-columns:1.15fr 1fr 1fr 42px;padding:6px 0}.matIdentity{grid-column:1/-1}.matCompact label:nth-of-type(1){grid-column:1}.matCompact label:nth-of-type(2){grid-column:2}.matCompact label:nth-of-type(3){grid-column:3}.matCompact label:nth-of-type(4){grid-column:1}.matCompact label:nth-of-type(5){grid-column:2/4}.matCompact .delMat{grid-column:4;grid-row:3}.matIdentity b{font-size:13px}.matQuickResult{grid-template-columns:1fr auto}}`;document.head.appendChild(style);
})();