// JF Oficina v0.15.18 — QR de pagamento configurável nas configurações
(function(){
 const $=id=>document.getElementById(id);
 function profile(){try{return window.JFCompanyProfile?.profile?.()||null}catch(e){return null}}
 function installSettings(){const box=$('companyPdfSettings');if(!box||$('cpPaymentQR'))return;const payTitle=[...box.querySelectorAll('h3')].find(x=>/Dados para pagamento/i.test(x.textContent));if(!payTitle)return;const area=document.createElement('div');area.className='section';area.style.margin='10px 0';area.innerHTML='<b>QR de pagamento</b><p class="small muted">Envie a imagem do QR que será exibida no lado direito dos dados de pagamento da OS e do orçamento.</p><div class="toolbar"><input id="cpPaymentQR" type="file" accept="image/*"><button type="button" id="cpRemovePaymentQR">Remover QR</button><img id="cpPaymentQRPreview" style="width:170px;max-height:170px;object-fit:contain;border:1px solid #ccd4cc;background:#fff;padding:4px"></div>';payTitle.insertAdjacentElement('afterend',area);refresh();$('cpPaymentQR').onchange=e=>load(e.target.files?.[0]);$('cpRemovePaymentQR').onclick=async()=>{const p=profile();if(!p)return;p.payment_qr='';await saveDB();refresh()}}
 function refresh(){const p=profile(),img=$('cpPaymentQRPreview');if(!img||!p)return;img.src=p.payment_qr||'';img.style.display=p.payment_qr?'block':'none'}
 function load(file){if(!file)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=async()=>{const max=900,sc=Math.min(1,max/im.width,max/im.height),c=document.createElement('canvas');c.width=Math.round(im.width*sc);c.height=Math.round(im.height*sc);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const p=profile();if(!p)return;p.payment_qr=c.toDataURL('image/jpeg',.92);await saveDB();refresh()};im.src=r.result};r.readAsDataURL(file)}
 function install(){installSettings()}
 addEventListener('DOMContentLoaded',()=>setTimeout(install,400));new MutationObserver(()=>setTimeout(install,0)).observe(document.documentElement,{childList:true,subtree:true});
})();