// JF Oficina v0.17.0 — Venda Direta / Venda Rápida somente de peças
(function(){
 const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const N=v=>Number(String(v??0).replace(',','.'))||0;
 const M=v=>N(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 function sales(){S.custom=S.custom||{};S.custom.quickSales=S.custom.quickSales||[];return S.custom.quickSales}
 function addUI(){
  const main=document.querySelector('main');if(!main||document.getElementById('quickSales'))return;
  const nav=document.querySelector('nav')||document.querySelector('.nav');
  if(nav){const b=document.createElement('button');b.type='button';b.textContent='Venda rápida';b.dataset.view='quickSales';b.onclick=()=>show();nav.appendChild(b)}
  const sec=document.createElement('section');sec.id='quickSales';sec.className='view';sec.innerHTML=`<h2>Venda Direta / Venda Rápida</h2><div class="toolbar"><button class="primary" id="qsNew">+ Nova venda</button><input id="qsFind" placeholder="Buscar venda, cliente ou peça"></div><div id="qsEditor" class="section hidden"></div><div class="tablewrap"><table><thead><tr><th>Venda</th><th>Data</th><th>Cliente</th><th>Itens</th><th>Total</th></tr></thead><tbody id="qsRows"></tbody></table></div>`;main.appendChild(sec);
  document.getElementById('qsNew').onclick=()=>edit();document.getElementById('qsFind').oninput=render;
  render();
 }
 function show(){document.querySelectorAll('.view').forEach(x=>x.classList.remove('on','active'));const s=document.getElementById('quickSales');s.classList.add('on');s.classList.add('active');render()}
 function nextNo(){return Math.max(0,...sales().map(x=>N(x.numero)))+1}
 function clientOpts(sel=''){return `<option value="">Consumidor não identificado</option>`+clients().map(c=>`<option value="${E(c.id)}" ${String(c.id)===String(sel)?'selected':''}>${E(c.nome||'')}</option>`).join('')}
 function productOpts(sel=''){return `<option value="">Selecione...</option>`+activeProducts().filter(p=>p.ativo!==false).map(p=>`<option value="${E(p.id)}" ${String(p.id)===String(sel)?'selected':''}>[${E(productCode(p))}] ${E(p.descricao||'')}</option>`).join('')}
 function edit(id=''){
  const old=sales().find(x=>String(x.id)===String(id));window.__qs=old?JSON.parse(JSON.stringify(old)):{id:'',numero:nextNo(),data:new Date().toISOString(),cliente_id:'',itens:[],desconto:0,acrescimo:0,pagamento:'Dinheiro',observacao:''};drawEditor();show()
 }
 function total(){return Math.max(0,(window.__qs?.itens||[]).reduce((a,x)=>a+N(x.quantidade)*N(x.valor)-N(x.desconto)+N(x.acrescimo),0)+N(window.__qs?.acrescimo)-N(window.__qs?.desconto))}
 function drawEditor(){const q=window.__qs,box=document.getElementById('qsEditor');box.classList.remove('hidden');box.innerHTML=`<div class="toolbar"><b>Venda ${E(q.numero)}</b><span class="muted">Somente peças / materiais</span></div><div class="grid3"><label>Cliente (opcional)<select id="qsClient">${clientOpts(q.cliente_id)}</select></label><label>Pagamento<select id="qsPay"><option>Dinheiro</option><option>PIX</option><option>Cartão</option><option>À prazo</option><option>Outro</option></select></label><label>Observação<input id="qsObs" value="${E(q.observacao||'')}"></label></div><h3>Peças</h3><div class="grid3"><label>Código<input id="qsCode" placeholder="Código JF / fabricante"></label><label>Descrição<input id="qsDesc" placeholder="Descrição"></label><label>&nbsp;<button type="button" id="qsAdd">+ Adicionar peça</button></label></div><div id="qsItems"></div><div class="grid3"><label>Desconto geral<input id="qsDisc" type="number" step=".01" value="${N(q.desconto)}"></label><label>Acréscimo geral<input id="qsAddG" type="number" step=".01" value="${N(q.acrescimo)}"></label><div><b>Total</b><div id="qsTotal" style="font-size:20px">${M(total())}</div></div></div><div class="toolbar"><button type="button" class="primary" id="qsSave">Finalizar venda e baixar estoque</button><button type="button" id="qsCancel">Cancelar</button></div>`;
  document.getElementById('qsPay').value=q.pagamento||'Dinheiro';document.getElementById('qsClient').onchange=e=>q.cliente_id=e.target.value;document.getElementById('qsPay').onchange=e=>q.pagamento=e.target.value;document.getElementById('qsObs').oninput=e=>q.observacao=e.target.value;document.getElementById('qsDisc').oninput=e=>{q.desconto=N(e.target.value);refreshItems()};document.getElementById('qsAddG').oninput=e=>{q.acrescimo=N(e.target.value);refreshItems()};document.getElementById('qsAdd').onclick=addFromSearch;document.getElementById('qsSave').onclick=saveSale;document.getElementById('qsCancel').onclick=()=>{box.classList.add('hidden');window.__qs=null};refreshItems()
 }
 function findProduct(){const c=(document.getElementById('qsCode').value||'').trim().toLowerCase(),d=(document.getElementById('qsDesc').value||'').trim().toLowerCase();return activeProducts().find(p=>(c&&[productCode(p),productMakerCode(p),p.codigo_barras].some(x=>String(x||'').toLowerCase().includes(c)))||(d&&String(p.descricao||'').toLowerCase().includes(d)))}
 function addFromSearch(){const p=findProduct();if(!p){alert('Peça não encontrada. Informe código ou descrição.');return}const ex=window.__qs.itens.find(x=>String(x.produto_id)===String(p.id));if(ex)ex.quantidade=N(ex.quantidade)+1;else window.__qs.itens.unshift({produto_id:p.id,quantidade:1,valor:N(p.valor_venda),desconto:0,acrescimo:0,origem:'Oficina'});document.getElementById('qsCode').value='';document.getElementById('qsDesc').value='';refreshItems()}
 function refreshItems(){const q=window.__qs,host=document.getElementById('qsItems');host.innerHTML=q.itens.map((x,i)=>{const p=prodBy(x.produto_id);return `<div class="itemrow" data-i="${i}"><label>Peça<input readonly value="[${E(productCode(p))}] ${E(p?.descricao||'')}"></label><label>Qtd<input class="qQty" type="number" step=".01" value="${N(x.quantidade)}"></label><label>Valor<input class="qVal" type="number" step=".01" value="${N(x.valor)}"></label><label>Desc.<input class="qDisc" type="number" step=".01" value="${N(x.desconto)}"></label><label>Acrésc.<input class="qAdd" type="number" step=".01" value="${N(x.acrescimo)}"></label><label>Origem<select class="qOrig"><option>Oficina</option><option>Hilux</option></select></label><button type="button" class="danger qDel">✕</button></div>`}).join('');
  ['qQty','qVal','qDisc','qAdd'].forEach((cl)=>document.querySelectorAll('.'+cl).forEach((el,i)=>el.oninput=()=>{const key={qQty:'quantidade',qVal:'valor',qDisc:'desconto',qAdd:'acrescimo'}[cl];q.itens[i][key]=N(el.value);document.getElementById('qsTotal').textContent=M(total())}));document.querySelectorAll('.qOrig').forEach((el,i)=>{el.value=q.itens[i].origem||'Oficina';el.onchange=()=>q.itens[i].origem=el.value});document.querySelectorAll('.qDel').forEach((el,i)=>el.onclick=()=>{q.itens.splice(i,1);refreshItems()});document.getElementById('qsTotal').textContent=M(total())
 }
 async function saveSale(){const q=window.__qs;if(!q.itens.length){alert('Adicione pelo menos uma peça.');return}for(const x of q.itens){const p=prodBy(x.produto_id);if(!p)continue;const qty=N(x.quantidade);p.estoque_atual=N(p.estoque_atual)-qty;S.custom.stockMoves=S.custom.stockMoves||[];S.custom.stockMoves.unshift({id:uid('MV'),produto_id:p.id,quantidade:-qty,tipo:'Venda direta',origem:x.origem||'Oficina',ref:'VD '+q.numero,at:new Date().toISOString()})}q.total=total();q.finalizada=true;q.id=q.id||uid('VD');sales().unshift(JSON.parse(JSON.stringify(q)));log('venda_direta',q.id,'Venda direta finalizada',`Venda ${q.numero} · ${M(q.total)}`);await saveDB();window.__qs=null;document.getElementById('qsEditor').classList.add('hidden');render();if(typeof window.pushCentralSync==='function')window.pushCentralSync().catch(()=>{});alert('Venda finalizada e estoque baixado.')}
 function render(){const host=document.getElementById('qsRows');if(!host)return;const q=(document.getElementById('qsFind')?.value||'').toLowerCase();host.innerHTML=sales().filter(s=>[s.numero,clientName(s.cliente_id),...(s.itens||[]).map(x=>prodBy(x.produto_id)?.descricao)].join(' ').toLowerCase().includes(q)).sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(s=>`<tr><td><b>VD ${E(s.numero)}</b></td><td>${new Date(s.data).toLocaleString('pt-BR')}</td><td>${E(s.cliente_id?clientName(s.cliente_id):'Consumidor não identificado')}</td><td>${(s.itens||[]).length}</td><td><b>${M(s.total)}</b></td></tr>`).join('')}
 addEventListener('DOMContentLoaded',()=>setTimeout(addUI,900));setTimeout(addUI,1800);window.JFQuickSales={show,edit,render};
})();