// JF Oficina v0.20.14 — Venda Direta / Venda Rápida somente de peças
(function(){
 const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const N=v=>Number(String(v??0).replace(',','.'))||0;
 const M=v=>N(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 function sales(){S.custom=S.custom||{};S.custom.quickSales=S.custom.quickSales||[];return S.custom.quickSales}
 function askQty(p,current=1){const raw=prompt(`Quantidade para adicionar\n\n${productCode(p)} · ${p?.descricao||'Produto'}`,String(current));if(raw===null)return null;const q=N(raw);if(!(q>0)){alert('Informe uma quantidade maior que zero.');return null}return q}
 function addUI(){
  const main=document.querySelector('main');if(!main||document.getElementById('quickSales'))return;
  const nav=document.querySelector('nav')||document.querySelector('.nav');
  if(nav){const b=document.createElement('button');b.type='button';b.textContent='Venda rápida';b.dataset.view='quickSales';b.onclick=()=>show();nav.appendChild(b)}
  const sec=document.createElement('section');sec.id='quickSales';sec.className='view';sec.innerHTML=`<h2>Venda Direta / Venda Rápida</h2><div class="toolbar"><button class="primary" id="qsNew">+ Nova venda</button><input id="qsFind" placeholder="Buscar venda, cliente ou peça"></div><div id="qsEditor" class="section hidden"></div><div class="tablewrap"><table><thead><tr><th>Venda</th><th>Data</th><th>Cliente</th><th>Itens</th><th>Total</th></tr></thead><tbody id="qsRows"></tbody></table></div>`;main.appendChild(sec);
  document.getElementById('qsNew').onclick=()=>edit();document.getElementById('qsFind').oninput=render;
  ensureEditDialog();render();
 }
 function show(){document.querySelectorAll('.view').forEach(x=>x.classList.remove('on','active'));const s=document.getElementById('quickSales');s.classList.add('on');s.classList.add('active');render()}
 function nextNo(){return Math.max(0,...sales().map(x=>N(x.numero)))+1}
 function clientOpts(sel=''){return `<option value="">Consumidor não identificado</option>`+clients().map(c=>`<option value="${E(c.id)}" ${String(c.id)===String(sel)?'selected':''}>${E(c.nome||'')}</option>`).join('')}
 function edit(id=''){
  const old=sales().find(x=>String(x.id)===String(id));window.__qs=old?JSON.parse(JSON.stringify(old)):{id:'',numero:nextNo(),data:new Date().toISOString(),cliente_id:'',itens:[],desconto:0,acrescimo:0,pagamento:'Dinheiro',observacao:''};drawEditor();show()
 }
 function total(){return Math.max(0,(window.__qs?.itens||[]).reduce((a,x)=>a+N(x.quantidade)*N(x.valor)-N(x.desconto)+N(x.acrescimo),0)+N(window.__qs?.acrescimo)-N(window.__qs?.desconto))}
 function drawEditor(){const q=window.__qs,box=document.getElementById('qsEditor');box.classList.remove('hidden');box.innerHTML=`<div class="toolbar"><b>Venda ${E(q.numero)}</b><span class="muted">Somente peças / materiais</span></div><div class="grid3"><label>Cliente (opcional)<select id="qsClient">${clientOpts(q.cliente_id)}</select></label><label>Pagamento<select id="qsPay"><option>Dinheiro</option><option>PIX</option><option>Cartão</option><option>À prazo</option><option>Outro</option></select></label><label>Observação<input id="qsObs" value="${E(q.observacao||'')}"></label></div><h3>Peças</h3><div class="grid3"><label>Código<input id="qsCode" placeholder="Código JF / fabricante" autocomplete="off"></label><label>Descrição<input id="qsDesc" placeholder="Descrição" autocomplete="off"></label><label>Aplicação / marca<input id="qsExtra" placeholder="Marca, aplicação ou categoria" autocomplete="off"></label></div><div id="qsProductResults" class="qsProductResults hidden"></div><div id="qsItems"></div><div class="grid3"><label>Desconto geral<input id="qsDisc" type="number" step=".01" value="${N(q.desconto)}"></label><label>Acréscimo geral<input id="qsAddG" type="number" step=".01" value="${N(q.acrescimo)}"></label><div><b>Total</b><div id="qsTotal" style="font-size:20px">${M(total())}</div></div></div><div class="toolbar"><button type="button" class="primary" id="qsSave">Finalizar venda e baixar estoque</button><button type="button" id="qsCancel">Cancelar</button></div>`;
  document.getElementById('qsPay').value=q.pagamento||'Dinheiro';document.getElementById('qsClient').onchange=e=>q.cliente_id=e.target.value;document.getElementById('qsPay').onchange=e=>q.pagamento=e.target.value;document.getElementById('qsObs').oninput=e=>q.observacao=e.target.value;document.getElementById('qsDisc').oninput=e=>{q.desconto=N(e.target.value);refreshItems()};document.getElementById('qsAddG').oninput=e=>{q.acrescimo=N(e.target.value);refreshItems()};['qsCode','qsDesc','qsExtra'].forEach(id=>{const el=document.getElementById(id);el.oninput=drawProductResults;el.onfocus=drawProductResults;el.onkeydown=e=>{if(e.key==='Escape')document.getElementById('qsProductResults')?.classList.add('hidden')}});document.getElementById('qsSave').onclick=saveSale;document.getElementById('qsCancel').onclick=()=>{box.classList.add('hidden');window.__qs=null};refreshItems()
 }
 function productMatches(p){const c=norm(document.getElementById('qsCode')?.value),d=norm(document.getElementById('qsDesc')?.value),x=norm(document.getElementById('qsExtra')?.value);if(!c&&!d&&!x)return false;const pc=norm([productCode(p),productMakerCode(p),p.codigo_barras,p.codigos_equivalentes].join(' ')),pd=norm(p.descricao),px=norm([p.marca,p.aplicacao,p.categoria,p.localizacao].join(' '));return (!c||pc.includes(c))&&(!d||pd.includes(d))&&(!x||px.includes(x))}
 function qtyInSale(id){return (window.__qs?.itens||[]).filter(x=>String(x.produto_id)===String(id)).reduce((a,x)=>a+N(x.quantidade),0)}
 function drawProductResults(){const host=document.getElementById('qsProductResults');if(!host)return;const active=[document.getElementById('qsCode')?.value,document.getElementById('qsDesc')?.value,document.getElementById('qsExtra')?.value].some(v=>String(v||'').trim());if(!active){host.classList.add('hidden');host.innerHTML='';return}const rows=activeProducts().filter(p=>p.ativo!==false&&productMatches(p)).slice(0,40);host.innerHTML=rows.length?rows.map((p,i)=>{const q=qtyInSale(p.id);return `<div class="qsProductResult"><div class="qsProductInfo"><b>${E(productCode(p))} · ${E(p.descricao||'')}</b><span>${E([productMakerCode(p),p.marca,p.aplicacao,'Saldo '+N(p.estoque_atual),q>0?'Na venda '+q:''].filter(Boolean).join(' · '))}</span></div><button type="button" data-qs-add="${i}">Adicionar</button></div>`}).join(''):'<div class="qsProductResult muted">Nenhum produto encontrado.</div>';host.classList.remove('hidden');host.querySelectorAll('[data-qs-add]').forEach(btn=>btn.onclick=()=>addProduct(rows[Number(btn.dataset.qsAdd)]))}
 function addProduct(p){if(!p||!window.__qs)return;const qty=askQty(p,1);if(qty===null)return;const ex=window.__qs.itens.find(x=>String(x.produto_id)===String(p.id)&&(x.origem||'Oficina')==='Oficina');if(ex)ex.quantidade=N(ex.quantidade)+qty;else window.__qs.itens.unshift({produto_id:p.id,quantidade:qty,valor:N(p.valor_venda),desconto:0,acrescimo:0,origem:'Oficina'});refreshItems();drawProductResults()}
 function ensureEditDialog(){if(document.getElementById('qsItemEditDlg'))return;const d=document.createElement('dialog');d.id='qsItemEditDlg';d.className='osmodal qsItemEditDlg';d.innerHTML=`<form method="dialog"><div class="dhead"><div><b id="qsEditTitle">Editar item</b><div id="qsEditSub" class="small muted"></div></div><button type="button" id="qsEditClose">✕</button></div><div class="dbody"><div class="grid2"><label>Quantidade<input id="qsEditQty" type="number" step=".01" min=".01"></label><label>Valor unitário<input id="qsEditVal" type="number" step=".01"></label><label>Desconto<input id="qsEditDisc" type="number" step=".01"></label><label>Acréscimo<input id="qsEditAdd" type="number" step=".01"></label><label>Origem<select id="qsEditOrigin"><option>Oficina</option><option>Hilux</option></select></label></div></div><div class="dfoot"><button type="button" id="qsEditCancel">Cancelar</button><button type="button" class="primary" id="qsEditSave">Salvar alterações</button></div></form>`;document.body.appendChild(d);document.getElementById('qsEditClose').onclick=document.getElementById('qsEditCancel').onclick=()=>d.close();document.getElementById('qsEditSave').onclick=()=>{const i=Number(d.dataset.i),r=window.__qs?.itens?.[i];if(!r)return d.close();const q=N(document.getElementById('qsEditQty').value);if(!(q>0)){alert('A quantidade deve ser maior que zero.');return}r.quantidade=q;r.valor=N(document.getElementById('qsEditVal').value);r.desconto=N(document.getElementById('qsEditDisc').value);r.acrescimo=N(document.getElementById('qsEditAdd').value);r.origem=document.getElementById('qsEditOrigin').value||'Oficina';d.close();refreshItems();drawProductResults()}}
 function editItem(i){const r=window.__qs?.itens?.[i];if(!r)return;ensureEditDialog();const p=prodBy(r.produto_id),d=document.getElementById('qsItemEditDlg');d.dataset.i=String(i);document.getElementById('qsEditTitle').textContent=`Editar ${productCode(p)||'item'}`;document.getElementById('qsEditSub').textContent=p?.descricao||'';document.getElementById('qsEditQty').value=N(r.quantidade)||1;document.getElementById('qsEditVal').value=N(r.valor);document.getElementById('qsEditDisc').value=N(r.desconto);document.getElementById('qsEditAdd').value=N(r.acrescimo);document.getElementById('qsEditOrigin').value=r.origem||'Oficina';d.showModal();setTimeout(()=>document.getElementById('qsEditQty')?.select(),30)}
 function refreshItems(){const q=window.__qs,host=document.getElementById('qsItems');host.innerHTML=q.itens.map((x,i)=>{const p=prodBy(x.produto_id);return `<div class="itemrow qsItemRow" data-i="${i}"><button type="button" class="qsItemIdentity" data-qs-edit="${i}" title="Clique para editar este item"><b>[${E(productCode(p))}] ${E(p?.descricao||'')}</b><span>${E([productMakerCode(p),p?.marca,p?.aplicacao].filter(Boolean).join(' · '))}</span></button><label>Qtd<input class="qQty" type="number" step=".01" value="${N(x.quantidade)}"></label><label>Valor<input class="qVal" type="number" step=".01" value="${N(x.valor)}"></label><label>Desc.<input class="qDisc" type="number" step=".01" value="${N(x.desconto)}"></label><label>Acrésc.<input class="qAdd" type="number" step=".01" value="${N(x.acrescimo)}"></label><label>Origem<select class="qOrig"><option>Oficina</option><option>Hilux</option></select></label><button type="button" class="danger qDel">✕</button></div>`}).join('');
  ['qQty','qVal','qDisc','qAdd'].forEach((cl)=>document.querySelectorAll('#qsItems .'+cl).forEach((el,i)=>el.oninput=()=>{const key={qQty:'quantidade',qVal:'valor',qDisc:'desconto',qAdd:'acrescimo'}[cl];q.itens[i][key]=N(el.value);document.getElementById('qsTotal').textContent=M(total())}));document.querySelectorAll('#qsItems .qOrig').forEach((el,i)=>{el.value=q.itens[i].origem||'Oficina';el.onchange=()=>q.itens[i].origem=el.value});document.querySelectorAll('#qsItems [data-qs-edit]').forEach(el=>el.onclick=()=>editItem(Number(el.dataset.qsEdit)));document.querySelectorAll('#qsItems .qDel').forEach((el,i)=>el.onclick=()=>{q.itens.splice(i,1);refreshItems();drawProductResults()});document.getElementById('qsTotal').textContent=M(total())
 }
 async function saveSale(){const q=window.__qs;if(!q.itens.length){alert('Adicione pelo menos uma peça.');return}for(const x of q.itens){const p=prodBy(x.produto_id);if(!p)continue;const qty=N(x.quantidade);p.estoque_atual=N(p.estoque_atual)-qty;S.custom.stockMoves=S.custom.stockMoves||[];S.custom.stockMoves.unshift({id:uid('MV'),produto_id:p.id,quantidade:-qty,tipo:'Venda direta',origem:x.origem||'Oficina',ref:'VD '+q.numero,at:new Date().toISOString()})}q.total=total();q.finalizada=true;q.id=q.id||uid('VD');sales().unshift(JSON.parse(JSON.stringify(q)));log('venda_direta',q.id,'Venda direta finalizada',`Venda ${q.numero} · ${M(q.total)}`);await saveDB();window.__qs=null;document.getElementById('qsEditor').classList.add('hidden');render();if(typeof window.pushCentralSync==='function')window.pushCentralSync().catch(()=>{});alert('Venda finalizada e estoque baixado.')}
 function render(){const host=document.getElementById('qsRows');if(!host)return;const q=(document.getElementById('qsFind')?.value||'').toLowerCase();host.innerHTML=sales().filter(s=>[s.numero,clientName(s.cliente_id),...(s.itens||[]).map(x=>prodBy(x.produto_id)?.descricao)].join(' ').toLowerCase().includes(q)).sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(s=>`<tr><td><b>VD ${E(s.numero)}</b></td><td>${new Date(s.data).toLocaleString('pt-BR')}</td><td>${E(s.cliente_id?clientName(s.cliente_id):'Consumidor não identificado')}</td><td>${(s.itens||[]).length}</td><td><b>${M(s.total)}</b></td></tr>`).join('')}
 const style=document.createElement('style');style.textContent=`.qsProductResults{border:1px solid #dce2e8;border-radius:9px;max-height:300px;overflow:auto;margin:6px 0 10px}.qsProductResult{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:9px 10px;border-bottom:1px solid #edf0f2;background:#fff}.qsProductInfo{min-width:0}.qsProductInfo b,.qsProductInfo span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.qsProductInfo span,.qsItemIdentity span{font-size:11px;color:#65727f}.qsItemIdentity{background:transparent;border:0;text-align:left;padding:4px 2px;cursor:pointer;color:inherit;min-width:0}.qsItemIdentity:hover{background:#f3f7f5;border-radius:7px}.qsItemIdentity b,.qsItemIdentity span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.qsItemEditDlg{width:min(620px,94vw)}@media(max-width:700px){.qsProductResult{grid-template-columns:1fr auto}.qsItemIdentity{grid-column:1/-1}}`;document.head.appendChild(style);
 addEventListener('DOMContentLoaded',()=>setTimeout(addUI,900));setTimeout(addUI,1800);window.JFQuickSales={show,edit,render};
})();