// JF Oficina v0.20.29 — inclusão rápida e lista compacta de serviços compatível com múltiplos técnicos
(function(){
 const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 function catalog(){return (S.servicos_catalogo||[]).filter(s=>s.ativo!==false)}
 function ensurePicker(){
  const pane=$('tab-services'),rows=$('serviceRows');if(!pane||!rows||$('srvQuickPicker'))return;
  const box=document.createElement('div');box.id='srvQuickPicker';box.className='srvQuickPicker';
  box.innerHTML='<div class="srvQuickFields"><label>Código<input id="sqCode" placeholder="Código do serviço" autocomplete="off"></label><label>Descrição<input id="sqDesc" placeholder="Descrição do serviço" autocomplete="off"></label><label>Categoria / palavra-chave<input id="sqCat" placeholder="Categoria ou palavra-chave" autocomplete="off"></label></div><div id="sqResults" class="srvQuickResults hidden"></div>';
  rows.parentNode.insertBefore(box,rows);
  [$('sqCode'),$('sqDesc'),$('sqCat')].forEach(x=>{x.oninput=draw;x.onfocus=draw;x.onkeydown=e=>{if(e.key==='Escape')$('sqResults')?.classList.add('hidden')}});
 }
 function matches(s){const a=norm($('sqCode')?.value),b=norm($('sqDesc')?.value),c=norm($('sqCat')?.value);if(!a&&!b&&!c)return false;return (!a||norm(s.codigo).includes(a))&&(!b||norm(s.descricao).includes(b))&&(!c||norm([s.categoria,s.palavras_chave].join(' ')).includes(c))}
 function draw(){const out=$('sqResults');if(!out)return;const list=catalog().filter(matches).slice(0,30);if(!list.length){out.innerHTML='<div class="srvQuickResult muted">Nenhum serviço encontrado.</div>';out.classList.remove('hidden');return}out.innerHTML=list.map((s,i)=>`<button type="button" class="srvQuickResult" data-i="${i}"><b>${esc([s.codigo,s.descricao].filter(Boolean).join(' · '))}</b><span>${esc([s.categoria,s.palavras_chave,money(s.valor)].filter(Boolean).join(' · '))}</span></button>`).join('');out.classList.remove('hidden');out.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>add(list[Number(el.dataset.i)]))}
 function add(s){if(typeof work==='undefined'||!work)return;work.servicos.unshift({id:uid('S'),servico_id:s.id,descricao:s.descricao||'',quantidade:1,valor:num(s.valor),desconto:0,acrescimo:0,tecnico:work.tecnico||'JEFERSON'});['sqCode','sqDesc','sqCat'].forEach(id=>{if($(id))$(id).value=''});$('sqResults')?.classList.add('hidden');compact();renderFinance();dirty();$('sqCode')?.focus()}
 function compact(){
  ensurePicker();const rows=$('serviceRows');if(!rows||typeof work==='undefined'||!work)return;
  rows.innerHTML=work.servicos.map((r,i)=>{const s=serviceBy(r.servico_id);return `<div class="itemrow srvCompact" data-i="${i}"><div class="srvIdentity"><b>${esc([s?.codigo,s?.descricao||r.descricao||'Serviço'].filter(Boolean).join(' · '))}</b><span>${esc([s?.categoria,s?.palavras_chave].filter(Boolean).join(' · '))}</span></div><label>Qtd/H<input class="srvQty" type="number" step=".25" value="${num(r.quantidade)||1}"></label><label>Valor<input class="srvVal" type="number" step=".01" value="${num(r.valor)}"></label><label>Desc.<input class="srvDisc" type="number" step=".01" value="${num(r.desconto)}"></label><label>Acrésc.<input class="srvAdd" type="number" step=".01" value="${num(r.acrescimo)}"></label><label>Técnico<input class="srvTech" value="${esc(r.tecnico||work.tecnico||'')}"></label><button type="button" class="danger delSrv">✕</button></div>`}).join('');
  bindRows('.srvQty','quantidade',work.servicos);bindRows('.srvVal','valor',work.servicos);bindRows('.srvDisc','desconto',work.servicos);bindRows('.srvAdd','acrescimo',work.servicos);bindRows('.srvTech','tecnico',work.servicos,false);document.querySelectorAll('#serviceRows .delSrv').forEach((e,i)=>e.onclick=()=>{work.servicos.splice(i,1);compact();renderFinance();dirty()});
 }
 function install(){if(typeof renderServices!=='function')return;ensurePicker();if(!window.__jfOldRenderServices)window.__jfOldRenderServices=renderServices;renderServices=compact;const addBtn=$('addService');if(addBtn)addBtn.style.display='none';compact()}
 addEventListener('DOMContentLoaded',()=>setTimeout(install,130));new MutationObserver(()=>{if($('tab-services')&&!$('srvQuickPicker'))install()}).observe(document.documentElement,{childList:true,subtree:true});
 const style=document.createElement('style');style.textContent=`.srvQuickPicker{margin:8px 0 10px}.srvQuickFields{display:grid;grid-template-columns:1fr 1.4fr 1.2fr;gap:7px}.srvQuickFields label{font-size:11px;color:#5f6c77}.srvQuickFields input{margin:2px 0 0}.srvQuickResults{border:1px solid #dce2e8;border-radius:9px;max-height:260px;overflow:auto;margin-top:5px}.srvQuickResult{display:flex;width:100%;border-radius:0;background:#fff;border-bottom:1px solid #edf0f2;text-align:left;padding:8px 10px;flex-direction:column;gap:2px}.srvQuickResult span,.srvIdentity span{font-size:11px;color:#65727f}.srvCompact{display:grid;grid-template-columns:minmax(260px,2.5fr) 72px 92px 82px 82px minmax(120px,1fr) 42px;gap:6px;align-items:end;padding:7px 0;border-bottom:1px dashed #dfe5ea}.srvCompact label{font-size:11px}.srvCompact input{padding:7px;margin:2px 0 0}.srvIdentity{align-self:center;min-width:0}.srvIdentity b,.srvIdentity span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:700px){.srvQuickFields{grid-template-columns:1fr 1fr}.srvQuickFields label:last-child{grid-column:1/-1}.srvCompact{grid-template-columns:1.15fr 1fr 1fr 42px;padding:6px 0}.srvIdentity{grid-column:1/-1}.srvCompact label:nth-of-type(1){grid-column:1}.srvCompact label:nth-of-type(2){grid-column:2}.srvCompact label:nth-of-type(3){grid-column:3}.srvCompact label:nth-of-type(4){grid-column:1}.srvCompact label:nth-of-type(5){grid-column:2/4}.srvCompact .delSrv{grid-column:4;grid-row:3}.srvIdentity b{font-size:13px}}`;document.head.appendChild(style);
})();