// JF Oficina v0.20.22 — núcleo único de sincronização
const JF_SYNC_VERSION='0.20.22';
const JF_SYNC_KEYS={revision:'jf-sync-revision',dirty:'jf-sync-dirty-at',last:'jf-sync-last-at',device:'jf-sync-device-id'};
let JF_SYNC_SUPPRESS=false;
function jfDeviceId(){let x=localStorage.getItem(JF_SYNC_KEYS.device);if(!x){x='D-'+crypto.randomUUID();localStorage.setItem(JF_SYNC_KEYS.device,x)}return x}
function jfStateItems(x=S){const c=x?.custom||{};return ['clientes','equipamentos_clientes','produtos','servicos_catalogo','ordens_servico','os_equipamentos','os_servicos','os_outros_servicos','os_produtos'].reduce((n,k)=>n+(Array.isArray(x?.[k])?x[k].length:0),0)+['clientes','equipamentos','os','funcionarios','fornecedores','categorias','marcas','locaisEstoque','orcamentos'].reduce((n,k)=>n+(Array.isArray(c[k])?c[k].length:0),0)}
function jfSetSyncStatus(text,type=''){const el=document.getElementById('syncStatus');if(el){el.textContent=text;el.dataset.type=type}const b=document.getElementById('jfAutoSyncBadge');if(b)b.textContent=text}
function jfSyncRevision(){return Number(localStorage.getItem(JF_SYNC_KEYS.revision)||0)}
function jfMarkSynced(rev){localStorage.setItem(JF_SYNC_KEYS.revision,String(rev||0));localStorage.removeItem(JF_SYNC_KEYS.dirty);localStorage.setItem(JF_SYNC_KEYS.last,new Date().toISOString())}
function jfMarkDirty(){if(JF_SYNC_SUPPRESS)return;localStorage.setItem(JF_SYNC_KEYS.dirty,String(Date.now()));window.dispatchEvent(new CustomEvent('jf-sync-dirty'))}
function jfScheduleSync(){jfMarkDirty()}
function jfRecordKey(x){return String(x?.id??x?.codigo_jf??x?.codigo_cti??x?.matricula??x?.numero_os??x?.numero_orcamento??'')}
function jfMergeArrayLocalWins(server=[],local=[]){const out=(server||[]).map(x=>deep(x)),idx=new Map(out.map((x,i)=>[jfRecordKey(x),i]));for(const item of local||[]){const k=jfRecordKey(item);if(k&&idx.has(k))out[idx.get(k)]=deep(item);else out.push(deep(item))}return out}
function jfMergeStatesLocalWins(server,local){const out=deep(server||{}),top=['clientes','equipamentos_clientes','produtos','servicos_catalogo','ordens_servico','os_equipamentos','os_servicos','os_outros_servicos','os_produtos','situacoes'];for(const k of top)out[k]=jfMergeArrayLocalWins(server?.[k]||[],local?.[k]||[]);out.custom=out.custom||{};const sc=server?.custom||{},lc=local?.custom||{};for(const k of ['clientes','equipamentos','os','log','stockMoves','deletedProducts','dictionary','techLibrary','funcionarios','fornecedores','categorias','marcas','locaisEstoque','orcamentos'])out.custom[k]=jfMergeArrayLocalWins(sc[k]||[],lc[k]||[]);out.custom.productSeq=Math.max(Number(sc.productSeq||0),Number(lc.productSeq||0));return out}
async function jfApplyServerState(payload,revision){if(!payload||typeof payload!=='object')return;JF_SYNC_SUPPRESS=true;try{S=deep(payload);normalize();S.custom=S.custom||{};for(const k of ['funcionarios','fornecedores','categorias','marcas','locaisEstoque','orcamentos'])S.custom[k]=S.custom[k]||[];await saveDB();render();if(typeof renderBudgets==='function')renderBudgets();jfMarkSynced(revision);window.dispatchEvent(new CustomEvent('jf-auth-synced'))}finally{JF_SYNC_SUPPRESS=false}}
async function jfSyncNow(mode='manual'){if(typeof window.jfAuthSyncNow==='function')return window.jfAuthSyncNow(mode)}
const jfOriginalSaveDB=saveDB;saveDB=async function(){const r=await jfOriginalSaveDB.apply(this,arguments);jfMarkDirty();return r};
function jfInstallSyncUI(){const settings=document.getElementById('settings');if(!settings||document.getElementById('syncBox'))return;const box=document.createElement('div');box.className='section';box.id='syncBox';box.innerHTML='<h3>Sincronização central</h3><p id="syncStatus" class="muted">Sincronização vinculada ao usuário autenticado.</p><div class="toolbar"><button type="button" id="syncNowBtn">Sincronizar agora</button></div><p class="small muted">Não é mais necessário código de sincronização por aparelho. A base correta é identificada pelo acesso do técnico.</p>';settings.insertBefore(box,document.getElementById('recoveryBox')||null);document.getElementById('syncNowBtn').onclick=()=>jfSyncNow('manual')}
addEventListener('DOMContentLoaded',()=>jfInstallSyncUI());
addEventListener('online',()=>window.jfAuthSyncNow?.('online'));
addEventListener('offline',()=>jfSetSyncStatus('Offline — alterações permanecem salvas neste aparelho.','offline'));
