// JF Oficina v0.19.9 — Técnicos, acesso por usuário/senha e comissões
(function(){
 const SUPA_URL='https://vfswmnkbwtlzensycnfj.supabase.co';
 const SUPA_KEY='sb_publishable_rO1NER3IpMO8HkRWwzVqvA_jDUqnyba';
 const FN=SUPA_URL+'/functions/v1/jf-technicians';
 const SESSION_KEY='jf-auth-session-v1', PROFILE_KEY='jf-auth-profile-v1', ENABLED_KEY='jf-auth-enabled-v1';
 const $=id=>document.getElementById(id), esc2=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const syncKey=()=>localStorage.getItem('jf-sync-key')||'';
 let currentProfile=null, techItems=[];
 const preLock=()=>window.JFAuthPrelock?.lock?.(),preUnlock=()=>window.JFAuthPrelock?.unlock?.();
 function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
 function setSession(s){if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY)}
 function setProfile(p){currentProfile=p||null;if(p)localStorage.setItem(PROFILE_KEY,JSON.stringify(p));else localStorage.removeItem(PROFILE_KEY);paintUser()}
 function cachedProfile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch{return null}}
 async function authReq(path,opt={}){const s=getSession(),h={'apikey':SUPA_KEY,'Content-Type':'application/json',...(opt.headers||{})};if(s?.access_token)h.Authorization='Bearer '+s.access_token;const r=await fetch(SUPA_URL+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||('HTTP '+r.status));return d}
 async function signIn(email,password){const d=await authReq('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});d.expires_at=Date.now()+(Number(d.expires_in)||3600)*1000;setSession(d);return d}
 async function refresh(){const s=getSession();if(!s?.refresh_token)throw new Error('Sessão expirada.');const d=await authReq('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token}),headers:{Authorization:''}});d.expires_at=Date.now()+(Number(d.expires_in)||3600)*1000;setSession(d);return d}
 async function validToken(){let s=getSession();if(!s)return null;if(s.expires_at&&s.expires_at-Date.now()<120000&&navigator.onLine){try{s=await refresh()}catch{return null}}return s.access_token||null}
 async function fn(action,data={},auth=true){let token=auth?await validToken():null;const h={'apikey':SUPA_KEY,'Content-Type':'application/json','x-jf-sync-key':syncKey()};if(token)h.Authorization='Bearer '+token;const r=await fetch(FN,{method:'POST',headers:h,body:JSON.stringify({action,...data})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||d.error||('HTTP '+r.status));return d}
 function addStyles(){if($('jfAuthStyles'))return;const st=document.createElement('style');st.id='jfAuthStyles';st.textContent=`#jfAuthGate{position:fixed;inset:0;background:linear-gradient(135deg,#102d4b,#0b5d34);z-index:999999;display:flex;align-items:center;justify-content:center;padding:18px;visibility:visible!important;pointer-events:auto!important}#jfAuthGate.hidden{display:none}.jfLoginCard{width:min(420px,96vw);background:#fff;border-radius:10px;padding:20px;border-top:5px solid #f2c500;box-shadow:0 25px 80px #0007}.jfLoginCard h2{margin:0 0 6px;color:#102d4b}.jfAuthMsg{min-height:18px;margin-top:7px;font-size:12px}.jfUserBtn{background:#f2c500!important;color:#102d4b!important}.jfTechActions{display:flex;gap:5px;flex-wrap:wrap}.jfCommissionGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.jfAccessCard{border-left:4px solid #087b36;padding:10px;background:#f5f8f4;margin:8px 0}.jfTechModal{width:min(760px,96vw)}@media(max-width:800px){.jfCommissionGrid{grid-template-columns:1fr}.jfTechTable th:nth-child(3),.jfTechTable td:nth-child(3){display:none}}`;document.head.appendChild(st)}
 function installGate(){if($('jfAuthGate'))return;const g=document.createElement('div');g.id='jfAuthGate';g.className='hidden';g.innerHTML=`<div class="jfLoginCard"><h2>JF Oficina</h2><p class="muted">Acesso de técnico</p><label>Usuário ou e-mail<input id="jfLoginUser" autocomplete="username"></label><label>Senha<input id="jfLoginPass" type="password" autocomplete="current-password"></label><button id="jfLoginBtn" class="primary" style="width:100%;margin-top:8px">Entrar</button><div id="jfLoginMsg" class="jfAuthMsg muted"></div></div>`;document.body.appendChild(g);$('jfLoginBtn').onclick=login;['jfLoginUser','jfLoginPass'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')login()}))}
 function showGate(msg=''){preLock();installGate();$('jfAuthGate').classList.remove('hidden');$('jfLoginMsg').textContent=msg}
 function hideGate(){if($('jfAuthGate'))$('jfAuthGate').classList.add('hidden');preUnlock()}
 async function login(){const u=$('jfLoginUser').value.trim(),p=$('jfLoginPass').value;$('jfLoginMsg').textContent='Entrando...';try{let email=u;if(!u.includes('@'))email=(await fn('login_hint',{username:u},false)).auth_email;await signIn(email,p);const me=await fn('me');if(!me?.item?.active&&me?.item?.active!==undefined)throw new Error('Usuário inativo.');setProfile(me.item);localStorage.setItem(ENABLED_KEY,'1');hideGate();$('jfLoginPass').value=''}catch(e){setSession(null);setProfile(null);showGate('Acesso negado: '+e.message)}}
 async function logout(){preLock();try{await authReq('/auth/v1/logout',{method:'POST'})}catch{}setSession(null);setProfile(null);showGate('Sessão encerrada.')}
 function paintUser(){let b=$('jfUserBtn');if(!b){const h=document.querySelector('header');if(!h)return;b=document.createElement('button');b.id='jfUserBtn';b.className='jfUserBtn';h.appendChild(b);b.onclick=openUserMenu}b.textContent=currentProfile?.name?('👤 '+currentProfile.name):'👤 Acesso'}
 function openUserMenu(){if(!currentProfile){showGate();return}if(!$('jfUserDlg')){const d=document.createElement('dialog');d.id='jfUserDlg';d.className='modal';d.innerHTML=`<div class="dhead"><b>Meu acesso</b><button id="jfUserClose">✕</button></div><div class="dbody"><p id="jfUserIdentity"></p><div class="grid2"><label>Nova senha<input id="jfOwnPass" type="password" minlength="8"></label><label>Confirmar senha<input id="jfOwnPass2" type="password" minlength="8"></label></div><button id="jfOwnChange" class="primary">Alterar minha senha</button></div><div class="dfoot"><button id="jfLogout" class="danger">Sair</button></div>`;document.body.appendChild(d);$('jfUserClose').onclick=()=>d.close();$('jfLogout').onclick=()=>{d.close();logout()};$('jfOwnChange').onclick=changeOwnPassword}const d=$('jfUserDlg');$('jfUserIdentity').textContent=`${currentProfile.name} · ${currentProfile.role==='admin'?'Administrador':'Técnico'}`;d.showModal()}
 async function changeOwnPassword(){const a=$('jfOwnPass').value,b=$('jfOwnPass2').value;if(a.length<8)return alert('A senha precisa ter pelo menos 8 caracteres.');if(a!==b)return alert('As senhas não conferem.');try{await authReq('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:a})});$('jfOwnPass').value=$('jfOwnPass2').value='';alert('Senha alterada com sucesso.')}catch(e){alert('Falha ao alterar senha: '+e.message)}}
 function mirrorLocal(item){S.custom=S.custom||{};S.custom.funcionarios=S.custom.funcionarios||[];let x=S.custom.funcionarios.find(f=>String(f.auth_profile_id||'')===String(item.id)||String(f.id||'')===String(item.employee_id||''));if(!x){x={id:item.employee_id||uid('TEC')};S.custom.funcionarios.push(x)}Object.assign(x,{nome:item.name,funcao:item.function_title||'Técnico',telefone:item.phone||'',email:item.email||'',ativo:item.active!==false,usuario:item.username||'',auth_profile_id:item.id,auth_user_id:item.auth_user_id,comissao_servicos:Number(item.commission_services)||0,comissao_pecas:Number(item.commission_parts)||0,comissao_outros:Number(item.commission_others)||0});return x}
 async function loadTechs(){const d=await fn('list');techItems=d.items||[];for(const x of techItems)mirrorLocal(x);await saveDB();return techItems}
 function renderBootstrap(panel){panel.innerHTML=`<h3>Técnicos</h3><div class="jfAccessCard"><b>Ativar controle de acesso</b><p class="small muted">Crie o primeiro administrador. Depois disso, cada técnico terá usuário e senha próprios.</p><div class="grid2"><label>Nome do administrador<input id="jfBootName" value="Jeferson"></label><label>E-mail do administrador<input id="jfBootEmail" type="email"></label></div><div class="grid2"><label>Senha inicial<input id="jfBootPass" type="password" minlength="8"></label><label>Confirmar senha<input id="jfBootPass2" type="password" minlength="8"></label></div><button id="jfBootBtn" class="primary">Ativar acesso</button><span id="jfBootMsg" class="small muted"></span></div>`;$('jfBootBtn').onclick=bootstrap}
 async function bootstrap(){const n=$('jfBootName').value.trim(),e=$('jfBootEmail').value.trim(),a=$('jfBootPass').value,b=$('jfBootPass2').value;if(!e||a.length<8)return alert('Informe e-mail e uma senha com pelo menos 8 caracteres.');if(a!==b)return alert('As senhas não conferem.');$('jfBootMsg').textContent='Criando administrador...';try{await fn('bootstrap_admin',{name:n,email:e,password:a},false);await signIn(e,a);const me=await fn('me');setProfile(me.item);localStorage.setItem(ENABLED_KEY,'1');hideGate();await renderTechPanel()}catch(err){$('jfBootMsg').textContent='Falha: '+err.message}}
 async function renderTechPanel(){const panel=$('adminPanel');if(!panel)return;let status;try{status=await fn('status',{},false)}catch(e){panel.innerHTML=`<h3>Técnicos</h3><p class="muted">Não foi possível consultar o serviço de acesso: ${esc2(e.message)}</p>`;return}if(!status.auth_enabled){renderBootstrap(panel);return}localStorage.setItem(ENABLED_KEY,'1');if(!currentProfile){panel.innerHTML='<h3>Técnicos</h3><p class="muted">Faça login como administrador para gerenciar acessos.</p>';showGate();return}if(currentProfile?.role!=='admin'){panel.innerHTML='<h3>Técnicos</h3><p class="muted">Somente o administrador pode gerenciar técnicos e comissões.</p>';return}try{await loadTechs()}catch(e){panel.innerHTML=`<h3>Técnicos</h3><p class="muted">Falha ao carregar técnicos: ${esc2(e.message)}</p>`;return}panel.innerHTML=`<div class="toolbar"><h3 style="margin:0">Técnicos</h3><button id="jfNewTech" class="primary">+ Novo técnico</button></div><p class="small muted">Cada técnico tem acesso próprio e percentuais independentes de comissão.</p><div class="tablewrap"><table class="jfTechTable"><thead><tr><th>Nome / usuário</th><th>Função</th><th>Contato</th><th>Comissões</th><th>Situação</th><th></th></tr></thead><tbody>${techItems.map(x=>`<tr><td><b>${esc2(x.name)}</b><br><span class="muted">${esc2(x.username||'')}</span></td><td>${esc2(x.function_title||'')}</td><td>${esc2(x.phone||x.email||'')}</td><td>Serv. ${num(x.commission_services)}% · Peças ${num(x.commission_parts)}% · Outros ${num(x.commission_others)}%</td><td>${x.active?'Ativo':'Inativo'}${x.role==='admin'?' · Admin':''}</td><td><div class="jfTechActions"><button data-edit-tech="${x.id}">Editar</button>${x.role!=='admin'?`<button data-pass-tech="${x.id}">Redefinir senha</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`;$('jfNewTech').onclick=()=>openTechEditor();panel.querySelectorAll('[data-edit-tech]').forEach(b=>b.onclick=()=>openTechEditor(b.dataset.editTech));panel.querySelectorAll('[data-pass-tech]').forEach(b=>b.onclick=()=>resetPassword(b.dataset.passTech))}
 function installTechModal(){if($('jfTechDlg'))return;const d=document.createElement('dialog');d.id='jfTechDlg';d.className='modal jfTechModal';d.innerHTML=`<form id="jfTechForm"><div class="dhead"><b id="jfTechTitle">Técnico</b><button type="button" id="jfTechClose">✕</button></div><div class="dbody"><input id="jfTechId" type="hidden"><div class="grid2"><label>Nome<input id="jfTechName" required></label><label>Função<input id="jfTechFunction" value="Técnico"></label><label>Usuário<input id="jfTechUsername" required autocomplete="off"></label><label>E-mail<input id="jfTechEmail" type="email"></label><label>Telefone<input id="jfTechPhone"></label><label>Situação<select id="jfTechActive"><option value="1">Ativo</option><option value="0">Inativo</option></select></label></div><h3>Comissões</h3><div class="jfCommissionGrid"><label>Serviços (%)<input id="jfCommServices" type="number" min="0" step="0.01" value="0"></label><label>Peças / materiais (%)<input id="jfCommParts" type="number" min="0" step="0.01" value="0"></label><label>Outros / deslocamentos (%)<input id="jfCommOthers" type="number" min="0" step="0.01" value="0"></label></div><div id="jfNewPassBox"><h3>Acesso</h3><label>Senha inicial<input id="jfTechPassword" type="password" minlength="8"><span class="small muted">Mínimo 8 caracteres. O administrador poderá redefinir, mas não visualizar a senha atual.</span></label></div></div><div class="dfoot"><button type="button" id="jfTechCancel">Cancelar</button><button class="primary">Salvar</button></div></form>`;document.body.appendChild(d);$('jfTechClose').onclick=$('jfTechCancel').onclick=()=>d.close();$('jfTechForm').onsubmit=saveTech}
 function openTechEditor(id=''){installTechModal();const x=id?techItems.find(t=>String(t.id)===String(id)):null;$('jfTechId').value=x?.id||'';$('jfTechTitle').textContent=x?'Editar técnico':'Novo técnico';$('jfTechName').value=x?.name||'';$('jfTechFunction').value=x?.function_title||'Técnico';$('jfTechUsername').value=x?.username||'';$('jfTechEmail').value=x?.email||'';$('jfTechPhone').value=x?.phone||'';$('jfTechActive').value=x?.active===false?'0':'1';$('jfCommServices').value=num(x?.commission_services);$('jfCommParts').value=num(x?.commission_parts);$('jfCommOthers').value=num(x?.commission_others);$('jfTechPassword').value='';$('jfNewPassBox').style.display=x?'none':'block';$('jfTechDlg').showModal()}
 async function saveTech(ev){ev.preventDefault();const id=$('jfTechId').value,payload={id,name:$('jfTechName').value.trim(),function_title:$('jfTechFunction').value.trim(),username:$('jfTechUsername').value.trim(),email:$('jfTechEmail').value.trim(),phone:$('jfTechPhone').value.trim(),active:$('jfTechActive').value==='1',commission_services:num($('jfCommServices').value),commission_parts:num($('jfCommParts').value),commission_others:num($('jfCommOthers').value),password:$('jfTechPassword').value};if(!id&&payload.password.length<8)return alert('A senha inicial precisa ter pelo menos 8 caracteres.');try{const d=await fn(id?'update':'create',payload);mirrorLocal(d.item);await saveDB();$('jfTechDlg').close();await renderTechPanel()}catch(e){alert('Falha ao salvar técnico: '+e.message)}}
 async function resetPassword(id){const p=prompt('Digite a NOVA senha para este técnico (mínimo 8 caracteres):');if(p===null)return;if(p.length<8)return alert('A senha precisa ter pelo menos 8 caracteres.');try{await fn('reset_password',{id,password:p});alert('Senha redefinida com sucesso.')}catch(e){alert('Falha ao redefinir senha: '+e.message)}}
 function hookFolder(){const b=document.querySelector('[data-admin="funcionarios"]');if(!b||b.dataset.jfTechHook)return;b.dataset.jfTechHook='1';const bb=b.querySelector('b'),sp=b.querySelector('span');if(bb)bb.textContent='Técnicos';if(sp)sp.textContent='Equipe, acessos e comissões';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();renderTechPanel()},true)}
 async function bootAuth(){preLock();addStyles();installGate();paintUser();hookFolder();const k=syncKey();if(!k){showGate('Acesso obrigatório. Entre com seu usuário e senha.');return}let status=null;try{status=await fn('status',{},false)}catch{if(getSession()&&cachedProfile()&&!navigator.onLine){setProfile(cachedProfile());hideGate()}else showGate('Não foi possível validar o acesso. Verifique a conexão.');return}if(!status.auth_enabled){localStorage.removeItem(ENABLED_KEY);showGate('Controle de acesso ainda não foi ativado.');return}localStorage.setItem(ENABLED_KEY,'1');let s=getSession();if(!s){showGate();return}if(!navigator.onLine){const cp=cachedProfile();if(cp){setProfile(cp);hideGate()}else showGate();return}try{const token=await validToken();if(!token)throw new Error('Sessão inválida');const me=await fn('me');if(!me?.item)throw new Error('Perfil não encontrado');setProfile(me.item);hideGate()}catch{setSession(null);setProfile(null);showGate('Sua sessão expirou. Entre novamente.')}}
 addEventListener('DOMContentLoaded',()=>setTimeout(()=>{hookFolder();bootAuth()},0));new MutationObserver(()=>hookFolder()).observe(document.documentElement,{childList:true,subtree:true});
 window.JFAuth={current:()=>currentProfile,logout,renderTechPanel};
})();