// JF Oficina v0.20.22 — autenticação estável e painel de técnicos
(function(){
 const SUPA_URL='https://vfswmnkbwtlzensycnfj.supabase.co';
 const SUPA_KEY='sb_publishable_rO1NER3IpMO8HkRWwzVqvA_jDUqnyba';
 const FN=SUPA_URL+'/functions/v1/jf-technicians';
 const SESSION_KEY='jf-auth-session-v1',PROFILE_KEY='jf-auth-profile-v1',ENABLED_KEY='jf-auth-enabled-v1',BROWSER_KEY='jf-auth-browser-session-v1';
 const $=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const num=v=>Number(v)||0;
 let currentProfile=null,techItems=[];
 const preLock=()=>window.JFAuthPrelock?.lock?.(),preUnlock=()=>window.JFAuthPrelock?.unlock?.();
 function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
 function setSession(s){if(s){localStorage.setItem(SESSION_KEY,JSON.stringify(s));sessionStorage.setItem(BROWSER_KEY,'1')}else{localStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(BROWSER_KEY)}}
 function cachedProfile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'null')}catch{return null}}
 function localTech(profile=currentProfile){if(!profile)return null;const a=S?.custom?.funcionarios||[];return a.find(x=>String(x.auth_profile_id||'')===String(profile.id||'')||String(x.auth_user_id||'')===String(profile.auth_user_id||''))||null}
 function effectiveProfile(){const base=currentProfile||cachedProfile();if(!base)return null;const local=localTech(base);return local?.permissions?{...base,permissions:local.permissions}:base}
 function setProfile(p){currentProfile=p||null;if(p)localStorage.setItem(PROFILE_KEY,JSON.stringify(p));else localStorage.removeItem(PROFILE_KEY);paintUser()}
 async function authReq(path,opt={}){const s=getSession(),h={'apikey':SUPA_KEY,'Content-Type':'application/json',...(opt.headers||{})};if(s?.access_token&&h.Authorization!==''&&!h.Authorization)h.Authorization='Bearer '+s.access_token;const r=await fetch(SUPA_URL+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||('HTTP '+r.status));return d}
 async function signIn(email,password){const d=await authReq('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password}),headers:{Authorization:''}});d.expires_at=Date.now()+(Number(d.expires_in)||3600)*1000;setSession(d);return d}
 async function refresh(){const s=getSession();if(!s?.refresh_token)throw new Error('Sessão expirada.');const d=await authReq('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token}),headers:{Authorization:''}});d.expires_at=Date.now()+(Number(d.expires_in)||3600)*1000;setSession(d);return d}
 async function validToken(){let s=getSession();if(!s)return null;if(s.expires_at&&s.expires_at-Date.now()<120000&&navigator.onLine){try{s=await refresh()}catch{return null}}return s?.access_token||null}
 async function fn(action,data={},auth=true){const token=auth?await validToken():null,h={'apikey':SUPA_KEY,'Content-Type':'application/json'};if(token)h.Authorization='Bearer '+token;const r=await fetch(FN,{method:'POST',headers:h,body:JSON.stringify({action,...data})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||d.error||('HTTP '+r.status));return d}
 function addStyles(){if($('jfAuthStyles'))return;const st=document.createElement('style');st.id='jfAuthStyles';st.textContent=`#jfAuthGate{position:fixed;inset:0;background:linear-gradient(135deg,#102d4b,#0b5d34);z-index:999999;display:flex;align-items:center;justify-content:center;padding:18px;visibility:visible!important;pointer-events:auto!important}#jfAuthGate.hidden{display:none}.jfLoginCard{width:min(420px,96vw);background:#fff;border-radius:10px;padding:20px;border-top:5px solid #f2c500;box-shadow:0 25px 80px #0007}.jfUserBtn{background:#f2c500!important;color:#102d4b!important}.jfTechActions{display:flex;gap:5px;flex-wrap:wrap}.jfTechTable{width:100%}`;document.head.appendChild(st)}
 function installGate(){if($('jfAuthGate'))return;const g=document.createElement('div');g.id='jfAuthGate';g.className='hidden';g.innerHTML=`<div class="jfLoginCard"><h2>JF Oficina</h2><p class="muted">Acesso de técnico</p><label>Usuário<input id="jfLoginUser" autocomplete="username"></label><label>Senha<input id="jfLoginPass" type="password" autocomplete="current-password"></label><button id="jfLoginBtn" class="primary" style="width:100%;margin-top:8px">Entrar</button><div id="jfLoginMsg" class="small muted" style="min-height:20px;margin-top:8px"></div></div>`;document.body.appendChild(g);$('jfLoginBtn').onclick=login;['jfLoginUser','jfLoginPass'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')login()}))}
 function showGate(msg=''){preLock();installGate();$('jfAuthGate').classList.remove('hidden');$('jfLoginMsg').textContent=msg}
 function hideGate(){if($('jfAuthGate'))$('jfAuthGate').classList.add('hidden');preUnlock()}
 async function login(){const u=$('jfLoginUser').value.trim(),p=$('jfLoginPass').value;if(!u||!p)return showGate('Informe usuário e senha.');$('jfLoginMsg').textContent='Entrando...';try{const hint=await fn('login_hint',{username:u.toLowerCase()},false);await signIn(hint.auth_email,p);const me=await fn('me');if(!me?.item)throw new Error('Perfil não encontrado.');setProfile(me.item);localStorage.setItem(ENABLED_KEY,'1');hideGate();$('jfLoginPass').value='';window.dispatchEvent(new CustomEvent('jf-auth-synced'));setTimeout(()=>window.jfAuthSyncNow?.('login'),200)}catch(e){setSession(null);setProfile(null);showGate('Acesso negado: '+e.message)}}
 async function logout(){preLock();try{await authReq('/auth/v1/logout',{method:'POST'})}catch{}setSession(null);setProfile(null);showGate('Sessão encerrada.')}
 function paintUser(){let b=$('jfUserBtn');if(!b){const h=document.querySelector('header');if(!h)return;b=document.createElement('button');b.id='jfUserBtn';b.className='jfUserBtn';h.appendChild(b);b.onclick=openUserMenu}const p=effectiveProfile();b.textContent=p?.name?('👤 '+p.name):'👤 Acesso'}
 function openUserMenu(){const p=effectiveProfile();if(!p)return showGate();if(!$('jfUserDlg')){const d=document.createElement('dialog');d.id='jfUserDlg';d.className='modal';d.innerHTML=`<div class="dhead"><b>Meu acesso</b><button id="jfUserClose">✕</button></div><div class="dbody"><p id="jfUserIdentity"></p><div class="grid2"><label>Nova senha<input id="jfOwnPass" type="password" minlength="8"></label><label>Confirmar senha<input id="jfOwnPass2" type="password" minlength="8"></label></div><button id="jfOwnChange" class="primary">Alterar minha senha</button></div><div class="dfoot"><button id="jfLogout" class="danger">Sair</button></div>`;document.body.appendChild(d);$('jfUserClose').onclick=()=>d.close();$('jfLogout').onclick=()=>{d.close();logout()};$('jfOwnChange').onclick=changeOwnPassword}const d=$('jfUserDlg');$('jfUserIdentity').textContent=`${p.name} · ${p.role==='admin'?'Administrador':'Técnico'}`;d.showModal()}
 async function changeOwnPassword(){const a=$('jfOwnPass').value,b=$('jfOwnPass2').value;if(a.length<8)return alert('A senha precisa ter pelo menos 8 caracteres.');if(a!==b)return alert('As senhas não conferem.');try{await authReq('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:a})});$('jfOwnPass').value=$('jfOwnPass2').value='';alert('Senha alterada com sucesso.')}catch(e){alert('Falha ao alterar senha: '+e.message)}}
 function mirrorLocal(item){S.custom=S.custom||{};S.custom.funcionarios=S.custom.funcionarios||[];let x=S.custom.funcionarios.find(f=>String(f.auth_profile_id||'')===String(item.id)||String(f.auth_user_id||'')===String(item.auth_user_id||''));if(!x){x={id:item.employee_id||uid('TEC')};S.custom.funcionarios.push(x)}const localPerm=x.permissions;Object.assign(x,{nome:item.name,funcao:item.function_title||'Técnico',telefone:item.phone||'',email:item.email||'',ativo:item.active!==false,usuario:item.username||'',auth_profile_id:item.id,auth_user_id:item.auth_user_id,comissao_servicos:num(item.commission_services),comissao_pecas:num(item.commission_parts),comissao_outros:num(item.commission_others)});if(!localPerm&&item.permissions)x.permissions=item.permissions;return x}
 async function loadTechs(){const d=await fn('list');techItems=d.items||[];for(const x of techItems)mirrorLocal(x);return techItems}
 async function renderTechPanel(){const panel=$('adminPanel');if(!panel)return;const p=effectiveProfile();if(!p){panel.innerHTML='<h3>Técnicos</h3><p class="muted">Faça login para gerenciar acessos.</p>';return showGate()}if(p.role!=='admin'){panel.innerHTML='<h3>Técnicos</h3><p class="muted">Somente o administrador pode gerenciar técnicos.</p>';return}try{await loadTechs()}catch(e){panel.innerHTML=`<h3>Técnicos</h3><p class="muted">Falha ao carregar técnicos: ${esc(e.message)}</p>`;return}panel.innerHTML=`<div class="toolbar"><h3 style="margin:0">Técnicos</h3></div><p class="small muted">A edição de permissões está ativa. Criação de usuário e redefinição administrativa de senha continuam protegidas até a estabilização definitiva do Auth.</p><div class="tablewrap"><table class="jfTechTable"><thead><tr><th>Nome / usuário</th><th>Função</th><th>Contato</th><th>Comissões</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${techItems.map(x=>`<tr><td><b>${esc(x.name)}</b><br><span class="muted">${esc(x.username||'')}</span></td><td>${esc(x.function_title||'')}</td><td>${esc(x.phone||x.email||'')}</td><td>Serv. ${num(x.commission_services)}% · Peças ${num(x.commission_parts)}% · Outros ${num(x.commission_others)}%</td><td>${x.active?'Ativo':'Inativo'}${x.role==='admin'?' · Admin':''}</td><td><span data-edit-tech="${x.id}" style="display:none"></span></td></tr>`).join('')}</tbody></table></div>`;setTimeout(()=>window.JFPermissions?.refreshButtons?.(),0)}
 function hookFolder(){const b=document.querySelector('[data-admin="funcionarios"]');if(!b||b.dataset.jfTechHook)return;b.dataset.jfTechHook='1';const bb=b.querySelector('b'),sp=b.querySelector('span');if(bb)bb.textContent='Técnicos';if(sp)sp.textContent='Equipe, acessos e permissões';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();renderTechPanel()},true)}
 async function bootAuth(){preLock();addStyles();installGate();paintUser();hookFolder();if(getSession()&&!sessionStorage.getItem(BROWSER_KEY)){setSession(null);setProfile(null)}let status;try{status=await fn('status',{},false)}catch(e){const cp=cachedProfile();if(!navigator.onLine&&cp&&getSession()){setProfile(cp);hideGate();return}return showGate('Não foi possível validar o acesso. Verifique a conexão.')}if(!status.auth_enabled){localStorage.removeItem(ENABLED_KEY);return showGate('Controle de acesso ainda não foi ativado.')}localStorage.setItem(ENABLED_KEY,'1');if(!getSession())return showGate();try{const token=await validToken();if(!token)throw new Error('Sessão inválida');const me=await fn('me');setProfile(me.item);sessionStorage.setItem(BROWSER_KEY,'1');hideGate();window.dispatchEvent(new CustomEvent('jf-auth-synced'))}catch{setSession(null);setProfile(null);showGate('Sua sessão expirou. Entre novamente.')}}
 addEventListener('DOMContentLoaded',()=>setTimeout(()=>{hookFolder();bootAuth()},0));new MutationObserver(()=>hookFolder()).observe(document.documentElement,{childList:true,subtree:true});
 window.JFAuth={current:effectiveProfile,raw:()=>currentProfile,session:getSession,logout,renderTechPanel,refreshProfile:async()=>{const me=await fn('me');setProfile(me.item);return effectiveProfile()}};
})();