import { createClient } from 'npm:@supabase/supabase-js@2'

const cors={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-jf-sync-key',
  'Access-Control-Allow-Methods':'POST, OPTIONS',
  'Content-Type':'application/json; charset=utf-8'
}
const respond=(status:number,data:any)=>new Response(JSON.stringify(data),{status,headers:cors})
const clean=(v:any)=>String(v??'').trim()
const pct=(v:any)=>Math.max(0,Number(v)||0)
const URL=Deno.env.get('SUPABASE_URL')||''
const PUBLIC_KEY='sb_publishable_rO1NER3IpMO8HkRWwzVqvA_jDUqnyba'
async function sha256(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bearer(req:Request){return (req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim()}
function publicClient(token=''){const options:any={auth:{persistSession:false,autoRefreshToken:false}};if(token)options.global={headers:{Authorization:'Bearer '+token}};return createClient(URL,PUBLIC_KEY,options)}
function adminClient(){const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const secretJson=Deno.env.get('SUPABASE_SECRET_KEYS')||'';let fallback='';if(secretJson){try{fallback=JSON.parse(secretJson)?.default||''}catch{}}return createClient(URL,service||fallback,{auth:{persistSession:false,autoRefreshToken:false}})}
async function getWorkspaceHash(req:Request,body:any){const syncKey=clean(req.headers.get('x-jf-sync-key')||body.sync_key);if(syncKey.length<24)return null;return await sha256(syncKey)}
async function userContext(req:Request){const token=bearer(req);if(!token)return null;const client=publicClient(token);const {data,error}=await client.auth.getUser(token);if(error||!data?.user)return null;return {token,client,user:data.user}}
function authProfile(user:any){const app=user?.app_metadata||{},meta=user?.user_metadata||{},workspace=clean(app.jf_workspace);if(!workspace)return null;const role=clean(app.jf_role)||'technician';return {id:'auth:'+user.id,auth_user_id:user.id,workspace_hash:workspace,name:clean(meta.name)||clean(meta.username)||clean(user.email)||'Técnico',username:clean(meta.username),auth_email:clean(user.email),email:null,phone:null,function_title:role==='admin'?'Administrador':'Técnico',role,active:app.jf_active!==false,commission_services:0,commission_parts:0,commission_others:0,permissions:{}}}
async function selfTech(ctx:any){const admin=adminClient();const {data,error}=await admin.from('jf_technicians').select('*').eq('auth_user_id',ctx.user.id).maybeSingle();if(error)throw error;return data||authProfile(ctx.user)||null}
async function requireAdmin(req:Request){const ctx=await userContext(req);if(!ctx)return {error:respond(401,{ok:false,error:'login_required'})};const tech=await selfTech(ctx);if(!tech||!tech.active||tech.role!=='admin')return {error:respond(403,{ok:false,error:'admin_required'})};return {ctx,tech}}
function authEmail(username:string,workspace:string){const u=username.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9._-]+/g,'.').replace(/^\.+|\.+$/g,'')||'tecnico';return `${u}.${workspace.slice(0,10)}@jf-oficina.local`}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return respond(405,{ok:false,error:'method_not_allowed'});
 let body:any={};try{body=await req.json()}catch{}const action=clean(body.action);
 try{
  if(action==='status'){const wh=await getWorkspaceHash(req,body);if(!wh)return respond(401,{ok:false,error:'invalid_workspace'});const c=publicClient();const {data,error}=await c.rpc('jf_auth_status',{p_workspace_hash:wh});if(error)throw error;return respond(200,{ok:true,workspace_hash:wh,auth_enabled:!!data})}
  if(action==='login_hint'){const wh=await getWorkspaceHash(req,body);if(!wh)return respond(401,{ok:false,error:'invalid_workspace'});const username=clean(body.username).toLowerCase();if(!username)return respond(400,{ok:false,error:'username_required'});const c=publicClient();const {data,error}=await c.rpc('jf_login_hint',{p_username:username,p_workspace_hash:wh});if(error)throw error;const rows=Array.isArray(data)?data:[];if(!rows.length)return respond(404,{ok:false,error:'user_not_found'});if(rows.length>1)return respond(409,{ok:false,error:'username_ambiguous'});return respond(200,{ok:true,auth_email:rows[0].auth_email})}
  if(action==='me'){const ctx=await userContext(req);if(!ctx)return respond(401,{ok:false,error:'login_required'});const tech=await selfTech(ctx);if(!tech)return respond(404,{ok:false,error:'profile_not_found'});if(!tech.active)return respond(403,{ok:false,error:'inactive'});return respond(200,{ok:true,item:tech})}
  if(action==='sync_get'){const ctx=await userContext(req);if(!ctx)return respond(401,{ok:false,error:'login_required'});const tech=await selfTech(ctx);if(!tech)return respond(404,{ok:false,error:'profile_not_found'});if(!tech.active)return respond(403,{ok:false,error:'inactive'});const admin=adminClient();const {data,error}=await admin.from('jf_sync_state').select('payload,revision,updated_at').eq('workspace_hash',tech.workspace_hash).maybeSingle();if(error)throw error;if(!data)return respond(200,{ok:true,exists:false,revision:0,payload:null,updatedAt:null,workspace_hash:tech.workspace_hash});return respond(200,{ok:true,exists:true,revision:Number(data.revision||0),payload:data.payload,updatedAt:data.updated_at,workspace_hash:tech.workspace_hash})}
  if(action==='sync_post'){const ctx=await userContext(req);if(!ctx)return respond(401,{ok:false,error:'login_required'});const tech=await selfTech(ctx);if(!tech)return respond(404,{ok:false,error:'profile_not_found'});if(!tech.active)return respond(403,{ok:false,error:'inactive'});const payload=body.payload,baseRevision=Number(body.baseRevision||0);if(!payload||typeof payload!=='object')return respond(400,{ok:false,error:'invalid_payload'});const admin=adminClient();const {data:current,error:ce}=await admin.from('jf_sync_state').select('revision,payload,updated_at').eq('workspace_hash',tech.workspace_hash).maybeSingle();if(ce)throw ce;if(!current){if(baseRevision!==0)return respond(409,{ok:false,error:'revision_conflict',revision:0,payload:null,updatedAt:null});const {data,error}=await admin.from('jf_sync_state').insert({workspace_hash:tech.workspace_hash,payload,revision:1,updated_at:new Date().toISOString()}).select('revision,updated_at').single();if(error)throw error;return respond(200,{ok:true,revision:Number(data.revision),updatedAt:data.updated_at})}const rev=Number(current.revision||0);if(baseRevision!==rev)return respond(409,{ok:false,error:'revision_conflict',revision:rev,payload:current.payload,updatedAt:current.updated_at});const {data,error}=await admin.from('jf_sync_state').update({payload,revision:rev+1,updated_at:new Date().toISOString()}).eq('workspace_hash',tech.workspace_hash).eq('revision',rev).select('revision,updated_at').maybeSingle();if(error)throw error;if(!data)return respond(409,{ok:false,error:'revision_conflict'});return respond(200,{ok:true,revision:Number(data.revision),updatedAt:data.updated_at})}
  const adm=await requireAdmin(req);if((adm as any).error)return (adm as any).error;const tech=(adm as any).tech;const workspace=tech.workspace_hash;const admin=adminClient();
  if(action==='list'){const {data,error}=await admin.from('jf_technicians').select('*').eq('workspace_hash',workspace).order('name');if(error)throw error;return respond(200,{ok:true,items:data||[]})}
  if(action==='create'){const name=clean(body.name),username=clean(body.username).toLowerCase(),password=clean(body.password);if(!name||!username||password.length<8)return respond(400,{ok:false,error:'name_username_password_required'});const email=clean(body.email),ae=authEmail(username,workspace);const {data:created,error}=await admin.auth.admin.createUser({email:ae,password,email_confirm:true,app_metadata:{jf_role:'technician',jf_workspace:workspace,jf_active:body.active!==false},user_metadata:{name,username}});if(error||!created?.user)return respond(400,{ok:false,error:'auth_create_failed',message:error?.message});const user=created.user;const record={workspace_hash:workspace,auth_user_id:user.id,employee_id:clean(body.employee_id)||null,name,username,auth_email:ae,email:email||null,phone:clean(body.phone)||null,function_title:clean(body.function_title)||'Técnico',role:'technician',active:body.active!==false,commission_services:pct(body.commission_services),commission_parts:pct(body.commission_parts),commission_others:pct(body.commission_others),permissions:body.permissions||{}};const {data,error:pe}=await admin.from('jf_technicians').insert(record).select().single();if(pe){await admin.auth.admin.deleteUser(user.id);return respond(400,{ok:false,error:'profile_create_failed',message:pe.message})}return respond(200,{ok:true,item:data})}
  if(action==='update'){const id=clean(body.id);if(!id)return respond(400,{ok:false,error:'id_required'});const {data:old,error:oe}=await admin.from('jf_technicians').select('*').eq('id',id).eq('workspace_hash',workspace).maybeSingle();if(oe)throw oe;if(!old)return respond(404,{ok:false,error:'not_found'});const updates:any={name:clean(body.name)||old.name,email:clean(body.email)||null,phone:clean(body.phone)||null,function_title:clean(body.function_title)||old.function_title,active:body.active!==false,commission_services:pct(body.commission_services),commission_parts:pct(body.commission_parts),commission_others:pct(body.commission_others),permissions:body.permissions||old.permissions||{}};const newUsername=clean(body.username).toLowerCase()||old.username;const authUpdate:any={app_metadata:{jf_role:old.role||'technician',jf_workspace:workspace,jf_active:updates.active}};if(newUsername!==old.username){updates.username=newUsername;updates.auth_email=authEmail(newUsername,workspace);authUpdate.email=updates.auth_email;authUpdate.user_metadata={name:updates.name,username:newUsername}}else if(updates.name!==old.name){authUpdate.user_metadata={name:updates.name,username:newUsername}}const {error:ue}=await admin.auth.admin.updateUserById(old.auth_user_id,authUpdate);if(ue)return respond(400,{ok:false,error:'auth_update_failed',message:ue.message});const {data,error}=await admin.from('jf_technicians').update(updates).eq('id',id).eq('workspace_hash',workspace).select().single();if(error)throw error;return respond(200,{ok:true,item:data})}
  if(action==='reset_password'){const id=clean(body.id),password=clean(body.password);if(!id||password.length<8)return respond(400,{ok:false,error:'id_password_required'});const {data:t,error:te}=await admin.from('jf_technicians').select('*').eq('id',id).eq('workspace_hash',workspace).maybeSingle();if(te)throw te;if(!t)return respond(404,{ok:false,error:'not_found'});const {error}=await admin.auth.admin.updateUserById(t.auth_user_id,{password});if(error)return respond(400,{ok:false,error:'password_reset_failed',message:error.message});return respond(200,{ok:true})}
  return respond(400,{ok:false,error:'unknown_action'})
 }catch(e){console.error(e);return respond(500,{ok:false,error:'server_error',message:String((e as any)?.message||e)})}
})